// Every word the lab console shows, in English and Chinese (中文). Keys are grouped by the part
// of the page that uses them. Text between backticks is shown as `code` where the page renders
// rich text (the How to use panel, a few hints). Device screens and console output come from the
// virtual machines themselves; `scr.*` are only the Chinese captions shown under a screen.

export const STRINGS = {
  en: {
    'doc.title': 'Lab console · OneCard Lab',
    'app.brand': 'OneCard Lab',
    'app.title': 'Lab console',
    ribbon: 'LAB · not real money',
    skip: 'Skip to the machines',
    'nav.label': 'Other apps',
    'lang.label': 'Language',
    'nav.operator': 'Operator console',
    'nav.admin': 'School office',
    'nav.parent': 'Parent app',
    'nav.newTab': '(opens in a new tab)',
    'hdr.server.up': 'Cloud server on',
    'hdr.server.down': 'Cloud server off',
    'hdr.clock': 'Lab time',
    'jump.label': 'On this page',
    'jump.server': 'Cloud server',
    'jump.clock': 'Lab clock',
    'jump.faults': 'Faults',
    'jump.messages': 'Messages',
    'jump.console': 'Console',

    'banner.down.title': 'The cloud server is switched off',
    'banner.down.text':
      'Every school lost it at the same moment. Canteen readers and water machines keep selling offline and keep their records; the kiosk adds nothing; parents cannot pay; the school office cannot load.',
    'banner.down.button': 'Switch the server on',
    'banner.net.title': 'Cannot reach the lab',
    'banner.net.text': 'The browser cannot reach the lab server. Is it still running? This page keeps trying every few seconds.',
    'banner.busy.title': 'The lab is setting up the demo',
    'banner.busy.text': 'This takes a moment. The page updates by itself.',
    'toast.back': 'The lab is reachable again.',

    'help.title': 'How to use this page',
    'help.tip': 'Pick a card in a card tray, press “Tap card” on a machine, then watch its screen, the card’s balance and the messages.',
    'help.intro':
      'Everything here is virtual: one cloud server serves many schools, and each school has its own machines, cards and admin card. Try this:',
    'help.s1':
      'Pick a card in a school’s card tray, then press “Tap card” on a machine. Its screen answers, the card’s balance changes and the messages appear in the inspector.',
    'help.s2': 'Pull a machine’s cable: it keeps selling offline and keeps the records. Plug it back in and watch it upload them.',
    'help.s3':
      'The admin card carries new prices and block lists to machines without a network: load it at the kiosk, tap it on the machine, then upload the receipts at the kiosk.',
    'help.s4': 'Faults show what can go wrong and how the system catches it. The lab clock moves time forward for refunds and checks.',
    'help.s5':
      'Switch the cloud server off to see what one server means for every school. A school onboarded in the operator console appears here by itself.',
    'help.exercises': 'Step-by-step exercises are in `docs/SCENARIOS.md`.',
    'help.outside': 'Outside apps that work with the lab',
    'help.putty.title': 'PuTTY: the machine consoles',
    'help.putty.text':
      'Host `{host}`, Port `{port}`, Connection type Telnet → Open. Type `machines`, then `connect smk-contoh/CANTEEN-01`.',
    'help.putty.nc': 'Mac or Linux: `nc {host} {port}` (or `telnet {host} {port}`).',
    'help.putty.off':
      'This lab was started with the consoles switched off (`LAB_CONSOLE_PORT=0`), so PuTTY cannot connect to it now. The Console tab on this page still works.',
    'help.mqtt.title': 'MQTT Explorer: watch the messages',
    'help.mqtt.text':
      'Host `{host}`, Port `{port}`, Username `{user}`, Password `{pass}` → Connect (the default `#` subscription works). The tree shows `lab/v1/<school>/<machine>/…` live, like Wireshark for the machines.',
    'help.phone.title': 'Phone: the parent app',
    'help.phone.text': 'Start the lab with `npm run start:lan` and open the address it prints, `/parent/`, on a phone on the same Wi-Fi.',

    'cloud.title': 'Virtual cloud server',
    'cloud.sub': 'One server for every school: MQTT broker, platform, database and web apps.',
    'cloud.on': 'On',
    'cloud.off': 'Off',
    'cloud.broker': 'MQTT broker',
    'cloud.broker.up': 'Running · {n} connections',
    'cloud.broker.down': 'Stopped',
    'cloud.platform': 'Platform',
    'cloud.platform.on': 'Listening to the broker',
    'cloud.platform.off': 'Not on the broker',
    'cloud.db': 'Database',
    'cloud.db.on': '{n} schools',
    'cloud.db.off': 'Unreachable while off',
    'cloud.clients': 'Broker connections: {list}',
    'cloud.clients.platform': 'platform',
    'cloud.clients.none': 'none',
    'cloud.switchOff': 'Switch server off',
    'cloud.switchOn': 'Switch server on',
    'cloud.restart': 'Restart broker',
    'cloud.restartOff': 'The broker can only be restarted while the server is on.',
    'cloud.busyOff': 'Switching off…',
    'cloud.busyOn': 'Switching on…',
    'cloud.busyRestart': 'Restarting…',
    'cloud.internet': 'Internet',
    'toast.serverOff': 'The cloud server is off. Machines keep working offline.',
    'toast.serverOn': 'The cloud server is on. Machines reconnect by themselves within about 10 seconds and upload what they kept.',
    'toast.serverSameOn': 'The cloud server was already on.',
    'toast.serverSameOff': 'The cloud server was already off.',
    'toast.brokerRestarted':
      'The broker restarted. The platform is back on it and sends the retained settings again; the machines reconnect within seconds.',

    'site.network': 'School network',
    'site.counts': '{machines} machines · {connected} connected · {cards} cards',
    'site.status.ACTIVE': 'Active',
    'site.status.SUSPENDED': 'Suspended',
    'site.suspended':
      'Suspended by the platform operator: its machines are disconnected, its uploads refused and its staff and parents blocked. The other schools carry on.',
    'site.noMachines': 'No machines yet. Register one in the school office.',
    'site.new': 'New on the platform',

    'type.CANTEEN': 'Canteen reader',
    'type.WATER': 'Water machine',
    'type.KIOSK': 'Top-up kiosk',
    'm.status.connected': 'Connected',
    'm.status.connecting': 'Connecting…',
    'm.status.serverOff': 'Offline: server off',
    'm.status.noNetwork': 'No network',
    'm.status.suspended': 'Refused: school suspended',
    'm.status.DISABLED': 'Switched off by the school',
    'm.status.MAINTENANCE': 'In maintenance',
    'm.status.installing': 'Being installed…',
    'm.cable': 'Cable',
    'm.cable.in': 'Plugged in',
    'm.cable.out': 'Pulled out',
    'm.platform': 'Platform view',
    'm.platform.online': 'Online · last heard {time}',
    'm.platform.offline': 'Offline · last heard {time}',
    'm.platform.never': 'Offline · never heard',
    'm.versions': 'Versions',
    'm.versions.value': 'Prices v{p} · Settings v{s} · Block list v{b}',
    'm.journal': 'Journal',
    'm.journal.value': '{unsent} unsent of {total} records',
    'm.lastMsg': 'Last message',
    'm.lastMsg.none': 'None since this page opened',
    'm.lastMsg.up': '↑ {type} · {time}',
    'm.lastMsg.down': '↓ {type} · {time}',
    'm.screen': 'Screen of {code}',
    'm.why': 'Why (only the lab shows this): {reason}.',
    'm.tap': 'Tap card',
    'm.pull': 'Pull cable',
    'm.plug': 'Plug cable in',
    'm.more': 'More',
    'm.moreLabel': 'More for {code}',
    'm.export': 'Export journal to USB',
    'm.heartbeat': 'Send a heartbeat now',
    'm.upload': 'Upload unsent records now',
    'm.reboot': 'Reboot (counters survive)',
    'm.adminTap': 'Tap the admin card here',
    'm.adminLoad': 'Load the admin card here',
    'm.adminUpload': 'Upload admin-card receipts here',
    'm.console': 'Open its console',
    'm.note.KIOSK': 'The only machine that adds money, and only while online.',
    'm.note.WATER': '{perLitre} per litre, at least {min}.',
    'm.note.CANTEEN': 'Price list v{version}: {items} items.',
    'toast.cableOut': '{code}: cable pulled out. It keeps working offline; its records wait in its journal.',
    'toast.cableIn': '{code}: cable plugged in. It is connected and has uploaded what it kept.',
    'toast.cableInWait': '{code}: cable plugged in. It keeps trying to connect by itself.',
    'toast.exported': '{code}: journal saved as {file} ({count} records). Import it in the school office, under reconciliation.',
    'toast.heartbeat': '{code}: heartbeat sent.',
    'toast.upload': '{code}: unsent records uploaded.',
    'toast.uploadNone': '{code}: nothing to upload, every record is sent.',
    'toast.reboot': '{code}: rebooted. Its counters and journal survived.',
    'toast.notConnected': '{code} is not connected to the broker: plug its cable in (and switch the server on) first.',
    'toast.consoleSaid': '{code}: {output}',

    'tray.title': 'Card tray',
    'tray.hint': 'Pick a card, then press “Tap card” on a machine.',
    'tray.picked': 'Picked: {name}, {balance} on the chip. Now press “Tap card” on a machine.',
    'tray.empty': 'No cards yet. Issue cards in the school office.',
    'card.onChip': 'on the chip',
    'card.counter': 'counter {n}',
    'card.status.ACTIVE': 'Active',
    'card.status.LOST': 'Reported lost',
    'card.status.RETIRED': 'Replaced',
    'card.status.none': 'Unknown to the platform',
    'card.copy': 'Copy of {uid}',
    'card.tampered': 'Tampered: every machine refuses it',
    'card.staff': 'Staff',
    'card.noMember': 'No cardholder',

    'admin.title': 'Admin card',
    'admin.what': 'Carries new prices, settings and block lists to machines that have no network.',
    'admin.empty': 'Not loaded yet: load it at the kiosk.',
    'admin.loaded': 'Token {token} · loaded {time}',
    'admin.packs': 'Carries {list}.',
    'admin.receipts': 'Receipts waiting: {n}',
    'admin.receipts.none': 'No receipts waiting.',
    'admin.load': 'Load at {kiosk}',
    'admin.tapLabel': 'Tap it on',
    'admin.tap': 'Tap admin card',
    'admin.upload': 'Upload receipts at {kiosk}',
    'admin.noKiosk': 'This school has no kiosk, so its admin card cannot be loaded.',
    'admin.receipt': '{device}: {kind} v{version} {result}',
    'result.APPLIED': 'applied',
    'result.ALREADY_APPLIED': 'already had it',
    'result.REJECTED': 'rejected',
    'kind.prices': 'prices',
    'kind.settings': 'settings',
    'kind.blocklist': 'block list',
    'list.sep': ', ',
    colon: ': ',

    'tap.title': 'Tap a card on {code}',
    'tap.where': '{type} · {location} · {school}',
    'tap.card': 'Card',
    'tap.cardInfo': '{balance} on the chip · counter {n} · {status}',
    'tap.otherSchool':
      'This card belongs to {school}. A machine of another school will refuse it: each school has its own card key. Try it, that is the cross-school check.',
    'tap.items': 'What to buy',
    'tap.itemsNote': 'From this machine’s own price list (v{version}). An offline machine may still use an older one.',
    'tap.less': 'One less {name}',
    'tap.more': 'One more {name}',
    'tap.qty': 'How many {name}',
    'tap.total': 'Total {amount}',
    'tap.pay': 'Tap card · pay {amount}',
    'tap.pickItems': 'Choose at least one item first.',
    'tap.water': 'How much water',
    'tap.ml': 'Millilitres',
    'tap.mlUnit': '{ml} ml',
    'tap.waterCost': 'About {amount} ({perLitre} per litre, at least {min}).',
    'tap.waterNote': 'The machine pours less if the card cannot pay for it all.',
    'tap.pour': 'Tap card · pour {ml} ml',
    'tap.mlInvalid': 'Choose from 1 to 20000 ml.',
    'tap.kiosk': 'The kiosk reads the card, sends its recent records to the platform, then adds any money waiting for it.',
    'tap.fault': 'Kiosk fault (optional)',
    'tap.fault.none': 'None: a normal tap',
    'tap.go': 'Tap card',
    'tap.busy': 'Tapping…',
    'tap.noCards': 'There are no cards to tap yet.',
    cancel: 'Cancel',
    close: 'Close',
    working: 'Working…',

    'fault.title': 'Faults',
    'fault.intro':
      'Make something go wrong on purpose and see how the system catches it. Each one shows up where a school would see it: refusal codes, the device log or reconciliation.',
    'fault.machine': 'Machine for the faults',
    'fault.card': 'Card for the faults',
    'fault.group.cards': 'Cards',
    'fault.group.messages': 'Machines and messages',
    'fault.group.kiosk': 'Top-up kiosk',
    'fault.group.server': 'Cloud server',
    'fault.run': 'Try it',
    'fault.needCard': 'Choose a card first.',
    'fault.needMachine': 'Choose a machine first.',
    'fault.needKiosk': 'The card’s school has no kiosk.',
    'fault.needOther': 'There is no other school to try this on.',
    'fault.kioskAt': 'At {kiosk} of {school}, with the card chosen above.',
    'fault.target': 'Target',
    'fault.target.auto': 'Another machine of the same school',
    'fault.on': 'On',
    'fault.amount': 'New balance (RM)',
    'fault.amountInvalid': 'Enter an amount in ringgit, for example 100.00.',
    'fault.clone-card.title': 'Copy a card',
    'fault.clone-card.text':
      'Copies the chip byte for byte, security code and all. Spend on both: the platform finds two purchases with the same card counter.',
    'fault.tamper-card.title': 'Tamper with a card',
    'fault.tamper-card.text': 'Changes the balance on the chip by hand. Its security code no longer matches, so every machine refuses it.',
    'fault.cross-school-card.title': 'Card from another school',
    'fault.cross-school-card.text':
      'Taps the card on another school’s machine. Each school has its own card key, so the card is refused (Card unavailable).',
    'fault.duplicate-upload.title': 'Send a record twice',
    'fault.duplicate-upload.text':
      'Sends the machine’s last record again in a new message. The platform answers DUPLICATE and still counts it once.',
    'fault.sequence-rollback.title': 'Sequence rollback',
    'fault.sequence-rollback.text':
      'Sends a properly signed message numbered behind what the platform already accepted, like a replayed or restored machine. Refused with SEQUENCE_ROLLBACK.',
    'fault.forged-message.title': 'Forged message',
    'fault.forged-message.text':
      'Sends a message that is not signed with the machine’s secret. Refused with SIGNATURE_INVALID; the school office shows it in the device log.',
    'fault.cross-device-publish.title': 'Publish to another machine’s topic',
    'fault.cross-device-publish.text':
      'Logs in with this machine’s login and publishes on another machine’s topic. The broker refuses and closes that connection; the real machine is knocked off for about a second.',
    'fault.power-cut-before-commit.title': 'Power cut before writing',
    'fault.power-cut-before-commit.text': 'The kiosk loses power before the money reaches the card. Nothing is written; the money keeps waiting.',
    'fault.power-cut-after-commit.title': 'Power cut after writing',
    'fault.power-cut-after-commit.text':
      'The money reaches the card, but the platform never hears. The next tap at the kiosk finds the write and confirms it.',
    'fault.confirm-timeout.title': 'Confirmation lost',
    'fault.confirm-timeout.text':
      'The kiosk’s confirmation times out. It looks the result up by the same transaction number and never writes the card twice.',
    'fault.server-down.title': 'Switch the cloud server off',
    'fault.server-down.text': 'Every school loses it at once: readers keep selling offline, the kiosk adds nothing, parents cannot pay.',
    'fault.server-up.title': 'Switch it back on',
    'fault.server-up.text': 'Machines reconnect by themselves and upload what they kept; the platform sends every machine its settings again.',
    'fault.broker-restart.title': 'Restart only the broker',
    'fault.broker-restart.text': 'Retained messages are lost with it; the platform puts them back as soon as it reconnects.',

    'fr.clone': 'Card {from} copied as {copy}: same balance {balance}, same counter {n}, valid security code. Spend on both, then tap the original at the kiosk.',
    'fr.tamper': 'Card {uid} now shows {balance}, but its security code no longer matches: every machine refuses it.',
    'fr.dup.ok': 'Record {txn} sent again: the platform answered DUPLICATE, so it still counts once.',
    'fr.dup.other': 'Record {txn} sent again: the platform answered {status}.',
    'fr.seq.ok': 'A signed message numbered {seq} (the platform had already accepted {last}) was refused: SEQUENCE_ROLLBACK. The school office shows it in the device log.',
    'fr.seq.wait': 'The message was sent, but the platform has not answered yet.',
    'fr.forged.ok': 'A {type} not signed with the machine’s secret was refused: SIGNATURE_INVALID. The school office shows it in the device log.',
    'fr.forged.other': 'A forged {type} was sent; the platform answered {code}.',
    'fr.cross.ok': 'Logged in as {from} and published on {topic}: the broker refused it and closed that connection. Nothing reached the platform.',
    'fr.cross.offline': 'The copied login knocked the real machine off the broker for about {s} s.',
    'fr.cross.login': 'The broker refused the login of {from}: nothing was published.',
    'fr.cross.bad': 'Published on {topic} as {from}: the broker did NOT refuse it. That must never happen.',
    'fr.crossSchool.refused': 'A card of {from} on {machine}: “{screen}”. The card means nothing to another school’s machines.',
    'fr.crossSchool.accepted': 'A card of {from} was ACCEPTED by {machine}. That must never happen.',
    'fr.server.off': 'The cloud server is off. Every school lost it at once.',
    'fr.server.on': 'The cloud server is on. Watch the machines reconnect and upload what they kept.',
    'fr.server.same': 'Nothing changed: the cloud server was already {state}.',
    'fr.broker': 'The broker restarted; the platform is back on it and publishes the retained settings again.',
    'fr.kiosk.before': 'Power cut before writing: nothing reached the card. {amount} keeps waiting; tap again without a fault to add it.',
    'fr.kiosk.after':
      'Power cut after writing: {amount} is on the card, but the platform never heard. Tap the card on the kiosk again: it finds the write and confirms it.',
    'fr.kiosk.timeout':
      'The confirmation was lost: the kiosk looked {txn} up and confirmed {amount} without writing the card a second time.',
    'fr.kiosk.nothing':
      'Nothing was waiting for this card, so there was nothing to cut. Top it up first (parent app, or a subsidy in the school office), then try again.',
    'fr.kiosk.refused': 'The kiosk refused: “{screen}” ({reason}).',
    'fr.kiosk.shows': 'The kiosk shows “{screen}”.',
    'fr.kiosk.reconfirmed': 'It found its earlier write {txn} on the card and confirmed it to the platform: the order is now added, without writing the card again.',
    'state.on': 'on',
    'state.off': 'off',

    'clock.title': 'Lab clock',
    'clock.kl': 'Kuala Lumpur time',
    'clock.running': 'Running',
    'clock.manual': 'Standing still until moved',
    'clock.h1': '+1 hour',
    'clock.d1': '+1 day',
    'clock.d15': '+15 days',
    'clock.jobs': 'Run jobs now',
    'clock.note':
      'Moving the clock makes every connected machine send a heartbeat, then runs the scheduled jobs: unpaid orders are cancelled, money never added is refunded after 14 days, and reconciliation looks for missing records and old block lists.',
    'clock.jobsResult':
      'Jobs: {cancelled} cancelled · {refunded} refunded · {parked} parked for a person · {gaps} missing-record gaps · {lag} old block lists.',
    'clock.moved': 'Clock moved forward {by}.',
    'clock.serverOff': 'The server is off, so the jobs did not run.',
    'clock.jobsOff': 'The jobs run on the cloud server: switch it on first.',
    'clock.reset': 'Reset the demo…',
    'reset.title': 'Start the demo again?',
    'reset.text':
      'Everything goes back to the start: a fresh database, clock, cards and machines. People signed in to the other apps have to sign in again.',
    'reset.confirm': 'Reset the demo',
    'reset.done': 'The demo started again.',
    'dur.minutes': '{n} minutes',
    'dur.hour': '1 hour',
    'dur.hours': '{n} hours',
    'dur.day': '1 day',
    'dur.days': '{n} days',

    'tabs.label': 'Messages and console',
    'insp.tab': 'Messages',
    'insp.title': 'Message inspector',
    'insp.live': 'Live',
    'insp.reconnecting': 'Reconnecting…',
    'insp.pausedCount': 'Paused · {n} new',
    'insp.school': 'School',
    'insp.allSchools': 'All schools',
    'insp.labOnly': 'Server and lab only',
    'insp.kinds': 'Show',
    'kind.mqtt': 'MQTT',
    'kind.platform': 'Platform',
    'kind.money': 'Money',
    'kind.differences': 'Differences',
    'kind.cards': 'Cards',
    'kind.lab': 'Machines and lab',
    'insp.heartbeats': 'Heartbeats',
    'insp.pause': 'Pause',
    'insp.resume': 'Resume',
    'insp.clear': 'Clear',
    'insp.count': '{shown} of {total} messages',
    'insp.col.time': 'Time',
    'insp.col.school': 'School',
    'insp.col.machine': 'Machine',
    'insp.col.type': 'Type',
    'insp.empty': 'No messages yet. Tap a card on a machine and watch them arrive here.',
    'insp.emptyFiltered': 'No messages match the filters.',
    'insp.onlyHeartbeats': 'Only heartbeats so far, and they are hidden: tick “Heartbeats” to see them, or tap a card on a machine.',
    'insp.server': 'lab',

    'con.tab': 'Console',
    'con.title': 'Machine and server consoles',
    'con.hint': 'Same console in PuTTY: Telnet to {host} port {port}.',
    'con.hintOff': 'Same console in PuTTY: Telnet to 127.0.0.1 port 2323 (this lab was started with the PuTTY consoles off).',
    'con.intro':
      'Consoles of the virtual machines and the virtual cloud server, like logging in to a switch. Type `machines` to list the machines, `connect smk-contoh/CANTEEN-01` to log in to one, `connect server` for the cloud server, and `help` (or `?`) for the commands. ↑ and ↓ bring back earlier commands.',
    'con.command': 'Command at {prompt}',
    'con.run': 'Run',
    'con.clear': 'Clear',
    'con.quick': 'Try',
    'con.closed': 'Session closed. Type a command to start again.',
    'con.failed': '% Could not run the command: {message}',

    'err.other': '{message} ({code})',
    'err.NETWORK': 'The browser cannot reach the lab server. Is it still running?',
    'err.SERVER_DOWN': 'The cloud server is switched off: switch it on first.',
    'err.LAB_BUSY': 'The lab is setting up the demo. Try again in a moment.',
    'err.LAB_NOT_RUNNING': 'The lab is not running.',
    'err.MACHINE_OFFLINE': 'That machine is not connected to the broker: plug its cable in (and switch the server on) first.',
    'err.NOTHING_TO_SEND': 'That machine has no record to send again: sell something on it first.',
    'err.NOTHING_TO_ROLL_BACK': 'The platform has not accepted a message from that machine yet: plug it in or send a heartbeat first.',
    'err.CARD_NOT_FOUND': 'That card is not in the card tray.',
    'err.CARD_UID_INVALID': 'That is not a card number.',
    'err.MACHINE_NOT_FOUND': 'That machine is not in the lab.',
    'err.ADMIN_CARD_NOT_FOUND': 'This school has no admin card in the lab.',
    'err.WRONG_MACHINE_TYPE': 'The admin card is loaded and emptied at a kiosk.',
    'err.SCHOOL_NOT_FOUND': 'There is no such school.',
    'err.INPUT_INVALID': 'The lab could not use what was sent: {message}',
    'err.FAULT_INVALID': 'That fault does not work here: {message}',
    'err.CROSS_ORIGIN': 'The server refused a request that did not come from this page. Reload the page and try again.',
    'err.INTERNAL': 'Something went wrong in the lab server. Check the terminal that runs the lab.',

    'reason.BLOCKED': 'the card is on the block list',
    'reason.CARD_UNREADABLE': 'the card’s security code does not match (it was edited by hand)',
    'reason.WRONG_SCHOOL': 'the card belongs to another school',
    'reason.NO_BLOCKLIST': 'the machine has never received a block list',
    'reason.NOT_READY': 'the machine has no prices or settings yet',
    'reason.JOURNAL_FULL': 'the machine’s journal is full',
    'reason.ITEMS_INVALID': 'the order was not valid',
    'reason.UNKNOWN_ITEM': 'an item is not on this machine’s price list',
    'reason.AMOUNT_INVALID': 'no amount of water was chosen',
    'reason.CLOSED': 'it is outside the meal times',
    'reason.GROUP_NOT_ALLOWED': 'this group of cardholders is not allowed here',
    'reason.PER_PURCHASE_LIMIT': 'above the limit per purchase',
    'reason.DAILY_LIMIT': 'above the daily limit',
    'reason.DAILY_COUNT': 'too many purchases today',
    'reason.TAP_GAP': 'the same card was tapped again too soon',
    'reason.INSUFFICIENT_BALANCE': 'not enough money on the card',
    'reason.OFFLINE': 'the kiosk has no connection to the broker',
    'reason.PLATFORM_UNREACHABLE': 'the platform did not answer the kiosk',
    'reason.CARD_NOT_ACTIVE': 'the platform says this card is lost or replaced',
    'reason.CARD_NOT_FOUND': 'the platform does not know this card',
    'reason.POWER_CUT': 'the power was cut while writing the card',
    'reason.PACKS_INVALID': 'the packs did not fit the admin card',

    // event summaries (message inspector)
    'ev.someone': 'someone',
    'ev.platform': 'the platform',
    'ev.viewer': 'a read-only viewer',
    'ev.retained': 'retained',
    'ev.bytes': '{n} bytes',
    'ev.mqtt.connect': '{who} logged in to the broker',
    'ev.mqtt.disconnect': '{who} left the broker',
    'ev.mqtt.denied': 'Broker refused the {action} of {who}',
    'ev.mqtt.denied.topic': 'Broker refused the {action} of {who} on {topic}',
    'ev.action.connect': 'login',
    'ev.action.publish': 'publish',
    'ev.action.subscribe': 'subscribe',
    'ev.mqtt.up': 'Machine → broker: {type} on {topic}',
    'ev.mqtt.down': 'Platform → machine: {type} on {topic}',
    'ev.mqtt.other': '{from} → broker: {type} on {topic}',
    'ev.intake.accepted': 'Platform accepted {type}',
    'ev.intake.duplicate': 'Platform already had this {type}: ignored, it counts once',
    'ev.intake.refused': 'Platform refused {type}: {code} ({why})',
    'ev.records': '{n} records ({list})',
    'ev.purchase': '{txn}: {amount} {status}, via {via}',
    'ev.purchase.diffs': ' · differences: {list}',
    'ev.ledger': '{kind} {amount}: {lines}',
    'ev.dr': 'DR',
    'ev.cr': 'CR',
    'ev.topup.status': '{kind} {amount}: {status}',
    'ev.topup.refunded': '{kind} {amount} refunded to the parent (mock bank)',
    'ev.topup.returned': '{kind} {amount} not added in time: returned to the school',
    'ev.config': 'New {kind}: version {version}',
    'ev.card.issued': 'Card {uid} issued',
    'ev.card.lost': 'Card {uid} reported lost · block list v{version}',
    'ev.card.found': 'Card {uid} found again · block list v{version}',
    'ev.card.debit': 'Card {uid}: −{amount} → {balance}',
    'ev.card.credit': 'Card {uid}: +{amount} → {balance}',
    'ev.screen': 'Screen: {text}',
    'ev.cable.in': 'Cable plugged in',
    'ev.cable.out': 'Cable pulled out',
    'ev.admin.loaded': 'Admin card loaded · token {token} · {packs}',
    'ev.admin.applied': 'Admin card read: {applied} applied, {already} already had it, {rejected} rejected',
    'ev.diff.opened': 'Difference: {kind}',
    'ev.diff.resolved': 'Resolved: {kind}',
    'ev.audit': '{actor}: {action}',
    'ev.lab.tap': 'You tapped {uid} on {device}: “{screen}”',
    'ev.lab.tapFault': ' · fault: {fault}',
    'ev.lab.tapOther': ' · a card of {school}',
    'ev.lab.usb': 'You exported {device}’s journal to USB: {count} records',
    'ev.lab.reboot': 'You rebooted {device}',
    'ev.lab.jobs': 'Jobs ran: {cancelled} cancelled · {refunded} refunded · {parked} parked · {gaps} gaps · {lag} old lists',
    'ev.lab.serverUp': 'You switched the cloud server on',
    'ev.lab.serverDown': 'You switched the cloud server off',
    'ev.lab.same': ' (it already was)',
    'ev.lab.brokerRestart': 'You restarted the broker',
    'ev.lab.reset': 'The demo started again',
    'ev.lab.fault': 'Fault: {name}',
    'ev.lab.clock': 'Clock moved forward {by} → {kl}',
    'ev.tenant': 'New school on the platform: {name} ({code})',
    'ev.school.status': '{code}: {from} → {status}',
    'ev.device.registered': 'New machine {code} ({type})',
    'ev.server.up': 'Cloud server switched on',
    'ev.server.down': 'Cloud server switched off',
    'ev.broker.up': 'Broker running at {url}',
    'ev.broker.down': 'Broker stopped ({reason})',

    'evx.mqtt.connect': 'Someone logged in to the MQTT broker: a machine, the platform or a viewer such as MQTT Explorer.',
    'evx.mqtt.disconnect': 'A connection to the MQTT broker ended: a cable pulled, the server switched off, a broker restart or a kick.',
    'evx.mqtt.denied': 'The broker refused a login, publish or subscribe that the account is not allowed to do.',
    'evx.mqtt.publish':
      'A message passed through the broker: records and status go up from the machines; prices, settings, block lists and commands come down from the platform.',
    'evx.intake.accepted': 'The platform checked the message (topic, signature, sequence number, school and machine) and accepted it.',
    'evx.intake.duplicate': 'The platform had already received this exact message. It is ignored, so nothing counts twice.',
    'evx.intake.refused': 'The platform refused the message. The code says why, and the school office shows it in the device log.',
    'evx.purchase.received': 'A purchase record reached the platform: posted to the books, flagged, a duplicate or refused.',
    'evx.ledger.posting': 'A double-entry posting in the school’s books: the debits always equal the credits.',
    'evx.topup.status': 'A top-up, subsidy or balance-transfer order changed status.',
    'evx.topup.refunded': 'Money that never reached the card was given back: a parent’s top-up to the parent (through the mock bank), a subsidy to the school.',
    'evx.config.published': 'The school published a new price list, settings or block list. Networked machines get it at once.',
    'evx.card.issued': 'The school issued a card; the lab made the virtual card itself (balance RM 0.00).',
    'evx.card.lost': 'A card was reported lost and put on the block list.',
    'evx.card.found': 'A lost card was found and taken off the block list.',
    'evx.card.write': 'A machine wrote to a card’s chip: a debit at a reader or water machine, a credit at the kiosk.',
    'evx.device.screen': 'What a machine’s screen shows now.',
    'evx.device.cable': 'A machine’s network cable was plugged in or pulled out.',
    'evx.admin-card.loaded': 'The kiosk loaded the admin card with the newest packs and a fresh token.',
    'evx.admin-card.applied': 'A machine read the admin card and wrote a receipt for each pack.',
    'evx.difference.opened': 'Reconciliation found something a person at the school office should look at.',
    'evx.difference.resolved': 'A person at the school office resolved a difference, with a note.',
    'evx.audit': 'Something done at the school office or by the operator, kept in the audit trail.',
    'evx.lab.action': 'Something you did in the lab: a tap, a fault, a server switch.',
    'evx.lab.clock': 'The lab clock moved forward.',
    'evx.tenant.created': 'The operator onboarded a new school. Its machines, cards and admin card appear in the lab.',
    'evx.school.status': 'The operator suspended or reactivated a school.',
    'evx.device.registered': 'A new machine was registered; the lab installs it.',
    'evx.server.status': 'The virtual cloud server was switched on or off.',
    'evx.broker.status': 'The MQTT broker started or stopped.',
    'evx.other': 'A lab event.',

    'refusal.TOPIC_INVALID': 'not a device topic',
    'refusal.UNKNOWN_DEVICE': 'no such school or machine',
    'refusal.ENVELOPE_INVALID': 'malformed message',
    'refusal.VERSION_UNSUPPORTED': 'protocol version not supported',
    'refusal.UNKNOWN_TYPE': 'unknown message type',
    'refusal.TOPIC_MISMATCH': 'school, machine or channel does not match the topic',
    'refusal.SIGNATURE_INVALID': 'the signature does not match',
    'refusal.SEQUENCE_ROLLBACK': 'the sequence number went backwards',
    'refusal.SCHOOL_SUSPENDED': 'the school is suspended',
    'refusal.DEVICE_DISABLED': 'the machine is switched off',
    'refusal.WRONG_DEVICE_TYPE': 'this kind of machine may not send this',
    'refusal.COUNT_MISMATCH': 'the batch count does not match',
    'refusal.RECORD_INVALID': 'malformed record',
    'refusal.UNKNOWN_ORIGIN_DEVICE': 'names a machine the school does not have',
    'refusal.INTERNAL': 'an error inside the platform',
    'refusal.other': 'see the device log',

    'diff.MISSING_RECORDS': 'A purchase the platform never received (gap in a machine’s transaction numbers)',
    'diff.DUPLICATE_CONFLICT': 'Same transaction number uploaded twice with different content',
    'diff.UNKNOWN_CARD': 'Purchase from a card this school does not know',
    'diff.PRICE_VERSION_UNKNOWN': 'Record names a price list version that was never issued',
    'diff.PRICE_MISMATCH': 'Amount does not match the price list version the machine used',
    'diff.BALANCE_CONTINUITY': 'Balance before minus amount does not equal balance after',
    'diff.BALANCE_MISMATCH': 'Card balance does not match the platform’s mirror balance',
    'diff.MIRROR_NEGATIVE': 'Mirror balance went below zero',
    'diff.SPENT_AFTER_LOST_REPORT': 'Card used after it was reported lost',
    'diff.CARD_CLONE_SUSPECTED': 'Two different purchases carry the same card counter (possible copied card)',
    'diff.OLD_BLOCK_LIST': 'Machine is still on an old block list',
    'diff.TOPUP_ADDED_AFTER_REFUND': 'Kiosk reports adding money that was already refunded',
    'diff.DOUBLE_ADD_SUSPECTED': 'The same top-up was reported added by a different write',

    'acct.CASH_RECEIVED': 'Cash received',
    'acct.STUDENT_WALLET': 'Student wallet',
    'acct.WAITING_TO_BE_ADDED': 'Waiting to be added',
    'acct.SCHOOL_SUBSIDY': 'School subsidy',
    'acct.SALES_PAYABLE': 'Sales payable',

    'order.TOPUP': 'Top-up',
    'order.SUBSIDY': 'Subsidy',
    'order.TRANSFER': 'Balance transfer',
    'topup.CREATED': 'created, waiting for payment',
    'topup.PAID': 'paid, waiting to be added at the kiosk',
    'topup.ADDED': 'added to the card',
    'topup.CANCELLED': 'cancelled (not paid in time)',
    'topup.FAILED': 'payment failed',
    'topup.EXPIRED': 'expired',
    'topup.REFUNDED': 'refunded',
    'topup.PARKED': 'parked for a person',
    'purchase.POSTED': 'posted',
    'purchase.FLAGGED': 'flagged',
    'purchase.DUPLICATE': 'duplicate',
    'purchase.REFUSED': 'refused',
    'via.MQTT': 'MQTT',
    'via.JOURNAL_BATCH': 'journal batch',
    'via.KIOSK_READBACK': 'kiosk read-back',
    'via.USB_IMPORT': 'USB import',
  },

  zh: {
    'doc.title': '实验室控制台 · OneCard Lab',
    'app.brand': 'OneCard Lab',
    'app.title': '实验室控制台',
    ribbon: '实验室 · 不是真钱',
    skip: '跳到机器',
    'nav.label': '其他应用',
    'lang.label': '语言',
    'nav.operator': '平台运营后台',
    'nav.admin': '学校后台',
    'nav.parent': '家长网页',
    'nav.newTab': '（在新分页打开）',
    'hdr.server.up': '云端服务器：开',
    'hdr.server.down': '云端服务器：关',
    'hdr.clock': '实验室时间',
    'jump.label': '本页内容',
    'jump.server': '云端服务器',
    'jump.clock': '实验室时钟',
    'jump.faults': '故障',
    'jump.messages': '消息',
    'jump.console': '控制台',

    'banner.down.title': '云端服务器已关掉',
    'banner.down.text':
      '所有学校在同一刻失去了它。食堂刷卡机和饮水机继续离线售卖，记录留在机器里；充值机加不了钱；家长付不了款；学校后台打不开。',
    'banner.down.button': '打开服务器',
    'banner.net.title': '连不上实验室',
    'banner.net.text': '浏览器连不上实验室服务器。它还在运行吗？本页每隔几秒会自动重试。',
    'banner.busy.title': '实验室正在布置演示',
    'banner.busy.text': '稍等一下，页面会自己更新。',
    'toast.back': '已重新连上实验室。',

    'help.title': '这个页面怎么用',
    'help.tip': '在卡片托盘里选一张卡，在机器上按“刷卡”，再看机器屏幕、卡上余额和消息。',
    'help.intro': '这里的一切都是虚拟的：一台云端服务器服务很多学校，每所学校有自己的机器、卡和参数卡。试试看：',
    'help.s1': '在学校的卡片托盘里选一张卡，再在机器上按“刷卡”。机器屏幕会回应，卡上余额会变，消息检视器里会出现消息。',
    'help.s2': '拔掉机器的网线：它会继续离线售卖并保留记录。再插回去，看它把记录上传。',
    'help.s3': '参数卡把新价格和黑名单带到没有网络的机器：在充值机装资料，刷在那台机器上，再回到充值机上传回执。',
    'help.s4': '故障演示会出什么问题、系统怎么发现。实验室时钟可以把时间拨快，用来看退款和对账。',
    'help.s5': '关掉云端服务器，看看“一台服务器”对每所学校意味着什么。在平台运营后台开通的新学校会自己出现在这里。',
    'help.exercises': '一步一步的练习在 `docs/SCENARIOS.md`。',
    'help.outside': '可以和实验室一起用的外部工具',
    'help.putty.title': 'PuTTY：机器控制台',
    'help.putty.text': 'Host `{host}`，Port `{port}`，Connection type 选 Telnet → Open。输入 `machines`，再输入 `connect smk-contoh/CANTEEN-01`。',
    'help.putty.nc': 'Mac 或 Linux：`nc {host} {port}`（或 `telnet {host} {port}`）。',
    'help.putty.off': '这个实验室启动时关掉了控制台（`LAB_CONSOLE_PORT=0`），所以现在 PuTTY 连不上。本页的“控制台”分页照样能用。',
    'help.mqtt.title': 'MQTT Explorer：看消息',
    'help.mqtt.text':
      'Host `{host}`，Port `{port}`，Username `{user}`，Password `{pass}` → Connect（默认的 `#` 订阅就行）。树状图会实时显示 `lab/v1/<学校>/<机器>/…`，就像机器的 Wireshark。',
    'help.phone.title': '手机：家长网页',
    'help.phone.text': '用 `npm run start:lan` 启动实验室，在同一个 Wi-Fi 的手机上打开它印出的地址 `/parent/`。',

    'cloud.title': '虚拟云端服务器',
    'cloud.sub': '一台服务器服务所有学校：MQTT broker、平台、数据库和网页。',
    'cloud.on': '开',
    'cloud.off': '关',
    'cloud.broker': 'MQTT broker',
    'cloud.broker.up': '运行中 · {n} 个连接',
    'cloud.broker.down': '已停止',
    'cloud.platform': '平台',
    'cloud.platform.on': '正在接收 broker 的消息',
    'cloud.platform.off': '没连上 broker',
    'cloud.db': '数据库',
    'cloud.db.on': '{n} 所学校',
    'cloud.db.off': '关机时无法访问',
    'cloud.clients': 'broker 连接：{list}',
    'cloud.clients.platform': '平台',
    'cloud.clients.none': '没有',
    'cloud.switchOff': '关掉服务器',
    'cloud.switchOn': '打开服务器',
    'cloud.restart': '重启 broker',
    'cloud.restartOff': '服务器开着时才能重启 broker。',
    'cloud.busyOff': '正在关机…',
    'cloud.busyOn': '正在开机…',
    'cloud.busyRestart': '正在重启…',
    'cloud.internet': '互联网',
    'toast.serverOff': '云端服务器已关掉。机器继续离线工作。',
    'toast.serverOn': '云端服务器已打开。机器会在约 10 秒内自己重新连上，并上传保留的记录。',
    'toast.serverSameOn': '云端服务器本来就开着。',
    'toast.serverSameOff': '云端服务器本来就关着。',
    'toast.brokerRestarted': 'broker 已重启。平台已重新连上并再次发送保留的设置；机器几秒内会重新连上。',

    'site.network': '学校网络',
    'site.counts': '{machines} 台机器 · {connected} 台已连线 · {cards} 张卡',
    'site.status.ACTIVE': '使用中',
    'site.status.SUSPENDED': '已停用',
    'site.suspended': '已被平台运营方停用：它的机器被断开、上传被拒，员工和家长被挡住。其他学校照常运作。',
    'site.noMachines': '还没有机器。请在学校后台登记。',
    'site.new': '平台上的新学校',

    'type.CANTEEN': '食堂刷卡机',
    'type.WATER': '饮水机',
    'type.KIOSK': '充值机',
    'm.status.connected': '已连线',
    'm.status.connecting': '连线中…',
    'm.status.serverOff': '离线：服务器关了',
    'm.status.noNetwork': '没有网络',
    'm.status.suspended': '被拒：学校已停用',
    'm.status.DISABLED': '被学校关掉',
    'm.status.MAINTENANCE': '维修中',
    'm.status.installing': '安装中…',
    'm.cable': '网线',
    'm.cable.in': '已插上',
    'm.cable.out': '已拔掉',
    'm.platform': '平台视角',
    'm.platform.online': '在线 · 最后心跳 {time}',
    'm.platform.offline': '离线 · 最后心跳 {time}',
    'm.platform.never': '离线 · 从没收到心跳',
    'm.versions': '版本',
    'm.versions.value': '价格 v{p} · 设置 v{s} · 黑名单 v{b}',
    'm.journal': '流水',
    'm.journal.value': '{total} 条记录中 {unsent} 条未上传',
    'm.lastMsg': '最后消息',
    'm.lastMsg.none': '本页打开后还没有',
    'm.lastMsg.up': '↑ {type} · {time}',
    'm.lastMsg.down': '↓ {type} · {time}',
    'm.screen': '{code} 的屏幕',
    'm.why': '原因（只有实验室看得到）：{reason}。',
    'm.tap': '刷卡',
    'm.pull': '拔网线',
    'm.plug': '插上网线',
    'm.more': '更多',
    'm.moreLabel': '{code} 的更多操作',
    'm.export': '把流水导出到 USB',
    'm.heartbeat': '立刻发送心跳',
    'm.upload': '立刻上传未上传的记录',
    'm.reboot': '重启（计数器保留）',
    'm.adminTap': '在这里刷参数卡',
    'm.adminLoad': '在这里给参数卡装资料',
    'm.adminUpload': '在这里上传参数卡回执',
    'm.console': '打开它的控制台',
    'm.note.KIOSK': '唯一能加钱的机器，而且只在在线时。',
    'm.note.WATER': '每公升 {perLitre}，最少 {min}。',
    'm.note.CANTEEN': '价格表 v{version}：{items} 样。',
    'toast.cableOut': '{code}：网线已拔掉。它继续离线工作，记录留在它的流水里。',
    'toast.cableIn': '{code}：网线已插上。它已连线，并上传了保留的记录。',
    'toast.cableInWait': '{code}：网线已插上。它会自己继续尝试连线。',
    'toast.exported': '{code}：流水已存成 {file}（{count} 条记录）。请在学校后台的对账页面导入。',
    'toast.heartbeat': '{code}：心跳已发送。',
    'toast.upload': '{code}：未上传的记录已上传。',
    'toast.uploadNone': '{code}：没有要上传的，每条记录都已送出。',
    'toast.reboot': '{code}：已重启。计数器和流水都保留着。',
    'toast.notConnected': '{code} 没连上 broker：请先插上网线（并打开服务器）。',
    'toast.consoleSaid': '{code}：{output}',

    'tray.title': '卡片托盘',
    'tray.hint': '先选一张卡，再在机器上按“刷卡”。',
    'tray.picked': '已选：{name}，卡上 {balance}。现在在机器上按“刷卡”。',
    'tray.empty': '还没有卡。请在学校后台发卡。',
    'card.onChip': '卡上余额',
    'card.counter': '计数 {n}',
    'card.status.ACTIVE': '正常',
    'card.status.LOST': '已挂失',
    'card.status.RETIRED': '已更换',
    'card.status.none': '平台不认识',
    'card.copy': '{uid} 的复制卡',
    'card.tampered': '被篡改：每台机器都会拒绝',
    'card.staff': '教职员',
    'card.noMember': '没有持卡人',

    'admin.title': '参数卡',
    'admin.what': '把新价格、设置和黑名单带到没有网络的机器。',
    'admin.empty': '还没装资料：请在充值机装资料。',
    'admin.loaded': '令牌 {token} · 装于 {time}',
    'admin.packs': '带着 {list}。',
    'admin.receipts': '待上传回执：{n}',
    'admin.receipts.none': '没有待上传的回执。',
    'admin.load': '在 {kiosk} 装资料',
    'admin.tapLabel': '刷在',
    'admin.tap': '刷参数卡',
    'admin.upload': '在 {kiosk} 上传回执',
    'admin.noKiosk': '这所学校没有充值机，所以参数卡装不了资料。',
    'admin.receipt': '{device}：{kind} v{version} {result}',
    'result.APPLIED': '已套用',
    'result.ALREADY_APPLIED': '本来就有',
    'result.REJECTED': '被拒',
    'kind.prices': '价格',
    'kind.settings': '设置',
    'kind.blocklist': '黑名单',
    'list.sep': '、',
    colon: '：',

    'tap.title': '在 {code} 上刷卡',
    'tap.where': '{type} · {location} · {school}',
    'tap.card': '卡',
    'tap.cardInfo': '卡上 {balance} · 计数 {n} · {status}',
    'tap.otherSchool': '这张卡属于 {school}。别校的机器会拒绝它：每所学校有自己的卡密钥。试试看，这就是跨校检查。',
    'tap.items': '要买什么',
    'tap.itemsNote': '来自这台机器自己的价格表（v{version}）。离线的机器可能还在用旧的。',
    'tap.less': '少一份{name}',
    'tap.more': '多一份{name}',
    'tap.qty': '{name}的数量',
    'tap.total': '合计 {amount}',
    'tap.pay': '刷卡 · 付 {amount}',
    'tap.pickItems': '请先至少选一样。',
    'tap.water': '要多少水',
    'tap.ml': '毫升',
    'tap.mlUnit': '{ml} 毫升',
    'tap.waterCost': '约 {amount}（每公升 {perLitre}，最少 {min}）。',
    'tap.waterNote': '卡上的钱不够时，机器会少倒一点。',
    'tap.pour': '刷卡 · 倒 {ml} 毫升',
    'tap.mlInvalid': '请选 1 到 20000 毫升。',
    'tap.kiosk': '充值机先读卡、把卡上最近的记录送到平台，再把等着的钱加进卡里。',
    'tap.fault': '充值机故障（可选）',
    'tap.fault.none': '没有：正常刷卡',
    'tap.go': '刷卡',
    'tap.busy': '刷卡中…',
    'tap.noCards': '还没有卡可以刷。',
    cancel: '取消',
    close: '关闭',
    working: '处理中…',

    'fault.title': '故障',
    'fault.intro': '故意制造问题，看系统怎么发现。每个问题都会出现在学校看得到的地方：拒绝代码、设备日志或对账。',
    'fault.machine': '用于故障的机器',
    'fault.card': '用于故障的卡',
    'fault.group.cards': '卡',
    'fault.group.messages': '机器和消息',
    'fault.group.kiosk': '充值机',
    'fault.group.server': '云端服务器',
    'fault.run': '试试',
    'fault.needCard': '请先选一张卡。',
    'fault.needMachine': '请先选一台机器。',
    'fault.needKiosk': '这张卡的学校没有充值机。',
    'fault.needOther': '没有别的学校可以试。',
    'fault.kioskAt': '在 {school} 的 {kiosk}，用上面选的卡。',
    'fault.target': '目标',
    'fault.target.auto': '同校的另一台机器',
    'fault.on': '刷在',
    'fault.amount': '新余额（RM）',
    'fault.amountInvalid': '请输入令吉金额，例如 100.00。',
    'fault.clone-card.title': '复制一张卡',
    'fault.clone-card.text': '把芯片逐字节复制，连安全码一起。两张都拿去消费：平台会发现两笔消费带同一个卡计数。',
    'fault.tamper-card.title': '篡改卡',
    'fault.tamper-card.text': '手动改卡上的余额。它的安全码就对不上了，所以每台机器都会拒绝它。',
    'fault.cross-school-card.title': '别校的卡',
    'fault.cross-school-card.text': '把卡刷在别校的机器上。每所学校有自己的卡密钥，所以卡会被拒绝（卡不可用）。',
    'fault.duplicate-upload.title': '同一笔记录发两次',
    'fault.duplicate-upload.text': '把机器最后一笔记录用新消息再发一次。平台回答 DUPLICATE，仍然只算一次。',
    'fault.sequence-rollback.title': '序号倒退',
    'fault.sequence-rollback.text': '发一条签名正确、但序号比平台已接受的还旧的消息，就像被重放或还原的机器。会以 SEQUENCE_ROLLBACK 被拒。',
    'fault.forged-message.title': '伪造消息',
    'fault.forged-message.text': '发一条没有用机器密钥签名的消息。会以 SIGNATURE_INVALID 被拒；学校后台的设备日志里看得到。',
    'fault.cross-device-publish.title': '发布到别台机器的主题',
    'fault.cross-device-publish.text':
      '用这台机器的登录去发布到别台机器的主题。broker 拒绝并关掉那条连接；真正的机器会被挤下线大约一秒。',
    'fault.power-cut-before-commit.title': '写卡前断电',
    'fault.power-cut-before-commit.text': '充值机在钱写进卡之前断电。什么都没写；钱继续等着。',
    'fault.power-cut-after-commit.title': '写卡后断电',
    'fault.power-cut-after-commit.text': '钱已写进卡，但平台没收到回报。下次在充值机刷卡时，它会发现这笔写入并确认。',
    'fault.confirm-timeout.title': '确认丢失',
    'fault.confirm-timeout.text': '充值机的确认超时了。它用同一个交易号查结果，绝不会把卡写两次。',
    'fault.server-down.title': '关掉云端服务器',
    'fault.server-down.text': '所有学校同时失去它：刷卡机继续离线售卖，充值机加不了钱，家长付不了款。',
    'fault.server-up.title': '重新打开',
    'fault.server-up.text': '机器自己重新连线并上传保留的记录；平台把设置重新发给每台机器。',
    'fault.broker-restart.title': '只重启 broker',
    'fault.broker-restart.text': '保留消息随之丢失；平台一重新连上就会补回去。',

    'fr.clone': '卡 {from} 已复制成 {copy}：余额一样 {balance}，计数一样 {n}，安全码有效。两张都拿去消费，再把原卡刷在充值机上。',
    'fr.tamper': '卡 {uid} 现在显示 {balance}，但安全码对不上了：每台机器都会拒绝它。',
    'fr.dup.ok': '记录 {txn} 又发了一次：平台回答 DUPLICATE，所以仍然只算一次。',
    'fr.dup.other': '记录 {txn} 又发了一次：平台回答 {status}。',
    'fr.seq.ok': '一条序号为 {seq} 的签名消息（平台已接受到 {last}）被拒：SEQUENCE_ROLLBACK。学校后台的设备日志里看得到。',
    'fr.seq.wait': '消息已发出，但平台还没回应。',
    'fr.forged.ok': '一条没有用机器密钥签名的 {type} 被拒：SIGNATURE_INVALID。学校后台的设备日志里看得到。',
    'fr.forged.other': '发出了一条伪造的 {type}；平台回答 {code}。',
    'fr.cross.ok': '用 {from} 登录并发布到 {topic}：broker 拒绝了，并关掉那条连接。没有任何东西到达平台。',
    'fr.cross.offline': '被复制的登录把真正的机器挤下线约 {s} 秒。',
    'fr.cross.login': 'broker 拒绝了 {from} 的登录：什么都没发布。',
    'fr.cross.bad': '用 {from} 发布到 {topic}：broker 没有拒绝。这绝不应该发生。',
    'fr.crossSchool.refused': '{from} 的卡刷在 {machine}：“{screen}”。这张卡对别校的机器毫无意义。',
    'fr.crossSchool.accepted': '{from} 的卡被 {machine} 接受了。这绝不应该发生。',
    'fr.server.off': '云端服务器已关掉。所有学校同时失去了它。',
    'fr.server.on': '云端服务器已打开。看机器重新连线并上传保留的记录。',
    'fr.server.same': '没有变化：云端服务器本来就{state}着。',
    'fr.broker': 'broker 已重启；平台已重新连上，并再次发布保留的设置。',
    'fr.kiosk.before': '写卡前断电：什么都没写进卡。{amount} 继续等着；不带故障再刷一次就能加进去。',
    'fr.kiosk.after': '写卡后断电：{amount} 已在卡上，但平台没收到回报。再把卡刷在充值机上：它会发现这笔写入并确认。',
    'fr.kiosk.timeout': '确认丢失了：充值机查了 {txn}，确认了 {amount}，没有把卡写第二次。',
    'fr.kiosk.nothing': '这张卡没有等着加的钱，所以没有可以“断”的。请先充值（家长网页，或在学校后台给补贴），再试一次。',
    'fr.kiosk.refused': '充值机拒绝了：“{screen}”（{reason}）。',
    'fr.kiosk.shows': '充值机显示“{screen}”。',
    'fr.kiosk.reconfirmed': '它在卡上找到之前的写入 {txn}，并向平台确认：订单现在是“已加进卡”，没有再写一次卡。',
    'state.on': '开',
    'state.off': '关',

    'clock.title': '实验室时钟',
    'clock.kl': '吉隆坡时间',
    'clock.running': '运行中',
    'clock.manual': '静止，直到拨快',
    'clock.h1': '+1 小时',
    'clock.d1': '+1 天',
    'clock.d15': '+15 天',
    'clock.jobs': '立刻执行排程工作',
    'clock.note':
      '拨快时钟会让每台在线机器发心跳，接着执行排程工作：没付款的订单会取消，超过 14 天没加进卡的钱会退款，对账会找缺漏的记录和旧黑名单。',
    'clock.jobsResult': '排程结果：取消 {cancelled} · 退款 {refunded} · 待人工处理 {parked} · 缺号 {gaps} · 旧黑名单 {lag}。',
    'clock.moved': '时钟拨快了 {by}。',
    'clock.serverOff': '服务器关着，所以排程工作没有执行。',
    'clock.jobsOff': '排程工作在云端服务器上执行：请先打开它。',
    'clock.reset': '重置演示…',
    'reset.title': '重新开始演示？',
    'reset.text': '一切回到开始：新的数据库、时钟、卡和机器。其他应用里已登录的人要重新登录。',
    'reset.confirm': '重置演示',
    'reset.done': '演示已重新开始。',
    'dur.minutes': '{n} 分钟',
    'dur.hour': '1 小时',
    'dur.hours': '{n} 小时',
    'dur.day': '1 天',
    'dur.days': '{n} 天',

    'tabs.label': '消息和控制台',
    'insp.tab': '消息',
    'insp.title': '消息检视器',
    'insp.live': '实时',
    'insp.reconnecting': '重新连线中…',
    'insp.pausedCount': '已暂停 · {n} 条新消息',
    'insp.school': '学校',
    'insp.allSchools': '所有学校',
    'insp.labOnly': '只看服务器和实验室',
    'insp.kinds': '显示',
    'kind.mqtt': 'MQTT',
    'kind.platform': '平台',
    'kind.money': '钱',
    'kind.differences': '差异',
    'kind.cards': '卡',
    'kind.lab': '机器和实验室',
    'insp.heartbeats': '心跳',
    'insp.pause': '暂停',
    'insp.resume': '继续',
    'insp.clear': '清空',
    'insp.count': '共 {total} 条，显示 {shown} 条',
    'insp.col.time': '时间',
    'insp.col.school': '学校',
    'insp.col.machine': '机器',
    'insp.col.type': '类型',
    'insp.empty': '还没有消息。在机器上刷一张卡，就会看到消息出现在这里。',
    'insp.emptyFiltered': '没有符合筛选的消息。',
    'insp.onlyHeartbeats': '目前只有心跳，而且被隐藏了：勾选“心跳”就能看到，或在机器上刷一张卡。',
    'insp.server': '实验室',

    'con.tab': '控制台',
    'con.title': '机器和服务器控制台',
    'con.hint': 'PuTTY 里也是同一个控制台：用 Telnet 连 {host} 端口 {port}。',
    'con.hintOff': 'PuTTY 里也是同一个控制台：用 Telnet 连 127.0.0.1 端口 2323（这个实验室启动时关掉了 PuTTY 控制台）。',
    'con.intro':
      '虚拟机器和虚拟云端服务器的控制台，就像登录交换机一样。输入 `machines` 列出机器，`connect smk-contoh/CANTEEN-01` 登录某台机器，`connect server` 登录云端服务器，`help`（或 `?`）看命令。↑ 和 ↓ 可以叫回之前的命令。',
    'con.command': '{prompt} 的命令',
    'con.run': '执行',
    'con.clear': '清空',
    'con.quick': '试试',
    'con.closed': '会话已结束。输入命令就能重新开始。',
    'con.failed': '% 命令执行不了：{message}',

    'err.other': '{message}（{code}）',
    'err.NETWORK': '浏览器连不上实验室服务器。它还在运行吗？',
    'err.SERVER_DOWN': '云端服务器关着：请先打开它。',
    'err.LAB_BUSY': '实验室正在布置演示，请稍后再试。',
    'err.LAB_NOT_RUNNING': '实验室没在运行。',
    'err.MACHINE_OFFLINE': '那台机器没连上 broker：请先插上网线（并打开服务器）。',
    'err.NOTHING_TO_SEND': '那台机器没有可以重发的记录：请先在它上面卖点东西。',
    'err.NOTHING_TO_ROLL_BACK': '平台还没接受过那台机器的消息：请先插上网线或发一次心跳。',
    'err.CARD_NOT_FOUND': '卡片托盘里没有这张卡。',
    'err.CARD_UID_INVALID': '这不是卡号。',
    'err.MACHINE_NOT_FOUND': '实验室里没有这台机器。',
    'err.ADMIN_CARD_NOT_FOUND': '这所学校在实验室里没有参数卡。',
    'err.WRONG_MACHINE_TYPE': '参数卡要在充值机装资料和上传回执。',
    'err.SCHOOL_NOT_FOUND': '没有这所学校。',
    'err.INPUT_INVALID': '实验室用不了送出的内容：{message}',
    'err.FAULT_INVALID': '这个故障在这里不适用：{message}',
    'err.CROSS_ORIGIN': '服务器拒绝了不是从本页发出的请求。请重新载入页面再试。',
    'err.INTERNAL': '实验室服务器出错了。请看运行实验室的终端。',

    'reason.BLOCKED': '卡在黑名单上',
    'reason.CARD_UNREADABLE': '卡的安全码对不上（被手动改过）',
    'reason.WRONG_SCHOOL': '卡属于别的学校',
    'reason.NO_BLOCKLIST': '机器从没收到黑名单',
    'reason.NOT_READY': '机器还没有价格或设置',
    'reason.JOURNAL_FULL': '机器的流水满了',
    'reason.ITEMS_INVALID': '点的东西不对',
    'reason.UNKNOWN_ITEM': '有一样不在这台机器的价格表上',
    'reason.AMOUNT_INVALID': '没选要多少水',
    'reason.CLOSED': '现在不是用餐时间',
    'reason.GROUP_NOT_ALLOWED': '这里不收这类持卡人',
    'reason.PER_PURCHASE_LIMIT': '超过每笔上限',
    'reason.DAILY_LIMIT': '超过每日上限',
    'reason.DAILY_COUNT': '今天消费次数太多',
    'reason.TAP_GAP': '同一张卡刷得太快',
    'reason.INSUFFICIENT_BALANCE': '卡上的钱不够',
    'reason.OFFLINE': '充值机没连上 broker',
    'reason.PLATFORM_UNREACHABLE': '平台没回应充值机',
    'reason.CARD_NOT_ACTIVE': '平台说这张卡已挂失或已更换',
    'reason.CARD_NOT_FOUND': '平台不认识这张卡',
    'reason.POWER_CUT': '写卡时断电',
    'reason.PACKS_INVALID': '资料装不进参数卡',

    'ev.someone': '某个客户端',
    'ev.platform': '平台',
    'ev.viewer': '只读查看者',
    'ev.retained': '保留消息',
    'ev.bytes': '{n} 字节',
    'ev.mqtt.connect': '{who} 登录了 broker',
    'ev.mqtt.disconnect': '{who} 离开了 broker',
    'ev.mqtt.denied': 'broker 拒绝了 {who} 的{action}',
    'ev.mqtt.denied.topic': 'broker 拒绝了 {who} 在 {topic} 的{action}',
    'ev.action.connect': '登录',
    'ev.action.publish': '发布',
    'ev.action.subscribe': '订阅',
    'ev.mqtt.up': '机器 → broker：{type}，主题 {topic}',
    'ev.mqtt.down': '平台 → 机器：{type}，主题 {topic}',
    'ev.mqtt.other': '{from} → broker：{type}，主题 {topic}',
    'ev.intake.accepted': '平台接受了 {type}',
    'ev.intake.duplicate': '平台已经收过这条 {type}：忽略，只算一次',
    'ev.intake.refused': '平台拒绝了 {type}：{code}（{why}）',
    'ev.records': '{n} 条记录（{list}）',
    'ev.purchase': '{txn}：{amount} {status}，经由 {via}',
    'ev.purchase.diffs': ' · 差异：{list}',
    'ev.ledger': '{kind} {amount}：{lines}',
    'ev.dr': '借',
    'ev.cr': '贷',
    'ev.topup.status': '{kind} {amount}：{status}',
    'ev.topup.refunded': '{kind} {amount} 已退还给家长（模拟银行）',
    'ev.topup.returned': '{kind} {amount} 没按时加进卡：退回给学校',
    'ev.config': '新的{kind}：版本 {version}',
    'ev.card.issued': '已发卡 {uid}',
    'ev.card.lost': '卡 {uid} 已挂失 · 黑名单 v{version}',
    'ev.card.found': '卡 {uid} 已找回 · 黑名单 v{version}',
    'ev.card.debit': '卡 {uid}：−{amount} → {balance}',
    'ev.card.credit': '卡 {uid}：+{amount} → {balance}',
    'ev.screen': '屏幕：{text}',
    'ev.cable.in': '网线已插上',
    'ev.cable.out': '网线已拔掉',
    'ev.admin.loaded': '参数卡已装好 · 令牌 {token} · {packs}',
    'ev.admin.applied': '读了参数卡：套用 {applied}，本来就有 {already}，被拒 {rejected}',
    'ev.diff.opened': '差异：{kind}',
    'ev.diff.resolved': '已解决：{kind}',
    'ev.audit': '{actor}：{action}',
    'ev.lab.tap': '你在 {device} 上刷了 {uid}：“{screen}”',
    'ev.lab.tapFault': ' · 故障：{fault}',
    'ev.lab.tapOther': ' · {school} 的卡',
    'ev.lab.usb': '你把 {device} 的流水导出到 USB：{count} 条记录',
    'ev.lab.reboot': '你重启了 {device}',
    'ev.lab.jobs': '排程已执行：取消 {cancelled} · 退款 {refunded} · 待人工 {parked} · 缺号 {gaps} · 旧黑名单 {lag}',
    'ev.lab.serverUp': '你打开了云端服务器',
    'ev.lab.serverDown': '你关掉了云端服务器',
    'ev.lab.same': '（本来就是）',
    'ev.lab.brokerRestart': '你重启了 broker',
    'ev.lab.reset': '演示重新开始了',
    'ev.lab.fault': '故障：{name}',
    'ev.lab.clock': '时钟拨快 {by} → {kl}',
    'ev.tenant': '平台上的新学校：{name}（{code}）',
    'ev.school.status': '{code}：{from} → {status}',
    'ev.device.registered': '新机器 {code}（{type}）',
    'ev.server.up': '云端服务器已打开',
    'ev.server.down': '云端服务器已关掉',
    'ev.broker.up': 'broker 运行于 {url}',
    'ev.broker.down': 'broker 已停止（{reason}）',

    'evx.mqtt.connect': '有人登录了 MQTT broker：机器、平台，或 MQTT Explorer 之类的查看者。',
    'evx.mqtt.disconnect': '一条和 MQTT broker 的连接结束了：拔了网线、关了服务器、重启 broker 或被踢掉。',
    'evx.mqtt.denied': 'broker 拒绝了该账号无权做的登录、发布或订阅。',
    'evx.mqtt.publish': '一条消息经过了 broker：记录和状态从机器往上送；价格、设置、黑名单和指令从平台往下发。',
    'evx.intake.accepted': '平台检查了这条消息（主题、签名、序号、学校和机器）并接受了它。',
    'evx.intake.duplicate': '平台已经收过这条一模一样的消息。它被忽略，所以不会重复计算。',
    'evx.intake.refused': '平台拒绝了这条消息。代码说明原因，学校后台的设备日志里也看得到。',
    'evx.purchase.received': '一笔消费记录到了平台：入账、被标记、重复或被拒。',
    'evx.ledger.posting': '学校账本里的一笔复式记账：借方总是等于贷方。',
    'evx.topup.status': '一笔充值、补贴或余额转移订单的状态变了。',
    'evx.topup.refunded': '没加进卡的钱被退回：家长的充值退给家长（通过模拟银行），补贴退回学校。',
    'evx.config.published': '学校发布了新的价格表、设置或黑名单。有网络的机器马上收到。',
    'evx.card.issued': '学校发了一张卡；实验室做出了这张虚拟卡（余额 RM 0.00）。',
    'evx.card.lost': '一张卡被挂失，并加进了黑名单。',
    'evx.card.found': '一张挂失的卡找回了，并从黑名单移除。',
    'evx.card.write': '机器写了卡的芯片：刷卡机或饮水机扣款，充值机加钱。',
    'evx.device.screen': '机器屏幕现在显示的内容。',
    'evx.device.cable': '机器的网线被插上或拔掉。',
    'evx.admin-card.loaded': '充值机把最新的资料和新令牌装进了参数卡。',
    'evx.admin-card.applied': '机器读了参数卡，并为每份资料写了回执。',
    'evx.difference.opened': '对账发现了需要学校后台人员查看的问题。',
    'evx.difference.resolved': '学校后台人员写了备注，解决了一个差异。',
    'evx.audit': '在学校后台或由运营方做的操作，记在审计记录里。',
    'evx.lab.action': '你在实验室里做的事：刷卡、故障、开关服务器。',
    'evx.lab.clock': '实验室时钟拨快了。',
    'evx.tenant.created': '运营方开通了一所新学校。它的机器、卡和参数卡出现在实验室里。',
    'evx.school.status': '运营方停用或恢复了一所学校。',
    'evx.device.registered': '登记了一台新机器；实验室把它装好。',
    'evx.server.status': '虚拟云端服务器被打开或关掉。',
    'evx.broker.status': 'MQTT broker 启动或停止了。',
    'evx.other': '实验室事件。',

    'refusal.TOPIC_INVALID': '不是设备主题',
    'refusal.UNKNOWN_DEVICE': '没有这个学校或机器',
    'refusal.ENVELOPE_INVALID': '消息格式不对',
    'refusal.VERSION_UNSUPPORTED': '不支持的协议版本',
    'refusal.UNKNOWN_TYPE': '未知的消息类型',
    'refusal.TOPIC_MISMATCH': '学校、机器或频道和主题对不上',
    'refusal.SIGNATURE_INVALID': '签名对不上',
    'refusal.SEQUENCE_ROLLBACK': '序号倒退了',
    'refusal.SCHOOL_SUSPENDED': '学校已停用',
    'refusal.DEVICE_DISABLED': '机器已被关掉',
    'refusal.WRONG_DEVICE_TYPE': '这种机器不能发这种消息',
    'refusal.COUNT_MISMATCH': '批次数量对不上',
    'refusal.RECORD_INVALID': '记录格式不对',
    'refusal.UNKNOWN_ORIGIN_DEVICE': '记录里的机器学校没有',
    'refusal.INTERNAL': '平台内部错误',
    'refusal.other': '见设备日志',

    'diff.MISSING_RECORDS': '平台没收到的消费（机器流水号有缺口）',
    'diff.DUPLICATE_CONFLICT': '同一流水号上传了两次，内容不同',
    'diff.UNKNOWN_CARD': '本校不认识的卡的消费',
    'diff.PRICE_VERSION_UNKNOWN': '记录里的价格版本平台没发过',
    'diff.PRICE_MISMATCH': '金额和机器所用价格版本对不上',
    'diff.BALANCE_CONTINUITY': '扣前余额减金额不等于扣后余额',
    'diff.BALANCE_MISMATCH': '卡上余额和平台镜像余额对不上',
    'diff.MIRROR_NEGATIVE': '镜像余额变成负数',
    'diff.SPENT_AFTER_LOST_REPORT': '挂失后卡还被使用',
    'diff.CARD_CLONE_SUSPECTED': '两笔不同消费带同一个卡计数（可能是复制卡）',
    'diff.OLD_BLOCK_LIST': '机器还在用旧的黑名单',
    'diff.TOPUP_ADDED_AFTER_REFUND': '充值机回报已加的钱其实已退款',
    'diff.DOUBLE_ADD_SUSPECTED': '同一笔充值被另一次写卡回报已加',

    'acct.CASH_RECEIVED': '已收现金',
    'acct.STUDENT_WALLET': '学生钱包',
    'acct.WAITING_TO_BE_ADDED': '等待加值',
    'acct.SCHOOL_SUBSIDY': '学校补贴',
    'acct.SALES_PAYABLE': '应付销售款',

    'order.TOPUP': '充值',
    'order.SUBSIDY': '补贴',
    'order.TRANSFER': '余额转移',
    'topup.CREATED': '已建立，等付款',
    'topup.PAID': '已付款，等在充值机加进卡',
    'topup.ADDED': '已加进卡',
    'topup.CANCELLED': '已取消（没按时付款）',
    'topup.FAILED': '付款失败',
    'topup.EXPIRED': '已过期',
    'topup.REFUNDED': '已退款',
    'topup.PARKED': '待人工处理',
    'purchase.POSTED': '已入账',
    'purchase.FLAGGED': '已标记',
    'purchase.DUPLICATE': '重复',
    'purchase.REFUSED': '被拒',
    'via.MQTT': 'MQTT',
    'via.JOURNAL_BATCH': '流水批次',
    'via.KIOSK_READBACK': '充值机回读',
    'via.USB_IMPORT': 'USB 导入',

    // captions under a machine screen (the machine itself shows English)
    'scr.paid': '已付 {a} · 余额 {b}',
    'scr.poured': '已倒 {ml} 毫升 · 已付 {a} · 余额 {b}',
    'scr.pouredPart': '已倒 {ml}/{req} 毫升 · 已付 {a} · 余额 {b}',
    'scr.added': '已加 {a} · 余额 {b}',
    'scr.nothing': '没有要加的钱 · 余额 {b}',
    'scr.unavailable': '卡不可用，请联系柜台',
    'scr.closed': '现在不营业',
    'scr.notEnough': '余额不足 · 余额 {b}',
    'scr.wait': '请等 {n} 秒再刷',
    'scr.dailyAmount': '已达每日上限 {a}',
    'scr.dailyCount': '已达每日 {n} 笔上限',
    'scr.perPurchase': '超过每笔上限 {a}',
    'scr.groupStudent': '这里不收学生卡',
    'scr.groupStaff': '这里不收教职员卡',
    'scr.notReady': '机器还没准备好，请联系柜台',
    'scr.memoryFull': '机器记忆体已满，请接上网络',
    'scr.noPlatform': '连不上平台，请稍后再来',
    'scr.powerCut': '加钱时断电，请再刷一次',
    'scr.adminLoaded': '参数卡已装好 · 令牌 {n} · {k} 份资料',
    'scr.adminUploaded': '参数卡回执已上传 · {n}',
    'scr.adminNone': '参数卡上没有回执',
    'scr.adminRead': '已读参数卡：套用 {a}，本来就有 {b}，被拒 {c}',
    'scr.adminBad': '参数卡装不上',
    'scr.starting': '启动中…',
    'scr.ready': '就绪',
    'scr.unknownItem': '没有这一样：{x}',
    'scr.chooseItems': '请选 1 到 {n} 样',
    'scr.qty': '数量必须是 1 到 {n}',
    'scr.chooseWater': '请选要倒多少水',
  },
};
