// Every string the school office shows, in English and Chinese (中文). Plain words: the people
// using this are school office staff, not engineers.

const en = {
  // ---- shell
  'app.skip': 'Skip to content',
  'app.home': 'OneCard Lab home',
  'app.name': 'School office',
  'app.ribbon': 'LAB · not real money',
  'app.yourSchool': 'Your school on the OneCard platform',
  'app.onlyYours': 'You see this school only. Other schools on the platform are invisible here.',
  'app.signOut': 'Sign out',
  'app.sections': 'Sections',
  'app.waiting': 'Waiting for the OneCard server…',

  'signin.title': 'School office: sign in',
  'signin.lede': 'Lab only: there are no passwords. Pick who you are.',
  'signin.tenants': 'Each school is a separate tenant on the OneCard platform. Staff only ever see their own school.',
  'signin.none': 'No school has staff yet. Onboard a school in the operator console first.',
  'signin.ended': 'Your session ended (the lab may have restarted). Sign in again.',
  'signin.suspended': '{school} is suspended on the OneCard platform, so its staff cannot sign in. The platform operator can reactivate it in the operator console.',

  'school.ACTIVE': 'Active',
  'school.SUSPENDED': 'Suspended',

  'role.OFFICE': 'Office',
  'role.FINANCE': 'Finance',
  'role.ADMIN': 'Admin',
  'roleText.OFFICE': 'Students, cards, parents, machines and prices',
  'roleText.FINANCE': 'Top-ups, subsidies, the books and reconciliation',
  'roleText.ADMIN': 'Everything in the school',

  'susp.short': 'School suspended',
  'susp.title': '{school} is suspended',
  'susp.titleUnknown': 'Your school is suspended',
  'susp.text':
    "The OneCard platform operator has suspended this school. While it is suspended, the school office, the school's machines and its parents cannot use OneCard. Nothing has been deleted.",
  'susp.ask': 'Ask the platform operator to reactivate the school. This page checks again every few seconds.',
  'susp.lab': 'In the lab you are the operator too:',
  'susp.operatorLink': 'open the operator console',
  'susp.check': 'Check again',
  'susp.still': 'Still suspended.',

  'nav.overview': 'Overview',
  'nav.students': 'Students & cards',
  'nav.cards': 'All cards',
  'nav.parents': 'Parents',
  'nav.machines': 'Machines',
  'nav.prices': 'Prices & settings',
  'nav.topups': 'Top-ups',
  'nav.books': 'Books',
  'nav.reconciliation': 'Reconciliation',
  'nav.audit': 'Audit log',
  'badge.reconciliation': '{n} open differences',
  'badge.topups': '{n} parked top-ups',
  'badge.parents': '{n} link requests waiting',

  // ---- overview
  'ov.lede': 'Today at {school} at a glance. Each box leads to the section that deals with it.',
  'ov.today': 'Today on the lab clock: {day}',
  'ov.sales': 'Sales today',
  'ov.salesSub': '{n} purchases at the canteen and water machines',
  'ov.machines': 'Machines online',
  'ov.machinesValue': '{online} of {total}',
  'ov.machinesOff': '{n} not online right now (no heartbeat in the last 90 seconds)',
  'ov.machinesAll': 'All machines are online',
  'ov.waiting': 'Money waiting at the kiosk',
  'ov.waitingSub': 'Paid or granted, not on the cards yet',
  'ov.differences': 'Open differences',
  'ov.differencesSub': 'Need a person to check them',
  'ov.differencesFinance': 'Finance staff check these',
  'ov.differencesNone': 'Nothing to check',
  'ov.parked': 'Parked top-ups',
  'ov.parkedSub': 'Need a decision: on the card, or refund',
  'ov.parkedFinance': 'Finance staff decide on these',
  'ov.parkedNone': 'Nothing waiting for a decision',
  'ov.links': 'Parents waiting for approval',
  'ov.linksSub': 'Link requests to approve or reject',
  'ov.linksNone': 'No requests waiting',
  'ov.tasks': 'Everyday jobs',
  'ov.task.lost': 'A card was lost: find the student and report the card lost',
  'ov.task.links': 'Approve a parent who linked to a child',
  'ov.task.prices': 'Change canteen prices or the water price',
  'ov.task.machines': 'Check that the machines are online and up to date',
  'ov.task.usb': "Import a machine's journal from a USB stick",
  'ov.task.parked': 'Decide on parked top-ups',
  'ov.task.subsidy': 'Grant a subsidy to a student',
  'ov.task.books': 'Check that the books balance',
  'ov.task.differences': 'Check and resolve differences',
  'ov.task.audit': 'See who did what (audit log)',
  'ov.tenantTitle': 'One school on a shared platform',
  'ov.tenantText':
    "{school} ({code}) is one tenant of the OneCard platform, which serves many schools from one server. Everything in this office belongs to {school} only: other schools' students, machines and money never appear here, even if you type an address by hand.",

  // ---- students and cards
  'st.lede': 'Everyone in the school who has a card: students and staff. Click a name to see balances, cards and history.',
  'st.add': 'Add a student or staff member',
  'st.lists': 'Lists',
  'st.tabStudents': 'Students and staff',
  'st.tabCards': 'All cards',
  'st.search': 'Search',
  'st.searchHint': 'Name, number, class or last 4 of the card',
  'st.count': '{shown} of {total} shown',
  'st.no': 'Number',
  'st.name': 'Name',
  'st.fullName': 'Full name',
  'st.class': 'Class',
  'st.group': 'Group',
  'st.card': 'Card',
  'st.balance': 'On the platform',
  'st.waiting': 'Waiting at the kiosk',
  'st.noCard': 'No card',
  'st.noMatch': 'Nobody matches the search.',
  'st.empty': 'No students or staff yet.',
  'st.addTitle': 'Add a student or staff member',
  'st.addBody': 'They appear in this school only. You can give them a card now or later.',
  'st.noHint': "The school's own number, e.g. S1007",
  'st.classHint': 'Optional, e.g. 4 Bestari',
  'st.cardUid': 'Card UID (optional)',
  'st.cardUidHint': 'The number printed on or read from the card: 8 to 20 hex characters, e.g. 04A1B2C3D4E5F6. Leave it empty to issue a card later.',
  'st.addConfirm': 'Add',
  'st.added': '{name} was added.',
  'st.addedWithCard': '{name} was added with card {card}. The card starts with RM 0.00.',
  'group.STUDENT': 'Student',
  'group.STAFF': 'Staff',
  'memberStatus.ACTIVE': 'Active',
  'memberStatus.LEFT': 'Has left the school',

  'cards.lede': 'Every card this school has issued, including lost and replaced ones. Someone handed in a card? Search for its last 4 characters.',
  'cards.card': 'Card',
  'cards.holder': 'Holder',
  'cards.status': 'Status',
  'cards.issued': 'Issued',
  'cards.lostAt': 'Reported lost',
  'cards.listVersion': 'Block list',
  'cards.actions': 'Action',
  'cards.count': '{shown} of {total} cards shown',
  'cards.empty': 'No cards issued yet.',
  'cardStatus.ACTIVE': 'Active',
  'cardStatus.LOST': 'Lost',
  'cardStatus.RETIRED': 'Retired',

  'card.uidInvalid': 'A card UID is 8 to 20 hex characters (0–9 and A–F), an even number of them, e.g. 04A1B2C3D4E5F6.',
  'card.uid': 'Card UID',
  'card.newUid': 'New card UID',
  'card.uidHint': 'From the card: 8 to 20 hex characters, e.g. 04A1B2C3D4E5F6 (spaces and colons are fine)',
  'card.sent': 'The new block list was sent to the machines.',
  'card.notSent': 'The new block list is saved but not sent yet: the platform cannot reach the message broker. It goes out by itself when the connection is back.',
  'card.seeMachines': 'See which machines have it',
  'card.lostButton': 'Report lost',
  'card.lostTitle': 'Report card {card} lost?',
  'card.lostBody':
    'The card of {name} goes on the school’s block list. Machines that get the new list refuse it. The money on it stays in the books and can move to a replacement card.',
  'card.lostWindow': 'Machines with no network keep accepting the card until they get the new list (when their cable is plugged in, or the admin card visits them).',
  'card.lostConfirm': 'Report lost',
  'card.lostDone': 'Card {card} is reported lost (block list version {version}).',
  'card.foundButton': 'Mark found',
  'card.foundOne': 'Card {card} was found',
  'card.foundTitle': 'Mark card {card} as found?',
  'card.foundBody': 'The card of {name} comes off the block list and works again once the machines get the new list. This is only possible if no replacement card was issued.',
  'card.foundConfirm': 'Mark as found',
  'card.foundDone': 'Card {card} works again.',
  'card.replaceButton': 'Replace card',
  'card.replaceTitle': 'Replace the card of {name}',
  'card.replaceOld': 'The current card {card} is reported lost first, so it stops working.',
  'card.replaceNoOld': 'There is no active card, so nothing needs to be reported lost.',
  'card.replaceMoney': 'The balance on the platform, {amount}, moves to the new card: it waits at the top-up kiosk until the new card is tapped there.',
  'card.replaceConfirm': 'Replace card',
  'card.replaceDone': 'New card {card} issued to {name}.',
  'card.replaceOldDone': 'The old card {card} is reported lost.',
  'card.replaceTransfer': '{amount} waits at the top-up kiosk for the new card: tap the new card there.',
  'card.replaceNoTransfer': 'There was no money to move.',
  'card.issueButton': 'Issue a card',
  'card.issueTitle': 'Issue a card to {name}',
  'card.issueBody': 'A new card starts with RM 0.00. Money is added at the top-up kiosk.',
  'card.issueConfirm': 'Issue card',
  'card.issueDone': 'Card {card} issued to {name}.',

  // ---- one student
  'mem.back': '← All students and staff',
  'mem.title': 'Student',
  'mem.notFoundTitle': 'Not found',
  'mem.notFound': 'There is no such student or staff member in {school}. People of other schools are never shown here.',
  'mem.noClass': 'no class',
  'mem.balances': 'Balances',
  'mem.platformBalance': 'Balance on the platform',
  'mem.platformSub': "The platform's copy of the money on the card",
  'mem.waiting': 'Waiting at the kiosk',
  'mem.waitingSub': 'Paid or granted; added when the card is tapped at the top-up kiosk',
  'mem.neverAdded': 'These two amounts are never added together: the waiting money is not on the card yet.',
  'mem.subsidy': 'Grant a subsidy',
  'mem.card': 'Card',
  'mem.onlyLost': 'No active card: the last one was reported lost.',
  'mem.noCard': 'No card yet.',
  'mem.issued': 'Issued {at}',
  'mem.cardsByOffice': 'Cards are handled by office staff.',
  'mem.parents': 'Parents',
  'mem.noParents': 'No parent has linked to this child yet.',
  'mem.invite': 'Create an invitation code',
  'mem.allParents': 'All parent requests',
  'mem.waitingOrders': 'Waiting at the kiosk',
  'mem.waitingOrdersText': 'Each of these is added to the card the next time it is tapped at the top-up kiosk.',
  'mem.noWaiting': 'Nothing is waiting.',
  'mem.purchases': 'Purchases',
  'mem.orders': 'Top-ups and subsidies',
  'mem.cards': 'Cards',
  'mem.noCards': 'No cards.',

  'sub.title': 'Grant a subsidy to {name}',
  'sub.body':
    "The school pays this amount. It waits at the top-up kiosk and is added the next time the card is tapped there. If it is not added within the school's add window, it goes back to the school.",
  'sub.amount': 'Amount (RM)',
  'sub.note': 'Note (optional)',
  'sub.notePlaceholder': 'e.g. Food aid, term 3',
  'sub.confirm': 'Grant subsidy',
  'sub.done': 'Subsidy of {amount} granted to {name}. It waits at the top-up kiosk until {at}.',

  'inv.title': "Invitation code for {name}'s parent",
  'inv.body': 'The parent types this code in the parent app (Link a child). You then approve the request here before they can see the child.',
  'inv.confirm': 'Create code',
  'inv.done': "Invitation code for {name}'s parent:",
  'inv.next': 'Give the code to the parent. When they use it, their request appears under Parents for you to approve.',

  // ---- parents
  'par.lede': 'Parents link to a child with an invitation code from the school. Each request needs your approval before the parent can see the child or top up.',
  'par.newInvite': 'Create an invitation code',
  'par.newInviteTitle': 'Create an invitation code',
  'par.pickChild': 'Choose a student',
  'par.child': 'Child',
  'par.pending': 'Waiting for your decision',
  'par.pendingText': "Check that each person really is the child's parent or guardian before you approve.",
  'par.noPending': 'No requests are waiting.',
  'par.invites': 'Invitation codes',
  'par.invitesText': 'A code can be used once, by one parent.',
  'par.noInvites': 'No invitation codes yet.',
  'par.decided': 'Decided requests',
  'par.noDecided': 'Nothing decided yet.',
  'par.parent': 'Parent',
  'par.email': 'Email',
  'par.status': 'Status',
  'par.requested': 'Requested',
  'par.decision': 'Decision',
  'par.code': 'Code',
  'par.created': 'Created',
  'par.used': 'Used',
  'par.approve': 'Approve',
  'par.reject': 'Reject',
  'par.approveTitle': 'Approve {parent} for {child}?',
  'par.approveBody':
    "Check that {parent} ({email}) really is a parent or guardian of {child}. Once approved, they see the child's balance and history and can top up the card.",
  'par.rejectTitle': 'Reject the request of {parent}?',
  'par.rejectBody': '{parent} will not be linked to {child}. They can ask again with a new invitation code.',
  'par.approved': '{parent} is now linked to {child}.',
  'par.rejected': 'The request of {parent} was rejected.',
  'linkStatus.PENDING': 'Waiting',
  'linkStatus.APPROVED': 'Approved',
  'linkStatus.REJECTED': 'Rejected',
  'inviteStatus.OPEN': 'Not used yet',
  'inviteStatus.USED': 'Used',
  'inviteStatus.REVOKED': 'Withdrawn',

  // ---- machines
  'mac.lede': "The school's canteen readers, water machines and top-up kiosk. A machine is online when it sent a heartbeat in the last 90 seconds.",
  'mac.register': 'Register a machine',
  'mac.list': 'Machines',
  'mac.versions': 'What each machine has',
  'mac.versionsText':
    'The price list, settings and block list each machine has confirmed. A machine that is behind still uses an older version: it updates when it is online, or when the admin card visits it.',
  'mac.log': 'Device log',
  'mac.logText': 'Messages the platform refused or found odd, newest first.',
  'mac.logFilter': 'Machine',
  'mac.logAll': 'All machines',
  'mac.logAt': 'Time',
  'mac.logLevel': 'Level',
  'mac.logWhat': 'What happened',
  'mac.logEmpty': 'Nothing in the log.',
  'mac.machine': 'Machine',
  'mac.location': 'Location',
  'mac.switched': 'Status',
  'mac.connection': 'Connection',
  'mac.heartbeat': 'Last heartbeat',
  'mac.software': 'Software',
  'mac.change': 'Change',
  'mac.changeButton': 'On / off…',
  'mac.online': 'Online',
  'mac.offline': 'Offline',
  'mac.empty': 'No machines yet.',
  'mac.verNone': 'none',
  'mac.behind': 'behind: v{v} is out',
  'mac.upToDate': 'up to date',
  'mac.statusTitle': 'Switch {code} on or off',
  'mac.statusBody':
    'A machine that is off or in maintenance is disconnected from the server at once and cannot connect again until it is switched on. When it is switched on, it gets the current prices, settings and block list.',
  'mac.statusNow': 'Now: {status}',
  'mac.statusLabel': 'Status',
  'mac.statusConfirm': 'Save',
  'mac.statusOn': '{code} is on. It got the current prices, settings and block list.',
  'mac.statusOnNotSent': '{code} is on, but the current settings could not be sent yet (the platform cannot reach the message broker).',
  'mac.statusOff': '{code} is now {status}. Connections closed: {n}.',
  'mac.registerTitle': 'Register a machine',
  'mac.registerBody': 'A new machine for this school. You see its secret once: the machine needs it to sign its messages.',
  'mac.code': 'Machine code',
  'mac.codeHint': 'Capital letters, digits and dashes, e.g. CANTEEN-03',
  'mac.codeInvalid': 'Use capital letters, digits and dashes (up to 32), starting and ending with a letter or digit.',
  'mac.type': 'Type',
  'mac.locationHint': 'e.g. Canteen counter C',
  'mac.registerConfirm': 'Register',
  'mac.registered': '{code} ({type}) is registered.',
  'mac.registeredSent': 'The current prices, settings and block list were sent to it.',
  'mac.registeredNotSent': 'It gets the current prices, settings and block list when it first connects.',
  'devType.CANTEEN': 'Canteen reader',
  'devType.WATER': 'Water machine',
  'devType.KIOSK': 'Top-up kiosk',
  'devStatus.ACTIVE': 'On',
  'devStatus.DISABLED': 'Off',
  'devStatus.MAINTENANCE': 'Maintenance',
  'devStatusLong.ACTIVE': 'On: working normally',
  'devStatusLong.MAINTENANCE': 'Maintenance: off for repair',
  'devStatusLong.DISABLED': 'Off: switched off',
  'stateVia.MQTT': 'over the network',
  'stateVia.HEARTBEAT': 'reported in a heartbeat',
  'stateVia.PROVISION': 'set at install',
  'stateVia.ADMIN_CARD': 'by admin card',
  'kind.prices': 'Price list',
  'kind.settings': 'Settings',
  'kind.blocklist': 'Block list',
  'level.INFO': 'Info',
  'level.WARN': 'Warning',
  'level.ERROR': 'Error',
  'log.SIGNATURE_INVALID': "Refused: the message was not signed with this machine's secret (forged or damaged).",
  'log.SEQUENCE_ROLLBACK': 'Refused: an old message number came again (replayed or rolled back).',
  'log.SCHOOL_SUSPENDED': 'Refused: the school is suspended.',
  'log.DEVICE_DISABLED': 'Refused: the machine is switched off.',
  'log.WRONG_DEVICE_TYPE': 'Refused: this kind of machine may not send that message.',
  'log.ENVELOPE_INVALID': 'Refused: the message was malformed.',
  'log.TOPIC_MISMATCH': 'Refused: the message did not match the topic it was sent on.',
  'log.RECORD_INVALID': 'Refused: a purchase record was malformed.',
  'log.COUNT_MISMATCH': 'Refused: a catch-up upload did not hold the number of records it said.',
  'log.UNKNOWN_ORIGIN_DEVICE': 'Refused: a record names a machine this school does not have.',
  'log.REPLAY': 'Refused: the kiosk request was already received (replayed).',
  'log.VERSION_UNSUPPORTED': 'Refused: the machine uses a protocol version the platform does not support.',
  'log.UNKNOWN_TYPE': 'Refused: unknown message type.',
  'log.ADMIN_CARD_REJECTED': 'The machine refused the admin card.',
  'log.COMMAND_REJECTED': 'The machine refused a command from the platform.',

  // ---- prices and settings
  'pr.lede':
    'What the machines charge and when they sell. Publishing makes a new version: networked machines get it within seconds, the others when they reconnect or the admin card visits them.',
  'pr.refreshSide': 'Refresh machine versions',
  'pr.reached': 'Has it reached the machines?',
  'pr.reachedText': 'Each machine confirms the version it holds. Machines with no network stay behind until they connect or the admin card visits them.',
  'pr.blocklist': 'Block list',
  'pr.blocklistText':
    'Cards on this list are refused by every machine that has this version. The list carries a keyed card reference and the last 4 characters only, never the full card number.',
  'pr.blockVersion': 'Version {v}',
  'pr.since': 'since {at}',
  'pr.blockEmpty': 'No cards are blocked.',
  'pr.history': 'Version history',
  'pr.histWhat': 'What',
  'pr.histVersion': 'Version',
  'pr.histCreated': 'Published',
  'pr.histFrom': 'Effective from',
  'pr.histEmpty': 'No versions yet.',
  'pr.version': 'Version {v}',
  'pr.inUse': 'Published {at}',
  'pr.noneYet': 'Nothing published yet.',
  'pr.items': 'Canteen items',
  'pr.code': 'Code',
  'pr.itemName': 'Name',
  'pr.price': 'Price',
  'pr.remove': 'Remove',
  'pr.removeItem': 'Remove {name}',
  'pr.addItem': 'Add an item',
  'pr.codeHint': 'Codes: capital letters, digits and dashes, e.g. NASI-LEMAK. Machines and receipts use the code.',
  'pr.water': 'Water',
  'pr.perLitre': 'Price per litre (RM)',
  'pr.perLitreHint': 'Charged by the millilitre and rounded: 650 ml at RM 0.20 a litre is RM 0.13.',
  'pr.minCharge': 'Minimum charge (RM)',
  'pr.minChargeHint': 'The least one pour costs.',
  'pr.publish': 'Publish price list',
  'pr.undo': 'Undo my changes',
  'pr.fixFirst': 'Fix the marked fields first.',
  'pr.nothing': 'Nothing changed: this is the same as version {v}.',
  'pr.confirmTitle': 'Publish price list version {v}?',
  'pr.confirmText':
    'Networked machines switch within seconds. Machines with no network keep the old prices until they connect or the admin card visits them. Every sale records the price version it used.',
  'pr.raced': 'Someone published version {v} while you were editing. Publishing replaces it with what you see here.',
  'pr.published': '{what} version {v} is published.',
  'pr.sent': 'Sent to the machines; networked ones confirm within seconds (see below).',
  'pr.notSent': 'Saved, but not sent yet: the platform cannot reach the message broker. It goes out by itself when the connection is back.',
  'pr.chAdded': 'New item: {name}, {price}',
  'pr.chPrice': '{name}: {from} → {to}',
  'pr.chName': 'Name: {from} → {to}',
  'pr.chRemoved': 'Removed: {name}',
  'pr.chLitre': 'Water per litre: {from} → {to}',
  'pr.chMin': 'Minimum water charge: {from} → {to}',
  'pr.err.code': 'Use capital letters, digits and dashes (1 to 24).',
  'pr.err.codeTwice': 'Two items have this code.',
  'pr.err.name': 'Give the item a name (up to 40 characters).',
  'pr.err.price': 'Enter a price from RM 0.01 to RM 1,000.00.',
  'pr.err.items': 'The price list needs 1 to 50 items.',
  'pr.err.perLitre': 'Enter RM 0.01 to RM 100.00.',
  'pr.err.minCharge': 'Enter RM 0.00 to RM 100.00.',

  'se.addWindow': 'Add a time window',
  'se.removeWindow': 'Remove this time window',
  'se.from': 'From',
  'se.to': 'To',
  'se.windows': 'When the canteen and water machines sell',
  'se.windowsText': 'Kuala Lumpur time. With no time windows, machines sell at any time. At most 6.',
  'se.anyTime': 'any time',
  'se.groups': 'Who may buy',
  'se.limits': 'Limits per card',
  'se.perPurchase': 'Most per purchase (RM)',
  'se.daily': 'Most per day (RM)',
  'se.count': 'Most purchases per day',
  'se.gap': 'Seconds between two taps',
  'se.inRM': 'In ringgit, e.g. 20.00',
  'se.countHint': '1 to 100',
  'se.gapHint': 'Stops a double tap from charging twice. 0 to 600.',
  'se.publish': 'Publish settings',
  'se.nothing': 'Nothing changed: these are the same as version {v}.',
  'se.confirmTitle': 'Publish settings version {v}?',
  'se.confirmText': 'Networked machines switch within seconds; machines with no network keep the old settings until they connect or the admin card visits them.',
  'se.chWindows': 'Selling times: {from} → {to}',
  'se.chGroups': 'Who may buy: {from} → {to}',
  'se.chPerPurchase': 'Most per purchase: {from} → {to}',
  'se.chDaily': 'Most per day: {from} → {to}',
  'se.chCount': 'Most purchases per day: {from} → {to}',
  'se.chGap': 'Seconds between two taps: {from} → {to}',
  'se.err.time': 'Enter a time, e.g. 06:30.',
  'se.err.order': 'The end must be after the start.',
  'se.err.groups': 'Choose at least one group.',
  'se.err.perPurchase': 'Enter RM 0.01 to RM 1,000.00.',
  'se.err.daily': 'Enter RM 0.01 to RM 10,000.00.',
  'se.err.count': 'Enter a whole number from 1 to 100.',
  'se.err.gap': 'Enter a whole number of seconds from 0 to 600.',

  // ---- top-ups
  'tu.lede': 'Money parents paid online and subsidies the school gives. It waits on the platform until the card is tapped at the top-up kiosk.',
  'tu.subsidy': 'Grant a subsidy',
  'tu.subsidyTitle': 'Grant a subsidy',
  'tu.pickMember': 'Choose a student',
  'tu.member': 'Student',
  'tu.parked': 'Parked: needs a decision',
  'tu.parkedText':
    "The kiosk started writing these to the card but never confirmed, and the add window has passed. The money may already be on the card, so OneCard never refunds these by itself. Check the card's balance (tap it at the kiosk or a reader), then decide.",
  'tu.noParked': 'Nothing is parked.',
  'tu.parkedFacts': 'Paid {paid} · kiosk tried {tried} · add window ended {by}',
  'tu.onCard': 'It is on the card',
  'tu.notOnCard': 'Not on the card: refund',
  'tu.addedTitle': "Mark {amount} as added to {name}'s card?",
  'tu.addedBody': 'Only if you checked that the money is on the card. The top-up is closed as added; nothing is refunded.',
  'tu.refundTitle': 'Refund {amount} for {name}?',
  'tu.refundBody': 'Only if the money is NOT on the card. The payment is reversed in the books and the parent is refunded (mock bank).',
  'tu.note': 'Note: what did you check?',
  'tu.notePhAdded': 'e.g. Card read at the kiosk shows RM 20.00 more',
  'tu.notePhRefund': 'e.g. Card read at the kiosk: the money is not on it',
  'tu.markAdded': 'Mark as added',
  'tu.refund': 'Refund',
  'tu.addedDone': '{amount} for {name} is marked as added.',
  'tu.refundDone': '{amount} for {name} is refunded.',
  'tu.all': 'All top-ups and subsidies',
  'tu.status': 'Status',
  'tu.kind': 'Kind',
  'tu.allStatuses': 'All',
  'tu.allKinds': 'All',

  'order.created': 'Created',
  'order.member': 'Student',
  'order.kind': 'Kind',
  'order.amount': 'Amount',
  'order.status': 'Status',
  'order.detail': 'Where it stands',
  'order.empty': 'No top-ups or subsidies.',
  'order.payBy': 'Waiting for the parent to pay, until {at}',
  'order.unconfirmed': 'The kiosk started writing it at {at} but did not confirm',
  'order.writeFailed': 'The kiosk could not write it at {at}; it tries again at the next tap',
  'order.addBy': 'Waiting at the kiosk until {at}',
  'order.noDeadline': 'Waiting at the kiosk (no deadline)',
  'order.added': 'Added {at} by {device}',
  'order.markedAdded': 'Marked as added by {by}',
  'order.parked': 'Kiosk write not confirmed ({at}): needs a decision',
  'order.refundedBy': 'Refunded by decision of {by}',
  'order.refunded': 'Not added in time: refunded',
  'order.CANCELLED': 'Not paid in time',
  'order.FAILED': 'The payment failed',
  'order.EXPIRED': 'Not added in time',
  'orderStatus.CREATED': 'Waiting for payment',
  'orderStatus.PAID': 'Waiting at kiosk',
  'orderStatus.ADDED': 'Added to card',
  'orderStatus.PARKED': 'Needs a decision',
  'orderStatus.REFUNDED': 'Refunded',
  'orderStatus.CANCELLED': 'Cancelled',
  'orderStatus.FAILED': 'Payment failed',
  'orderStatus.EXPIRED': 'Expired',
  'orderKind.TOPUP': 'Parent top-up',
  'orderKind.SUBSIDY': 'School subsidy',
  'orderKind.TRANSFER': 'Card replacement transfer',

  'purchase.at': 'Time',
  'purchase.machine': 'Machine',
  'purchase.member': 'Student',
  'purchase.what': 'What',
  'purchase.amount': 'Amount',
  'purchase.priceVersion': 'Prices',
  'purchase.arrived': 'How it arrived',
  'purchase.status': 'Status',
  'purchase.empty': 'No purchases yet.',
  'purchase.water': '{ml} ml of water',
  'purchase.unknownCard': 'Unknown card',
  'purchase.late': 'late',
  'purchaseStatus.POSTED': 'In the books',
  'purchaseStatus.FLAGGED': 'Flagged',
  'via.MQTT': 'Live',
  'via.JOURNAL_BATCH': 'Catch-up upload',
  'via.KIOSK_READBACK': 'Kiosk read-back',
  'via.USB_IMPORT': 'USB import',
  'saleKind.SALE': 'Canteen',
  'saleKind.WATER': 'Water',

  // ---- books
  'bk.lede': "The school's double-entry books on the platform. Every payment, subsidy, kiosk write and purchase is a posting whose debits equal its credits.",
  'bk.tb': 'Trial balance',
  'bk.balanced': 'Balanced',
  'bk.balancedText': 'Total debits and total credits are both {amount}.',
  'bk.notBalanced': 'NOT balanced',
  'bk.notBalancedText': 'Debits {debit}, credits {credit}: {diff} apart. This should never happen; tell the platform operator.',
  'bk.account': 'Account',
  'bk.debit': 'Debit',
  'bk.credit': 'Credit',
  'bk.balance': 'Balance',
  'bk.members': '{n} accounts',
  'bk.totals': 'Totals',
  'bk.equal': 'equal',
  'bk.unequal': 'not equal',
  'bk.perMember': 'Per-student accounts ({n})',
  'bk.perMemberLabel': 'Per-student accounts',
  'bk.member': 'Student',
  'bk.sales': 'Sales by day',
  'bk.day': 'Day',
  'bk.show': 'Show',
  'bk.salesOn': 'Sales on {day}:',
  'bk.fromPurchases': 'from {n} purchases',
  'bk.byMachine': 'By machine',
  'bk.byItem': 'By item',
  'bk.machine': 'Machine',
  'bk.kind': 'Kind',
  'bk.count': 'Purchases',
  'bk.total': 'Total',
  'bk.item': 'Item',
  'bk.qty': 'Quantity',
  'bk.noSales': 'No sales.',
  'bk.postings': 'Latest postings',
  'bk.postingsText': 'Each posting moves money between accounts; its debits always equal its credits.',
  'bk.at': 'Time',
  'bk.what': 'What happened',
  'bk.lines': 'Debit and credit',
  'bk.memo': 'Memo',
  'bk.noPostings': 'No postings yet.',
  'bk.reverses': 'Undoes an earlier posting',
  'bk.dr': 'Debit',
  'bk.cr': 'Credit',
  'bk.purchases': 'Purchases',
  'bk.allMachines': 'All machines',
  'acct.CASH_RECEIVED': 'Cash received',
  'acct.STUDENT_WALLET': 'Student wallet',
  'acct.WAITING_TO_BE_ADDED': 'Waiting to be added',
  'acct.SCHOOL_SUBSIDY': 'School subsidy',
  'acct.SALES_PAYABLE': 'Sales owed to operators',
  'acctText.CASH_RECEIVED': 'Money the school has received from parents',
  'acctText.STUDENT_WALLET': "The platform's copy of the money on the cards",
  'acctText.WAITING_TO_BE_ADDED': 'Paid or granted, not on the cards yet',
  'acctText.SCHOOL_SUBSIDY': 'Subsidies the school gave',
  'acctText.SALES_PAYABLE': 'Canteen and water sales owed to the operators',
  'posting.TOPUP_PAID': 'Parent payment received',
  'posting.TOPUP_ADDED': 'Top-up added to the card',
  'posting.SUBSIDY_GRANTED': 'Subsidy granted',
  'posting.SUBSIDY_ADDED': 'Subsidy added to the card',
  'posting.TRANSFER_CREATED': 'Balance moved for a new card',
  'posting.TRANSFER_ADDED': 'Transfer added to the new card',
  'posting.PURCHASE': 'Purchase',
  'posting.REVERSAL': 'Refund (reversal)',

  // ---- reconciliation
  'rc.ledeAll': 'Differences the platform found between the cards, the machines and the books, and machine journals brought in on a USB stick.',
  'rc.ledeFinance': 'Differences the platform found between the cards, the machines and the books. Each needs a person to check it and resolve it with a note.',
  'rc.ledeOffice': "Bring in a machine's records on a USB stick when it cannot reach the network.",
  'rc.financeOnly': 'Differences are checked by finance staff.',
  'rc.differences': 'Differences',
  'rc.show': 'Show',
  'rc.filter.OPEN': 'Open',
  'rc.filter.RESOLVED': 'Resolved',
  'rc.filter.ALL': 'All',
  'rc.count.OPEN': '{n} open',
  'rc.count.RESOLVED': '{n} resolved',
  'rc.count.ALL': '{n} in total',
  'rc.noneOpen': 'No open differences. Everything adds up.',
  'rc.none': 'No differences.',
  'rc.found': 'found {at}',
  'rc.technical': 'Technical details',
  'rc.resolve': 'Resolve with a note',
  'rc.resolveTitle': 'Resolve this difference',
  'rc.resolveBody': 'Say what you checked and what you did. The note stays in the history with your name.',
  'rc.note': 'Note',
  'rc.notePlaceholder': "e.g. Copied card found and destroyed; the student's card was replaced.",
  'rc.resolveConfirm': 'Mark as resolved',
  'rc.resolvedDone': 'Resolved: {what}',
  'rc.resolvedBy': 'Resolved {at} by {by}',
  'rc.memberPage': "student's page",
  'rc.importTitle': "Import a machine's USB file",
  'rc.importText':
    "When a machine cannot reach the network, export its journal to a USB stick (in the lab: the machine's USB export in the lab console) and import the file here. Each record counts once: records already received show as duplicates.",
  'rc.file': 'Journal file (.json)',
  'rc.fileHint': 'The file must come from a machine of this school, unchanged.',
  'rc.import': 'Import',
  'rc.pickFile': 'Choose a file first.',
  'rc.tooBig': 'The file is larger than 1 MB: this is not a machine journal.',
  'rc.notJson': 'This file is not a machine journal (it is not JSON).',
  'rc.importedTitle': '{device}: {n} records read.',
  'rc.importedFrom': 'File {file}, exported {at}.',
  'rc.countPOSTED': 'New, in the books',
  'rc.countFLAGGED': 'New, flagged',
  'rc.countDUPLICATE': 'Already received',
  'rc.countREFUSED': 'Refused',
  'rc.countsHelp': 'Flagged records are in the books but need a look under Differences. Records already received do not count twice.',
  'rc.conflicts': '{n} records had the same number as an earlier one but different content. Finance staff see them as differences.',
  'rc.newDifferences': 'New differences found:',
  'rc.tellFinance': 'Tell your finance staff: they check differences.',
  'rc.refusedTitle': 'Refused records',
  'rc.txn': 'Transaction',
  'rc.reason': 'Reason',
  'rc.jobsTitle': "Run the platform's checks now",
  'rc.jobsText':
    "The platform runs these by itself every few seconds in the lab: unpaid top-ups are cancelled, money not added within the add window is refunded, unconfirmed kiosk writes are parked, and gaps in machines' transaction numbers and machines on an old block list are flagged.",
  'rc.runJobs': 'Run the checks now',
  'rc.job.cancelled': 'unpaid top-ups cancelled',
  'rc.job.refunded': 'refunded (not added in time)',
  'rc.job.parked': 'parked for a decision',
  'rc.job.gaps': 'new gaps in transaction numbers',
  'rc.job.lag': 'machines newly found on an old block list',
  'diffStatus.OPEN': 'Open',
  'diffStatus.RESOLVED': 'Resolved',
  // the platform's own wording (src/platform/differences.js DIFFERENCE_KINDS), for import results
  'diffKind.MISSING_RECORDS': 'A purchase the platform never received (gap in a machine’s transaction numbers)',
  'diffKind.DUPLICATE_CONFLICT': 'Same transaction number uploaded twice with different content',
  'diffKind.UNKNOWN_CARD': 'Purchase from a card this school does not know',
  'diffKind.PRICE_VERSION_UNKNOWN': 'Record names a price list version that was never issued',
  'diffKind.PRICE_MISMATCH': 'Amount does not match the price list version the machine used',
  'diffKind.BALANCE_CONTINUITY': 'Balance before minus amount does not equal balance after',
  'diffKind.BALANCE_MISMATCH': 'Card balance does not match the platform’s mirror balance',
  'diffKind.MIRROR_NEGATIVE': 'Mirror balance went below zero',
  'diffKind.SPENT_AFTER_LOST_REPORT': 'Card used after it was reported lost',
  'diffKind.CARD_CLONE_SUSPECTED': 'Two different purchases carry the same card counter (possible copied card)',
  'diffKind.OLD_BLOCK_LIST': 'Machine is still on an old block list',
  'diffKind.TOPUP_ADDED_AFTER_REFUND': 'Kiosk reports adding money that was already refunded',
  'diffKind.DOUBLE_ADD_SUSPECTED': 'The same top-up was reported added by a different write',
  'dk.origin': 'Machine',
  'dk.txn': 'Transaction',
  'dk.last4': 'Card',
  'dk.amountSen': 'Amount',
  'dk.expectedSen': 'Expected amount',
  'dk.priceVersion': 'Price version',
  'dk.latestVersion': 'Latest price version',
  'dk.problems': 'Problems',
  'dk.kind': 'Kind',
  'dk.balanceBeforeSen': 'Balance before',
  'dk.balanceAfterSen': 'Balance after',
  'dk.expectedAfterSen': 'Expected balance after',
  'dk.cardSeq': 'Card counter',
  'dk.purchases': 'Purchases',
  'dk.listVersionOnMachine': 'Block list on the machine',
  'dk.lostListVersion': 'Block list with the lost card',
  'dk.machineHadUpdatedList': 'Machine had the updated list',
  'dk.memberId': 'Student',
  'dk.walletSen': 'Wallet after',
  'dk.from': 'From number',
  'dk.to': 'To number',
  'dk.count': 'How many',
  'dk.fromTxn': 'First missing',
  'dk.toTxn': 'Last missing',
  'dk.deviceCode': 'Machine',
  'dk.appliedVersion': 'Version on the machine',
  'dk.currentVersion': 'Current version',
  'dk.currentSince': 'Current since',
  'dk.reportedVia': 'Reported',
  'dk.reportedAt': 'Reported at',
  'dk.cardSen': 'On the card',
  'dk.unconfirmedSen': 'Written but unconfirmed',
  'dk.mirrorSen': 'In the books',
  'dk.laterSen': 'Added after the read',
  'dk.differenceSen': 'Difference',
  'dk.hint': 'Hint',
  'dk.purchaseId': 'Purchase',
  'dk.changed': 'Changed fields',
  'dk.orderId': 'Top-up',
  'dk.memberNo': 'Number',
  'dk.note': 'Note',
  'dk.decision': 'Decision',
  'dk.uid': 'Card UID',
  'dk.code': 'Code',
  'dk.status': 'Status',
  'dk.version': 'Version',
  'dk.total': 'Total',
  'dk.counts': 'Counts',
  'dk.device': 'Machine',
  'dk.exportedAt': 'Exported',
  'dk.name': 'Name',
  'dk.devices': 'Machines',
  'dk.staff': 'Staff',
  'dk.demoMembers': 'Demo students',
  'dk.type': 'Type',
  'dk.location': 'Location',

  // ---- audit
  'au.lede': 'Who did what in this school, newest first. Only admins see this.',
  'au.limit': 'Show',
  'au.at': 'Time',
  'au.who': 'Who',
  'au.what': 'What',
  'au.detail': 'Details',
  'au.empty': 'Nothing recorded yet.',
  'au.parent': 'A parent',
  'au.seed': 'Lab set-up',
  'au.system': 'OneCard platform',
  'auditAction.member.add': 'Added a student or staff member',
  'auditAction.card.issue': 'Issued a card',
  'auditAction.card.lost': 'Reported a card lost',
  'auditAction.card.found': 'Marked a card found',
  'auditAction.card.replace': 'Replaced a card',
  'auditAction.invite.create': 'Created an invitation code',
  'auditAction.invite.redeem': 'A parent used an invitation code',
  'auditAction.link.approve': 'Approved a parent',
  'auditAction.link.reject': 'Rejected a parent',
  'auditAction.device.register': 'Registered a machine',
  'auditAction.device.status': 'Switched a machine on or off',
  'auditAction.config.publish': 'Published prices or settings',
  'auditAction.blocklist.start': 'Started the block list',
  'auditAction.school.create': 'School created',
  'auditAction.school.settings': 'Changed school settings',
  'auditAction.school.status': 'School suspended or reactivated',
  'auditAction.subsidy.grant': 'Granted a subsidy',
  'auditAction.tenant.create': 'School onboarded on the platform',
  'auditAction.topup.resolve': 'Decided on a parked top-up',
  'auditAction.transfer.create': 'Moved a balance to a new card',
  'auditAction.difference.resolve': 'Resolved a difference',
  'auditAction.journal.import': 'Imported a USB journal',
  'auditAction.admin-card.load': 'Loaded the admin card',
  'auditAction.admin-card.receipts': 'Admin card receipts uploaded',

  // ---- errors from the API, in plain words
  'err.STAFF_NOT_FOUND': 'That staff member no longer exists. Reload the page.',
  'err.SCHOOL_SUSPENDED': 'Your school is suspended on the OneCard platform.',
  'err.SCHOOL_NOT_FOUND': 'No such school.',
  'err.MEMBER_NOT_FOUND': 'There is no such student in your school.',
  'err.MEMBER_NO_TAKEN': 'This number is already used by someone in your school.',
  'err.MEMBER_NO_INVALID': 'Enter a number of up to 32 characters.',
  'err.NAME_INVALID': 'Enter a name of 1 to 100 characters.',
  'err.CLASS_NAME_INVALID': 'The class can be at most 40 characters.',
  'err.MEMBER_GROUP_INVALID': 'Choose Student or Staff.',
  'err.CARD_UID_INVALID': 'A card UID is 8 to 20 hex characters (0–9 and A–F), an even number of them, e.g. 04A1B2C3D4E5F6.',
  'err.CARD_UID_TAKEN': 'This card UID is already registered in your school.',
  'err.MEMBER_HAS_ACTIVE_CARD': 'This person already has an active card. Report it lost or replace it first.',
  'err.CARD_NOT_FOUND': 'There is no such card in your school.',
  'err.CARD_NOT_ACTIVE': 'This card is not active any more.',
  'err.CARD_NOT_LOST': 'This card is not reported lost.',
  'err.LINK_NOT_FOUND': 'This request no longer exists.',
  'err.LINK_ALREADY_DECIDED': 'Someone has already decided on this request.',
  'err.INVITE_INVALID': 'This invitation code is not valid.',
  'err.DEVICE_CODE_INVALID': 'Use capital letters, digits and dashes (up to 32), starting and ending with a letter or digit.',
  'err.DEVICE_CODE_TAKEN': 'Your school already has a machine with this code.',
  'err.DEVICE_TYPE_INVALID': 'Choose a machine type.',
  'err.DEVICE_STATUS_INVALID': 'Choose On, Maintenance or Off.',
  'err.DEVICE_NOT_FOUND': 'There is no machine with this code in your school.',
  'err.LOCATION_INVALID': 'The location can be at most 80 characters.',
  'err.CONFIG_INVALID': 'The machines would not accept this:',
  'err.ORDER_NOT_PARKED': 'This top-up is no longer parked: someone decided already, or the kiosk confirmed it.',
  'err.ORDER_NOT_FOUND': 'There is no such top-up in your school.',
  'err.DECISION_INVALID': 'Choose added or refund.',
  'err.AMOUNT_INVALID': 'Enter a valid amount.',
  'err.NOTE_INVALID': 'The note must be text.',
  'err.DIFFERENCE_NOT_FOUND': 'This difference no longer exists in your school.',
  'err.DIFFERENCE_ALREADY_RESOLVED': 'Someone has already resolved this difference.',
  'err.FILTER_INVALID': 'That filter is not valid.',
  'err.JOURNAL_INVALID': 'This is not a machine journal export (it needs the school, the machine and its records).',
  'err.JOURNAL_WRONG_SCHOOL': "This file was exported by a machine of another school. Each school imports only its own machines' files.",
  'err.JOURNAL_SIGNATURE_INVALID': 'The file does not match its signature: it was changed after the export, or another machine made it. Nothing was imported.',
  'err.DAY_INVALID': 'Choose a day.',
};

const zh = {
  'app.skip': '跳到内容',
  'app.home': 'OneCard 实验室首页',
  'app.name': '学校后台',
  'app.ribbon': '实验室 · 不是真钱',
  'app.yourSchool': '你在 OneCard 平台上的学校',
  'app.onlyYours': '你只看得到这所学校。平台上的其他学校在这里看不到。',
  'app.signOut': '退出登录',
  'app.sections': '栏目',
  'app.waiting': '正在等待 OneCard 服务器…',

  'signin.title': '学校后台：登录',
  'signin.lede': '仅限实验室：没有密码，选择你是谁即可。',
  'signin.tenants': '每所学校都是 OneCard 平台上独立的租户。职员只看得到自己的学校。',
  'signin.none': '还没有任何学校职员。请先在平台运营后台开通学校。',
  'signin.ended': '你的登录已结束（实验室可能重启了）。请重新登录。',
  'signin.suspended': '{school} 已在 OneCard 平台上被停用，职员无法登录。平台运营方可以在平台运营后台恢复它。',

  'school.ACTIVE': '正常',
  'school.SUSPENDED': '已停用',

  'role.OFFICE': '办公室',
  'role.FINANCE': '财务',
  'role.ADMIN': '管理员',
  'roleText.OFFICE': '学生、卡、家长、机器和价格',
  'roleText.FINANCE': '充值、补助、账本和对账',
  'roleText.ADMIN': '学校里的一切',

  'susp.short': '学校已停用',
  'susp.title': '{school} 已被停用',
  'susp.titleUnknown': '你的学校已被停用',
  'susp.text': 'OneCard 平台运营方停用了这所学校。停用期间，学校后台、学校的机器和家长都不能使用 OneCard。没有任何资料被删除。',
  'susp.ask': '请联系平台运营方恢复这所学校。本页每隔几秒会自动再检查。',
  'susp.lab': '在实验室里你也是平台运营方：',
  'susp.operatorLink': '打开平台运营后台',
  'susp.check': '再检查一次',
  'susp.still': '仍然停用中。',

  'nav.overview': '概览',
  'nav.students': '学生和卡',
  'nav.cards': '所有卡',
  'nav.parents': '家长',
  'nav.machines': '机器',
  'nav.prices': '价格和设置',
  'nav.topups': '充值',
  'nav.books': '账本',
  'nav.reconciliation': '对账',
  'nav.audit': '操作记录',
  'badge.reconciliation': '{n} 个未处理的差异',
  'badge.topups': '{n} 笔搁置的充值',
  'badge.parents': '{n} 个绑定申请待处理',

  'ov.lede': '{school} 今天的情况一览。点击方块进入处理它的栏目。',
  'ov.today': '实验室时钟上的今天：{day}',
  'ov.sales': '今日销售',
  'ov.salesSub': '食堂和饮水机共 {n} 笔消费',
  'ov.machines': '在线机器',
  'ov.machinesValue': '{online} / {total}',
  'ov.machinesOff': '{n} 台现在不在线（90 秒内没有心跳）',
  'ov.machinesAll': '所有机器都在线',
  'ov.waiting': '在充值机等着加值的钱',
  'ov.waitingSub': '已付款或已发放，还没加到卡上',
  'ov.differences': '未处理的差异',
  'ov.differencesSub': '需要有人检查',
  'ov.differencesFinance': '由财务职员检查',
  'ov.differencesNone': '没有需要检查的',
  'ov.parked': '搁置的充值',
  'ov.parkedSub': '需要决定：已在卡上，还是退款',
  'ov.parkedFinance': '由财务职员决定',
  'ov.parkedNone': '没有待决定的',
  'ov.links': '等待批准的家长',
  'ov.linksSub': '需要批准或拒绝的绑定申请',
  'ov.linksNone': '没有待处理的申请',
  'ov.tasks': '日常工作',
  'ov.task.lost': '卡丢了：找到学生，挂失这张卡',
  'ov.task.links': '批准绑定孩子的家长',
  'ov.task.prices': '修改食堂价格或水价',
  'ov.task.machines': '检查机器是否在线、版本是否最新',
  'ov.task.usb': '从 U 盘导入机器的流水',
  'ov.task.parked': '处理搁置的充值',
  'ov.task.subsidy': '给学生发放补助',
  'ov.task.books': '检查账本是否平衡',
  'ov.task.differences': '检查并处理差异',
  'ov.task.audit': '查看谁做了什么（操作记录）',
  'ov.tenantTitle': '共享平台上的一所学校',
  'ov.tenantText':
    '{school}（{code}）是 OneCard 平台的一个租户，平台用同一台服务器为很多学校服务。这个后台里的一切只属于 {school}：其他学校的学生、机器和钱永远不会出现在这里，即使你手动输入网址也一样。',

  'st.lede': '学校里所有持卡的人：学生和职员。点击名字查看余额、卡和记录。',
  'st.add': '新增学生或职员',
  'st.lists': '列表',
  'st.tabStudents': '学生和职员',
  'st.tabCards': '所有卡',
  'st.search': '搜索',
  'st.searchHint': '名字、编号、班级或卡号后 4 位',
  'st.count': '显示 {shown} / {total}',
  'st.no': '编号',
  'st.name': '名字',
  'st.fullName': '全名',
  'st.class': '班级',
  'st.group': '类别',
  'st.card': '卡',
  'st.balance': '平台余额',
  'st.waiting': '在充值机等着加值',
  'st.noCard': '没有卡',
  'st.noMatch': '没有符合搜索的人。',
  'st.empty': '还没有学生或职员。',
  'st.addTitle': '新增学生或职员',
  'st.addBody': '他们只会出现在这所学校。你可以现在或以后给他们发卡。',
  'st.noHint': '学校自己的编号，例如 S1007',
  'st.classHint': '可不填，例如 4 Bestari',
  'st.cardUid': '卡 UID（可不填）',
  'st.cardUidHint': '印在卡上或读卡读出的号码：8 到 20 个十六进制字符，例如 04A1B2C3D4E5F6。不填的话以后再发卡。',
  'st.addConfirm': '新增',
  'st.added': '已新增 {name}。',
  'st.addedWithCard': '已新增 {name}，卡 {card}。卡上起始余额 RM 0.00。',
  'group.STUDENT': '学生',
  'group.STAFF': '职员',
  'memberStatus.ACTIVE': '在校',
  'memberStatus.LEFT': '已离校',

  'cards.lede': '这所学校发过的每一张卡，包括挂失和换掉的。有人交来一张卡？用卡号后 4 位搜索。',
  'cards.card': '卡',
  'cards.holder': '持卡人',
  'cards.status': '状态',
  'cards.issued': '发卡时间',
  'cards.lostAt': '挂失时间',
  'cards.listVersion': '黑名单版本',
  'cards.actions': '操作',
  'cards.count': '显示 {shown} / {total} 张卡',
  'cards.empty': '还没有发过卡。',
  'cardStatus.ACTIVE': '使用中',
  'cardStatus.LOST': '已挂失',
  'cardStatus.RETIRED': '已作废',

  'card.uidInvalid': '卡 UID 是 8 到 20 个十六进制字符（0–9 和 A–F），字符数必须是双数，例如 04A1B2C3D4E5F6。',
  'card.uid': '卡 UID',
  'card.newUid': '新卡 UID',
  'card.uidHint': '从卡上读取：8 到 20 个十六进制字符，例如 04A1B2C3D4E5F6（可以有空格或冒号）',
  'card.sent': '新的黑名单已发给机器。',
  'card.notSent': '新的黑名单已保存但还没发出：平台连不上消息服务器（broker）。连接恢复后会自动发出。',
  'card.seeMachines': '查看哪些机器已收到',
  'card.lostButton': '挂失',
  'card.lostTitle': '挂失卡 {card}？',
  'card.lostBody': '{name} 的卡会列入学校的黑名单。收到新名单的机器会拒绝它。卡上的钱仍记在账上，可以转到补发的新卡。',
  'card.lostWindow': '没有网络的机器在收到新名单之前（插上网线，或参数卡到访）仍会接受这张卡。',
  'card.lostConfirm': '挂失',
  'card.lostDone': '卡 {card} 已挂失（黑名单版本 {version}）。',
  'card.foundButton': '标记为找回',
  'card.foundOne': '卡 {card} 已找回',
  'card.foundTitle': '把卡 {card} 标记为找回？',
  'card.foundBody': '{name} 的卡会从黑名单移除，机器收到新名单后就能再用。只有在还没补发新卡时才能这样做。',
  'card.foundConfirm': '标记为找回',
  'card.foundDone': '卡 {card} 可以再用了。',
  'card.replaceButton': '换卡',
  'card.replaceTitle': '为 {name} 换卡',
  'card.replaceOld': '目前的卡 {card} 会先被挂失，不能再用。',
  'card.replaceNoOld': '没有使用中的卡，不需要挂失。',
  'card.replaceMoney': '平台上的余额 {amount} 会转到新卡：在新卡到充值机拍卡之前，这笔钱会在那里等着。',
  'card.replaceConfirm': '换卡',
  'card.replaceDone': '已为 {name} 发新卡 {card}。',
  'card.replaceOldDone': '旧卡 {card} 已挂失。',
  'card.replaceTransfer': '{amount} 在充值机等新卡：请用新卡在那里拍卡。',
  'card.replaceNoTransfer': '没有需要转移的钱。',
  'card.issueButton': '发卡',
  'card.issueTitle': '给 {name} 发卡',
  'card.issueBody': '新卡起始余额 RM 0.00。钱要在充值机加到卡上。',
  'card.issueConfirm': '发卡',
  'card.issueDone': '已给 {name} 发卡 {card}。',

  'mem.back': '← 所有学生和职员',
  'mem.title': '学生',
  'mem.notFoundTitle': '找不到',
  'mem.notFound': '{school} 没有这个学生或职员。其他学校的人永远不会在这里显示。',
  'mem.noClass': '没有班级',
  'mem.balances': '余额',
  'mem.platformBalance': '平台上的余额',
  'mem.platformSub': '平台记录的卡上金额',
  'mem.waiting': '在充值机等着加值',
  'mem.waitingSub': '已付款或已发放；在充值机拍卡时加到卡上',
  'mem.neverAdded': '这两个金额永远不相加：等着加值的钱还不在卡上。',
  'mem.subsidy': '发放补助',
  'mem.card': '卡',
  'mem.onlyLost': '没有使用中的卡：上一张已挂失。',
  'mem.noCard': '还没有卡。',
  'mem.issued': '发卡时间 {at}',
  'mem.cardsByOffice': '卡由办公室职员处理。',
  'mem.parents': '家长',
  'mem.noParents': '还没有家长绑定这个孩子。',
  'mem.invite': '生成邀请码',
  'mem.allParents': '所有家长申请',
  'mem.waitingOrders': '在充值机等着加值',
  'mem.waitingOrdersText': '下次在充值机拍卡时，这些都会加到卡上。',
  'mem.noWaiting': '没有等着加值的钱。',
  'mem.purchases': '消费记录',
  'mem.orders': '充值和补助',
  'mem.cards': '卡',
  'mem.noCards': '没有卡。',

  'sub.title': '给 {name} 发放补助',
  'sub.body': '这笔钱由学校支付。它会在充值机等着，下次拍卡时加到卡上。如果在学校规定的期限内没有加到卡上，就会退回学校。',
  'sub.amount': '金额（RM）',
  'sub.note': '备注（可不填）',
  'sub.notePlaceholder': '例如：第三学期伙食补助',
  'sub.confirm': '发放补助',
  'sub.done': '已给 {name} 发放补助 {amount}。它会在充值机等到 {at}。',

  'inv.title': '给 {name} 家长的邀请码',
  'inv.body': '家长在家长网页（绑定孩子）输入这个邀请码。你在这里批准申请后，家长才看得到孩子。',
  'inv.confirm': '生成邀请码',
  'inv.done': '给 {name} 家长的邀请码：',
  'inv.next': '把邀请码交给家长。家长使用后，申请会出现在「家长」栏目等你批准。',

  'par.lede': '家长用学校给的邀请码绑定孩子。每个申请都要你批准，家长才看得到孩子或充值。',
  'par.newInvite': '生成邀请码',
  'par.newInviteTitle': '生成邀请码',
  'par.pickChild': '选择学生',
  'par.child': '孩子',
  'par.pending': '等你决定',
  'par.pendingText': '批准前请确认对方真的是孩子的家长或监护人。',
  'par.noPending': '没有待处理的申请。',
  'par.invites': '邀请码',
  'par.invitesText': '每个邀请码只能由一位家长用一次。',
  'par.noInvites': '还没有邀请码。',
  'par.decided': '已决定的申请',
  'par.noDecided': '还没有决定过的申请。',
  'par.parent': '家长',
  'par.email': '电邮',
  'par.status': '状态',
  'par.requested': '申请时间',
  'par.decision': '决定',
  'par.code': '邀请码',
  'par.created': '生成时间',
  'par.used': '使用时间',
  'par.approve': '批准',
  'par.reject': '拒绝',
  'par.approveTitle': '批准 {parent} 绑定 {child}？',
  'par.approveBody': '请确认 {parent}（{email}）真的是 {child} 的家长或监护人。批准后，对方可以看到孩子的余额和记录，也可以给卡充值。',
  'par.rejectTitle': '拒绝 {parent} 的申请？',
  'par.rejectBody': '{parent} 不会和 {child} 绑定。对方可以用新的邀请码再申请。',
  'par.approved': '{parent} 已和 {child} 绑定。',
  'par.rejected': '已拒绝 {parent} 的申请。',
  'linkStatus.PENDING': '待处理',
  'linkStatus.APPROVED': '已批准',
  'linkStatus.REJECTED': '已拒绝',
  'inviteStatus.OPEN': '未使用',
  'inviteStatus.USED': '已使用',
  'inviteStatus.REVOKED': '已撤回',

  'mac.lede': '学校的食堂刷卡机、饮水机和充值机。机器在 90 秒内有心跳就算在线。',
  'mac.register': '登记机器',
  'mac.list': '机器',
  'mac.versions': '每台机器的版本',
  'mac.versionsText': '每台机器确认收到的价格表、设置和黑名单。落后的机器还在用旧版本：联网时或参数卡到访时就会更新。',
  'mac.log': '机器日志',
  'mac.logText': '平台拒绝或觉得可疑的消息，最新的在前面。',
  'mac.logFilter': '机器',
  'mac.logAll': '所有机器',
  'mac.logAt': '时间',
  'mac.logLevel': '级别',
  'mac.logWhat': '发生了什么',
  'mac.logEmpty': '日志里没有记录。',
  'mac.machine': '机器',
  'mac.location': '位置',
  'mac.switched': '状态',
  'mac.connection': '连线',
  'mac.heartbeat': '最后心跳',
  'mac.software': '软件',
  'mac.change': '更改',
  'mac.changeButton': '开 / 关…',
  'mac.online': '在线',
  'mac.offline': '离线',
  'mac.empty': '还没有机器。',
  'mac.verNone': '没有',
  'mac.behind': '落后：已有 v{v}',
  'mac.upToDate': '最新',
  'mac.statusTitle': '开关 {code}',
  'mac.statusBody': '关掉或维修中的机器会立刻和服务器断开，在重新打开之前都不能再连上。重新打开时，它会收到目前的价格、设置和黑名单。',
  'mac.statusNow': '目前：{status}',
  'mac.statusLabel': '状态',
  'mac.statusConfirm': '保存',
  'mac.statusOn': '{code} 已打开，并收到目前的价格、设置和黑名单。',
  'mac.statusOnNotSent': '{code} 已打开，但目前的设置还没能发出（平台连不上消息服务器）。',
  'mac.statusOff': '{code} 现在是「{status}」。已断开的连线：{n}。',
  'mac.registerTitle': '登记机器',
  'mac.registerBody': '这所学校的新机器。它的密钥只会显示一次：机器用它为消息签名。',
  'mac.code': '机器编号',
  'mac.codeHint': '大写字母、数字和横线，例如 CANTEEN-03',
  'mac.codeInvalid': '请用大写字母、数字和横线（最多 32 个），开头和结尾必须是字母或数字。',
  'mac.type': '类型',
  'mac.locationHint': '例如：食堂 C 柜台',
  'mac.registerConfirm': '登记',
  'mac.registered': '{code}（{type}）已登记。',
  'mac.registeredSent': '目前的价格、设置和黑名单已发给它。',
  'mac.registeredNotSent': '它第一次连上时会收到目前的价格、设置和黑名单。',
  'devType.CANTEEN': '食堂刷卡机',
  'devType.WATER': '饮水机',
  'devType.KIOSK': '充值机',
  'devStatus.ACTIVE': '开',
  'devStatus.DISABLED': '关',
  'devStatus.MAINTENANCE': '维修中',
  'devStatusLong.ACTIVE': '开：正常工作',
  'devStatusLong.MAINTENANCE': '维修中：维修期间关闭',
  'devStatusLong.DISABLED': '关：停止使用',
  'stateVia.MQTT': '经网络',
  'stateVia.HEARTBEAT': '心跳回报',
  'stateVia.PROVISION': '安装时设定',
  'stateVia.ADMIN_CARD': '经参数卡',
  'kind.prices': '价格表',
  'kind.settings': '设置',
  'kind.blocklist': '黑名单',
  'level.INFO': '信息',
  'level.WARN': '警告',
  'level.ERROR': '错误',
  'log.SIGNATURE_INVALID': '已拒绝：消息不是用这台机器的密钥签名的（伪造或损坏）。',
  'log.SEQUENCE_ROLLBACK': '已拒绝：收到旧的消息编号（重放或回滚）。',
  'log.SCHOOL_SUSPENDED': '已拒绝：学校已被停用。',
  'log.DEVICE_DISABLED': '已拒绝：机器已关闭。',
  'log.WRONG_DEVICE_TYPE': '已拒绝：这种机器不能发送这种消息。',
  'log.ENVELOPE_INVALID': '已拒绝：消息格式不对。',
  'log.TOPIC_MISMATCH': '已拒绝：消息和发送的主题对不上。',
  'log.RECORD_INVALID': '已拒绝：消费记录格式不对。',
  'log.COUNT_MISMATCH': '已拒绝：补传的记录数目和声明的不符。',
  'log.UNKNOWN_ORIGIN_DEVICE': '已拒绝：记录里的机器不是这所学校的。',
  'log.REPLAY': '已拒绝：充值机的请求之前已收到过（重放）。',
  'log.VERSION_UNSUPPORTED': '已拒绝：机器用的协议版本平台不支持。',
  'log.UNKNOWN_TYPE': '已拒绝：未知的消息类型。',
  'log.ADMIN_CARD_REJECTED': '机器拒绝了参数卡。',
  'log.COMMAND_REJECTED': '机器拒绝了平台的指令。',

  'pr.lede': '机器收多少钱、什么时候卖。每次发布都会产生新版本：联网的机器几秒内收到，其他机器在重新连线或参数卡到访时收到。',
  'pr.refreshSide': '刷新机器版本',
  'pr.reached': '机器收到了吗？',
  'pr.reachedText': '每台机器都会确认自己的版本。没有网络的机器在连线或参数卡到访之前会一直落后。',
  'pr.blocklist': '黑名单',
  'pr.blocklistText': '拥有这个版本的机器都会拒绝名单上的卡。名单只带加密的卡参考码和卡号后 4 位，从不带完整卡号。',
  'pr.blockVersion': '版本 {v}',
  'pr.since': '自 {at} 起',
  'pr.blockEmpty': '没有被封锁的卡。',
  'pr.history': '版本记录',
  'pr.histWhat': '项目',
  'pr.histVersion': '版本',
  'pr.histCreated': '发布时间',
  'pr.histFrom': '生效时间',
  'pr.histEmpty': '还没有版本。',
  'pr.version': '版本 {v}',
  'pr.inUse': '发布于 {at}',
  'pr.noneYet': '还没发布过。',
  'pr.items': '食堂品项',
  'pr.code': '代码',
  'pr.itemName': '名称',
  'pr.price': '价格',
  'pr.remove': '移除',
  'pr.removeItem': '移除 {name}',
  'pr.addItem': '新增品项',
  'pr.codeHint': '代码：大写字母、数字和横线，例如 NASI-LEMAK。机器和收据都用这个代码。',
  'pr.water': '饮水',
  'pr.perLitre': '每公升价格（RM）',
  'pr.perLitreHint': '按毫升计费并四舍五入：每公升 RM 0.20 时，650 毫升收 RM 0.13。',
  'pr.minCharge': '最低收费（RM）',
  'pr.minChargeHint': '每次倒水最少收的钱。',
  'pr.publish': '发布价格表',
  'pr.undo': '撤销我的修改',
  'pr.fixFirst': '请先修正标出的栏位。',
  'pr.nothing': '没有改动：和版本 {v} 一样。',
  'pr.confirmTitle': '发布价格表版本 {v}？',
  'pr.confirmText': '联网的机器几秒内就换。没有网络的机器在连线或参数卡到访之前继续用旧价格。每笔消费都会记录所用的价格版本。',
  'pr.raced': '你编辑期间有人发布了版本 {v}。发布会用你现在看到的内容取代它。',
  'pr.published': '{what}版本 {v} 已发布。',
  'pr.sent': '已发给机器；联网的几秒内就会确认（见下方）。',
  'pr.notSent': '已保存，但还没发出：平台连不上消息服务器（broker）。连接恢复后会自动发出。',
  'pr.chAdded': '新品项：{name}，{price}',
  'pr.chPrice': '{name}：{from} → {to}',
  'pr.chName': '名称：{from} → {to}',
  'pr.chRemoved': '移除：{name}',
  'pr.chLitre': '每公升水价：{from} → {to}',
  'pr.chMin': '最低水费：{from} → {to}',
  'pr.err.code': '请用大写字母、数字和横线（1 到 24 个）。',
  'pr.err.codeTwice': '有两个品项用了这个代码。',
  'pr.err.name': '请填写品项名称（最多 40 个字）。',
  'pr.err.price': '请输入 RM 0.01 到 RM 1,000.00 的价格。',
  'pr.err.items': '价格表需要 1 到 50 个品项。',
  'pr.err.perLitre': '请输入 RM 0.01 到 RM 100.00。',
  'pr.err.minCharge': '请输入 RM 0.00 到 RM 100.00。',

  'se.addWindow': '新增时段',
  'se.removeWindow': '移除这个时段',
  'se.from': '从',
  'se.to': '到',
  'se.windows': '食堂和饮水机的营业时段',
  'se.windowsText': '吉隆坡时间。没有设时段的话，机器全天都卖。最多 6 个。',
  'se.anyTime': '全天',
  'se.groups': '谁可以买',
  'se.limits': '每张卡的限额',
  'se.perPurchase': '每笔最多（RM）',
  'se.daily': '每天最多（RM）',
  'se.count': '每天最多几笔',
  'se.gap': '两次拍卡的间隔（秒）',
  'se.inRM': '以令吉计，例如 20.00',
  'se.countHint': '1 到 100',
  'se.gapHint': '防止拍两次扣两次钱。0 到 600。',
  'se.publish': '发布设置',
  'se.nothing': '没有改动：和版本 {v} 一样。',
  'se.confirmTitle': '发布设置版本 {v}？',
  'se.confirmText': '联网的机器几秒内就换；没有网络的机器在连线或参数卡到访之前继续用旧设置。',
  'se.chWindows': '营业时段：{from} → {to}',
  'se.chGroups': '谁可以买：{from} → {to}',
  'se.chPerPurchase': '每笔最多：{from} → {to}',
  'se.chDaily': '每天最多：{from} → {to}',
  'se.chCount': '每天最多几笔：{from} → {to}',
  'se.chGap': '两次拍卡的间隔（秒）：{from} → {to}',
  'se.err.time': '请输入时间，例如 06:30。',
  'se.err.order': '结束时间必须在开始时间之后。',
  'se.err.groups': '至少选一个类别。',
  'se.err.perPurchase': '请输入 RM 0.01 到 RM 1,000.00。',
  'se.err.daily': '请输入 RM 0.01 到 RM 10,000.00。',
  'se.err.count': '请输入 1 到 100 的整数。',
  'se.err.gap': '请输入 0 到 600 的整数秒数。',

  'tu.lede': '家长在线付的钱和学校发的补助。在卡到充值机拍卡之前，钱都在平台上等着。',
  'tu.subsidy': '发放补助',
  'tu.subsidyTitle': '发放补助',
  'tu.pickMember': '选择学生',
  'tu.member': '学生',
  'tu.parked': '搁置：需要决定',
  'tu.parkedText': '充值机开始写卡但没有确认，而且加值期限已过。钱可能已经在卡上，所以 OneCard 不会自动退款。请先查看卡上余额（在充值机或刷卡机拍卡），再做决定。',
  'tu.noParked': '没有搁置的充值。',
  'tu.parkedFacts': '付款 {paid} · 充值机尝试 {tried} · 加值期限 {by}',
  'tu.onCard': '钱已在卡上',
  'tu.notOnCard': '不在卡上：退款',
  'tu.addedTitle': '把 {amount} 标记为已加到 {name} 的卡上？',
  'tu.addedBody': '只有在确认钱已在卡上时才这样做。这笔充值会以「已加值」结束，不会退款。',
  'tu.refundTitle': '为 {name} 退款 {amount}？',
  'tu.refundBody': '只有在钱「不在」卡上时才这样做。账上会冲销这笔付款，并退款给家长（模拟银行）。',
  'tu.note': '备注：你检查了什么？',
  'tu.notePhAdded': '例如：在充值机读卡，多了 RM 20.00',
  'tu.notePhRefund': '例如：在充值机读卡，钱不在卡上',
  'tu.markAdded': '标记为已加值',
  'tu.refund': '退款',
  'tu.addedDone': '{name} 的 {amount} 已标记为已加值。',
  'tu.refundDone': '{name} 的 {amount} 已退款。',
  'tu.all': '所有充值和补助',
  'tu.status': '状态',
  'tu.kind': '种类',
  'tu.allStatuses': '全部',
  'tu.allKinds': '全部',

  'order.created': '建立时间',
  'order.member': '学生',
  'order.kind': '种类',
  'order.amount': '金额',
  'order.status': '状态',
  'order.detail': '进度',
  'order.empty': '没有充值或补助。',
  'order.payBy': '等家长付款，期限 {at}',
  'order.unconfirmed': '充值机在 {at} 开始写卡，但没有确认',
  'order.writeFailed': '充值机在 {at} 写卡失败；下次拍卡会再试',
  'order.addBy': '在充值机等到 {at}',
  'order.noDeadline': '在充值机等着（没有期限）',
  'order.added': '{at} 由 {device} 加到卡上',
  'order.markedAdded': '由 {by} 标记为已加值',
  'order.parked': '充值机写卡没确认（{at}）：需要决定',
  'order.refundedBy': '由 {by} 决定退款',
  'order.refunded': '没有及时加值：已退款',
  'order.CANCELLED': '没有及时付款',
  'order.FAILED': '付款失败',
  'order.EXPIRED': '没有及时加值',
  'orderStatus.CREATED': '等待付款',
  'orderStatus.PAID': '等待加值',
  'orderStatus.ADDED': '已加到卡上',
  'orderStatus.PARKED': '待决定',
  'orderStatus.REFUNDED': '已退款',
  'orderStatus.CANCELLED': '已取消',
  'orderStatus.FAILED': '付款失败',
  'orderStatus.EXPIRED': '已过期',
  'orderKind.TOPUP': '家长充值',
  'orderKind.SUBSIDY': '学校补助',
  'orderKind.TRANSFER': '换卡转移',

  'purchase.at': '时间',
  'purchase.machine': '机器',
  'purchase.member': '学生',
  'purchase.what': '内容',
  'purchase.amount': '金额',
  'purchase.priceVersion': '价格版本',
  'purchase.arrived': '怎么传来',
  'purchase.status': '状态',
  'purchase.empty': '还没有消费记录。',
  'purchase.water': '{ml} 毫升水',
  'purchase.unknownCard': '不明的卡',
  'purchase.late': '迟到',
  'purchaseStatus.POSTED': '已入账',
  'purchaseStatus.FLAGGED': '已标记',
  'via.MQTT': '实时',
  'via.JOURNAL_BATCH': '补传',
  'via.KIOSK_READBACK': '充值机读卡回传',
  'via.USB_IMPORT': 'U 盘导入',
  'saleKind.SALE': '食堂',
  'saleKind.WATER': '饮水',

  'bk.lede': '学校在平台上的复式账本。每笔付款、补助、充值机写卡和消费都是一笔借贷相等的分录。',
  'bk.tb': '试算平衡',
  'bk.balanced': '平衡',
  'bk.balancedText': '借方合计和贷方合计都是 {amount}。',
  'bk.notBalanced': '不平衡',
  'bk.notBalancedText': '借方 {debit}，贷方 {credit}：相差 {diff}。这不应该发生；请通知平台运营方。',
  'bk.account': '账户',
  'bk.debit': '借方',
  'bk.credit': '贷方',
  'bk.balance': '余额',
  'bk.members': '{n} 个账户',
  'bk.totals': '合计',
  'bk.equal': '相等',
  'bk.unequal': '不相等',
  'bk.perMember': '每个学生的账户（{n}）',
  'bk.perMemberLabel': '每个学生的账户',
  'bk.member': '学生',
  'bk.sales': '每日销售',
  'bk.day': '日期',
  'bk.show': '显示',
  'bk.salesOn': '{day} 的销售：',
  'bk.fromPurchases': '共 {n} 笔消费',
  'bk.byMachine': '按机器',
  'bk.byItem': '按品项',
  'bk.machine': '机器',
  'bk.kind': '种类',
  'bk.count': '笔数',
  'bk.total': '合计',
  'bk.item': '品项',
  'bk.qty': '数量',
  'bk.noSales': '没有销售。',
  'bk.postings': '最近的分录',
  'bk.postingsText': '每笔分录在账户之间转移金额；借方永远等于贷方。',
  'bk.at': '时间',
  'bk.what': '发生了什么',
  'bk.lines': '借贷',
  'bk.memo': '备注',
  'bk.noPostings': '还没有分录。',
  'bk.reverses': '冲销之前的分录',
  'bk.dr': '借',
  'bk.cr': '贷',
  'bk.purchases': '消费记录',
  'bk.allMachines': '所有机器',
  'acct.CASH_RECEIVED': '已收现金',
  'acct.STUDENT_WALLET': '学生钱包',
  'acct.WAITING_TO_BE_ADDED': '待加到卡上',
  'acct.SCHOOL_SUBSIDY': '学校补助',
  'acct.SALES_PAYABLE': '应付经营者的销售额',
  'acctText.CASH_RECEIVED': '学校从家长那里收到的钱',
  'acctText.STUDENT_WALLET': '平台记录的卡上金额',
  'acctText.WAITING_TO_BE_ADDED': '已付款或已发放，还没加到卡上',
  'acctText.SCHOOL_SUBSIDY': '学校发放的补助',
  'acctText.SALES_PAYABLE': '欠食堂和饮水经营者的销售额',
  'posting.TOPUP_PAID': '收到家长付款',
  'posting.TOPUP_ADDED': '充值已加到卡上',
  'posting.SUBSIDY_GRANTED': '发放补助',
  'posting.SUBSIDY_ADDED': '补助已加到卡上',
  'posting.TRANSFER_CREATED': '换卡余额转移',
  'posting.TRANSFER_ADDED': '转移的钱已加到新卡',
  'posting.PURCHASE': '消费',
  'posting.REVERSAL': '退款（冲销）',

  'rc.ledeAll': '平台在卡、机器和账本之间发现的差异，以及用 U 盘带回来的机器流水。',
  'rc.ledeFinance': '平台在卡、机器和账本之间发现的差异。每一项都需要有人检查，并附备注处理。',
  'rc.ledeOffice': '机器连不上网络时，用 U 盘把它的记录带回来。',
  'rc.financeOnly': '差异由财务职员检查。',
  'rc.differences': '差异',
  'rc.show': '显示',
  'rc.filter.OPEN': '未处理',
  'rc.filter.RESOLVED': '已处理',
  'rc.filter.ALL': '全部',
  'rc.count.OPEN': '{n} 个未处理',
  'rc.count.RESOLVED': '{n} 个已处理',
  'rc.count.ALL': '共 {n} 个',
  'rc.noneOpen': '没有未处理的差异。一切都对得上。',
  'rc.none': '没有差异。',
  'rc.found': '发现于 {at}',
  'rc.technical': '技术细节',
  'rc.resolve': '附备注处理',
  'rc.resolveTitle': '处理这个差异',
  'rc.resolveBody': '写下你检查了什么、做了什么。备注会连同你的名字留在记录里。',
  'rc.note': '备注',
  'rc.notePlaceholder': '例如：找到复制卡并已销毁；学生已换新卡。',
  'rc.resolveConfirm': '标记为已处理',
  'rc.resolvedDone': '已处理：{what}',
  'rc.resolvedBy': '{at} 由 {by} 处理',
  'rc.memberPage': '学生页面',
  'rc.importTitle': '导入机器的 U 盘文件',
  'rc.importText': '机器连不上网络时，把它的流水导出到 U 盘（实验室里：在实验室控制台用机器的 USB 导出），再在这里导入。每笔记录只算一次：已收到的会显示为重复。',
  'rc.file': '流水文件（.json）',
  'rc.fileHint': '文件必须来自这所学校的机器，而且不能被改动。',
  'rc.import': '导入',
  'rc.pickFile': '请先选择文件。',
  'rc.tooBig': '文件超过 1 MB：这不是机器流水。',
  'rc.notJson': '这不是机器流水文件（不是 JSON）。',
  'rc.importedTitle': '{device}：读取了 {n} 笔记录。',
  'rc.importedFrom': '文件 {file}，导出时间 {at}。',
  'rc.countPOSTED': '新的，已入账',
  'rc.countFLAGGED': '新的，已标记',
  'rc.countDUPLICATE': '之前已收到',
  'rc.countREFUSED': '已拒绝',
  'rc.countsHelp': '已标记的记录已入账，但需要在「差异」里查看。之前已收到的记录不会重复计算。',
  'rc.conflicts': '有 {n} 笔记录和之前的编号相同但内容不同。财务职员会在差异里看到。',
  'rc.newDifferences': '发现新的差异：',
  'rc.tellFinance': '请通知财务职员：差异由他们检查。',
  'rc.refusedTitle': '被拒绝的记录',
  'rc.txn': '交易编号',
  'rc.reason': '原因',
  'rc.jobsTitle': '现在执行平台的检查',
  'rc.jobsText': '实验室里平台每隔几秒会自动执行：取消没付款的充值、退还期限内没加到卡上的钱、搁置未确认的充值机写卡，并标出机器交易编号的缺口和还在用旧黑名单的机器。',
  'rc.runJobs': '现在检查',
  'rc.job.cancelled': '笔没付款的充值已取消',
  'rc.job.refunded': '笔已退款（没及时加值）',
  'rc.job.parked': '笔已搁置待决定',
  'rc.job.gaps': '个新的交易编号缺口',
  'rc.job.lag': '台新发现还在用旧黑名单的机器',
  'diffStatus.OPEN': '未处理',
  'diffStatus.RESOLVED': '已处理',
  'diffKind.MISSING_RECORDS': '平台没收到的消费（机器流水号有缺口）',
  'diffKind.DUPLICATE_CONFLICT': '同一流水号上传了两次，内容不同',
  'diffKind.UNKNOWN_CARD': '本校不认识的卡的消费',
  'diffKind.PRICE_VERSION_UNKNOWN': '记录里的价格版本平台没发过',
  'diffKind.PRICE_MISMATCH': '金额和机器所用价格版本对不上',
  'diffKind.BALANCE_CONTINUITY': '扣前余额减金额不等于扣后余额',
  'diffKind.BALANCE_MISMATCH': '卡上余额和平台镜像余额对不上',
  'diffKind.MIRROR_NEGATIVE': '镜像余额变成负数',
  'diffKind.SPENT_AFTER_LOST_REPORT': '挂失后卡还被使用',
  'diffKind.CARD_CLONE_SUSPECTED': '两笔不同消费带同一个卡计数（可能是复制卡）',
  'diffKind.OLD_BLOCK_LIST': '机器还在用旧的黑名单',
  'diffKind.TOPUP_ADDED_AFTER_REFUND': '充值机回报已加的钱其实已退款',
  'diffKind.DOUBLE_ADD_SUSPECTED': '同一笔充值被另一次写卡回报已加',
  'dk.origin': '机器',
  'dk.txn': '交易编号',
  'dk.last4': '卡',
  'dk.amountSen': '金额',
  'dk.expectedSen': '应收金额',
  'dk.priceVersion': '价格版本',
  'dk.latestVersion': '最新价格版本',
  'dk.problems': '问题',
  'dk.kind': '种类',
  'dk.balanceBeforeSen': '扣前余额',
  'dk.balanceAfterSen': '扣后余额',
  'dk.expectedAfterSen': '应有的扣后余额',
  'dk.cardSeq': '卡计数',
  'dk.purchases': '消费',
  'dk.listVersionOnMachine': '机器上的黑名单版本',
  'dk.lostListVersion': '列入这张挂失卡的黑名单版本',
  'dk.machineHadUpdatedList': '机器已有更新的名单',
  'dk.memberId': '学生',
  'dk.walletSen': '之后的钱包余额',
  'dk.from': '起始编号',
  'dk.to': '结束编号',
  'dk.count': '数目',
  'dk.fromTxn': '第一个缺少的',
  'dk.toTxn': '最后一个缺少的',
  'dk.deviceCode': '机器',
  'dk.appliedVersion': '机器上的版本',
  'dk.currentVersion': '目前版本',
  'dk.currentSince': '目前版本自',
  'dk.reportedVia': '回报方式',
  'dk.reportedAt': '回报时间',
  'dk.cardSen': '卡上',
  'dk.unconfirmedSen': '已写入但未确认',
  'dk.mirrorSen': '账上',
  'dk.laterSen': '读卡后才加的',
  'dk.differenceSen': '差额',
  'dk.hint': '提示',
  'dk.purchaseId': '消费记录',
  'dk.changed': '改变的栏位',
  'dk.orderId': '充值',
  'dk.memberNo': '编号',
  'dk.note': '备注',
  'dk.decision': '决定',
  'dk.uid': '卡 UID',
  'dk.code': '代码',
  'dk.status': '状态',
  'dk.version': '版本',
  'dk.total': '合计',
  'dk.counts': '数目',
  'dk.device': '机器',
  'dk.exportedAt': '导出时间',
  'dk.name': '名字',
  'dk.devices': '机器',
  'dk.staff': '职员',
  'dk.demoMembers': '示范学生',
  'dk.type': '类型',
  'dk.location': '位置',

  'au.lede': '这所学校里谁做了什么，最新的在前面。只有管理员看得到。',
  'au.limit': '显示',
  'au.at': '时间',
  'au.who': '谁',
  'au.what': '做了什么',
  'au.detail': '细节',
  'au.empty': '还没有记录。',
  'au.parent': '一位家长',
  'au.seed': '实验室初始资料',
  'au.system': 'OneCard 平台',
  'auditAction.member.add': '新增学生或职员',
  'auditAction.card.issue': '发卡',
  'auditAction.card.lost': '挂失',
  'auditAction.card.found': '标记卡已找回',
  'auditAction.card.replace': '换卡',
  'auditAction.invite.create': '生成邀请码',
  'auditAction.invite.redeem': '家长使用了邀请码',
  'auditAction.link.approve': '批准家长',
  'auditAction.link.reject': '拒绝家长',
  'auditAction.device.register': '登记机器',
  'auditAction.device.status': '开关机器',
  'auditAction.config.publish': '发布价格或设置',
  'auditAction.blocklist.start': '建立黑名单',
  'auditAction.school.create': '建立学校',
  'auditAction.school.settings': '修改学校设定',
  'auditAction.school.status': '学校被停用或恢复',
  'auditAction.subsidy.grant': '发放补助',
  'auditAction.tenant.create': '学校在平台上开通',
  'auditAction.topup.resolve': '处理搁置的充值',
  'auditAction.transfer.create': '把余额转到新卡',
  'auditAction.difference.resolve': '处理差异',
  'auditAction.journal.import': '导入 U 盘流水',
  'auditAction.admin-card.load': '载入参数卡',
  'auditAction.admin-card.receipts': '上传参数卡回执',

  'err.STAFF_NOT_FOUND': '这位职员已不存在。请重新加载页面。',
  'err.SCHOOL_SUSPENDED': '你的学校已在 OneCard 平台上被停用。',
  'err.SCHOOL_NOT_FOUND': '没有这所学校。',
  'err.MEMBER_NOT_FOUND': '你的学校没有这个学生。',
  'err.MEMBER_NO_TAKEN': '这个编号已被学校里的其他人使用。',
  'err.MEMBER_NO_INVALID': '请输入最多 32 个字符的编号。',
  'err.NAME_INVALID': '请输入 1 到 100 个字的名字。',
  'err.CLASS_NAME_INVALID': '班级最多 40 个字。',
  'err.MEMBER_GROUP_INVALID': '请选择学生或职员。',
  'err.CARD_UID_INVALID': '卡 UID 是 8 到 20 个十六进制字符（0–9 和 A–F），字符数必须是双数，例如 04A1B2C3D4E5F6。',
  'err.CARD_UID_TAKEN': '这个卡 UID 在你的学校已登记过。',
  'err.MEMBER_HAS_ACTIVE_CARD': '这个人已经有使用中的卡。请先挂失或换卡。',
  'err.CARD_NOT_FOUND': '你的学校没有这张卡。',
  'err.CARD_NOT_ACTIVE': '这张卡已不是使用中。',
  'err.CARD_NOT_LOST': '这张卡没有挂失。',
  'err.LINK_NOT_FOUND': '这个申请已不存在。',
  'err.LINK_ALREADY_DECIDED': '已经有人处理过这个申请。',
  'err.INVITE_INVALID': '这个邀请码无效。',
  'err.DEVICE_CODE_INVALID': '请用大写字母、数字和横线（最多 32 个），开头和结尾必须是字母或数字。',
  'err.DEVICE_CODE_TAKEN': '你的学校已经有这个编号的机器。',
  'err.DEVICE_TYPE_INVALID': '请选择机器类型。',
  'err.DEVICE_STATUS_INVALID': '请选择开、维修中或关。',
  'err.DEVICE_NOT_FOUND': '你的学校没有这个编号的机器。',
  'err.LOCATION_INVALID': '位置最多 80 个字。',
  'err.CONFIG_INVALID': '机器不会接受这个：',
  'err.ORDER_NOT_PARKED': '这笔充值已不在搁置状态：有人已处理，或充值机已确认。',
  'err.ORDER_NOT_FOUND': '你的学校没有这笔充值。',
  'err.DECISION_INVALID': '请选择已加值或退款。',
  'err.AMOUNT_INVALID': '请输入有效的金额。',
  'err.NOTE_INVALID': '备注必须是文字。',
  'err.DIFFERENCE_NOT_FOUND': '你的学校已没有这个差异。',
  'err.DIFFERENCE_ALREADY_RESOLVED': '已经有人处理过这个差异。',
  'err.FILTER_INVALID': '这个筛选条件无效。',
  'err.JOURNAL_INVALID': '这不是机器流水导出文件（需要学校、机器和记录）。',
  'err.JOURNAL_WRONG_SCHOOL': '这个文件是另一所学校的机器导出的。每所学校只能导入自己机器的文件。',
  'err.JOURNAL_SIGNATURE_INVALID': '文件和它的签名对不上：导出后被改动过，或是别的机器做的。没有导入任何东西。',
  'err.DAY_INVALID': '请选择日期。',
};

export const STRINGS = { en, zh };
