// Every visible string of the parent app, in English and Chinese (中文).
// Parents are not engineers: plain words, say what happens, say what to do next.
// {name}-style placeholders are filled in by i18n.t(key, vars).

export const STRINGS = {
  en: {
    // shell
    ribbon: 'LAB · not real money',
    appName: 'Parents',
    appTitle: 'OneCard for parents',
    skip: 'Skip to content',
    signedInAs: 'Signed in as {name}',
    signOut: 'Sign out',
    labHome: 'All lab apps',
    footNote: 'A practice lab: the people, schools and money here are made up.',

    // server down / no network
    offlineTitle: 'The OneCard server can’t be reached right now.',
    offlineText: 'Your money is safe. In the lab, the server can be switched back on from the lab console. This page keeps trying by itself.',
    networkTitle: 'Can’t reach the lab server.',
    networkText: 'Check that the lab is still running on this computer. This page keeps trying by itself.',
    backOnline: 'Connected again.',
    backOnlineTitle: 'OneCard is back',
    waitingServer: 'Waiting for the OneCard server…',
    waitingServerText: 'This page opens by itself as soon as the server answers.',
    backOnlineRetry: 'Press “Try again” to go on with your top-up. It is safe: you won’t pay twice.',

    // sign in
    signinTitle: 'Welcome to OneCard',
    signinLede: 'See your child’s card balance and top up the card from your phone.',
    labNoticeTitle: 'Lab sign-in: no passwords',
    labNoticeText: 'This is a practice lab with made-up people. Pick a demo parent to sign in as, or create a new parent. A real app would ask for your own login.',
    demoParents: 'Sign in as a demo parent',
    noChildrenYet: 'No children linked yet',
    newParentTitle: 'New parent',
    newParentText: 'Create a parent for the lab, then link a child with an invitation code from the school.',
    yourName: 'Your name',
    yourEmail: 'Email',
    emailHint: 'Use a made-up address, like name@example.com.',
    createParent: 'Create parent and sign in',
    signingIn: 'Signing in…',
    creating: 'Creating…',
    errNameRequired: 'Please enter your name.',
    errEmailRequired: 'Please enter an email address, like name@example.com.',
    EMAIL_INVALID: 'That email address doesn’t look right. Use one like name@example.com.',
    EMAIL_TAKEN: 'A parent with this email already exists. Pick them from the demo parents, or use another email.',
    NAME_INVALID: 'Please enter your name (up to 100 characters).',
    PARENT_NOT_FOUND: 'This parent no longer exists (the lab may have been reset). The list has been refreshed: please pick again.',

    // home
    hello: 'Hello, {name}',
    yourChildren: 'Your children',
    kidsInSchools: '{kids} children in {schools} schools. Each school runs its own card.',
    kidsAtSchool: '{kids} children at {school}.',
    noChildrenTitle: 'No children linked yet',
    noChildrenPending: 'Your request is with the school office. Your child appears here once the school approves it.',
    noChildrenText: 'Ask the school office for an invitation code, then enter it under “Link a child”.',
    onCard: 'On the card',
    waitingAtKiosk: 'Waiting at the kiosk',
    asOf: 'as of {time}',
    noCardUseYet: 'No card use recorded yet',
    notOnCardYet: 'Not on the card yet',
    cardEnding: 'Card ending {last4}',
    cardLostShort: 'Card reported lost',
    cardRetiredShort: 'Card no longer used',
    noCardShort: 'No card yet',
    schoolPausedShort: 'This school is paused on OneCard. Balance and top-ups are not available for now.',
    open: 'Open',
    pendingTitle: 'Waiting for the school',
    pendingText: 'The school office checks each request before linking a child to you.',
    sentOn: 'Sent {time}',
    pendingStatus: 'Waiting for approval',
    rejectedStatus: 'Not approved',
    rejectedText: 'The school didn’t approve this request. Ask the school office for a new invitation code.',
    linkTitle: 'Link a child',
    linkText: 'Enter the invitation code the school gave you. It has 8 letters and numbers and works once.',
    codeLabel: 'Invitation code',
    codePlaceholder: 'e.g. ABCD 2345',
    linkSubmit: 'Send to the school',
    linkSending: 'Sending…',
    linkSent: 'Request sent to {school}. {child} will appear here once the school approves it.',
    linkAgain: 'You already sent this code. {child} will appear here once {school} approves it.',
    errCodeRequired: 'Please enter the invitation code.',
    INVITE_INVALID: 'That code doesn’t work. Check the letters and numbers, or ask the school office for a new code. Each code works only once.',
    LINK_EXISTS: 'You have already asked to link this child, or the child is already linked to you.',

    // child page
    backToChildren: 'My children',
    classOf: 'Class {name}',
    moneyFor: 'Money for {name}',
    waitingExplain: 'Waiting money is added when your child taps the card at the school’s top-up kiosk.',
    balanceExplain: 'The card itself holds the money. “On the card” is what the school’s machines last reported.',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    updated: 'Updated.',
    topUp: 'Top up the card',
    unpaidTitle: 'Not paid yet',
    unpaidText: 'You started a top-up of {amount} on {time} but haven’t paid it.',
    unpaidPayBy: 'You can still pay until {time}. If you don’t, it is cancelled by itself and nothing is charged.',
    payNow: 'Pay {amount} now',
    historyTitle: 'History',
    tabTopups: 'Top-ups',
    tabPurchases: 'Purchases',
    noTopups: 'No top-ups yet.',
    noPurchases: 'No purchases yet.',
    purchasesNote: 'Machines without a network send their purchases later, so a purchase can show up after a while.',
    showMore: 'Show more',
    kindTOPUP: 'Top-up by you',
    kindSUBSIDY: 'School subsidy',
    kindTRANSFER: 'Moved from the old card',
    statusCREATED: 'Not paid yet',
    statusPAID: 'Waiting at the kiosk',
    statusADDED: 'Added to the card',
    statusPARKED: 'School is checking',
    statusEXPIRED: 'Refunded',
    statusREFUNDED: 'Refunded',
    statusFAILED: 'Payment declined',
    statusCANCELLED: 'Not paid in time',
    detailStarted: 'Started {time}',
    detailPayBy: 'Pay by {time}',
    detailPaid: 'Paid {time}',
    detailGiven: 'Given by the school {time}',
    detailMoved: 'Moved {time}',
    detailAddBy: 'Refunded by itself if not added by {time}',
    detailAdded: 'Added to the card {time}',
    detailParked: 'The kiosk may have added it already. The school office is checking.',
    detailRefundedTopup: 'Not added in time, so the money went back to you.',
    detailRefundedSubsidy: 'Not added in time, so it went back to the school.',
    detailFailed: 'The bank declined it. Nothing was charged.',
    detailCancelled: 'Not paid in time. Nothing was charged.',
    purchaseSALE: 'Canteen',
    purchaseWATER: 'Drinking water',
    litres: '{n} litres',
    tryAgain: 'Try again',
    loadFailed: 'We couldn’t load this.',

    // problems with a child
    suspendedTitle: '{school} is paused on OneCard',
    suspendedText: 'While the school is paused, you can’t see {child}’s balance or top up. Money you already paid is safe. Please contact the school.',
    notLinkedTitle: 'Child not found',
    notLinkedText: 'This child isn’t linked to your account. Go back to your children to see who is.',
    noCardTitle: '{child} has no card yet',
    noCardText: 'The school office gives out the cards. You can top up once {child} has one.',
    lostCardTitle: '{child}’s card was reported lost',
    lostCardText: 'Top-ups are paused until the school office gives {child} a new card.',
    retiredCardTitle: '{child}’s card is no longer used',
    retiredCardText: 'Please ask the school office about a new card.',

    // top-up form
    topupTitle: 'Top up the card',
    topupFor: 'For {child} at {school}',
    howMuch: 'How much?',
    otherAmount: 'Other amount',
    otherAmountHint: 'In ringgit, like 15 or 15.50',
    limitsKnown: '{school} accepts {min} to {max} per top-up.',
    nextTitle: 'What happens next',
    step1: 'You pay at the bank. In the lab it is a pretend bank: nothing is charged.',
    step2: 'The money waits on OneCard for {child}.',
    step3: 'Your child taps the card at the school’s top-up kiosk, and the money goes onto the card.',
    continueToBank: 'Continue to the bank',
    continueToBankAmount: 'Continue to the bank · {amount}',
    leaveNote: 'You’ll leave this page to pay, then come back here.',
    starting: 'Starting the top-up…',
    goingToBank: 'Opening the bank…',
    errChooseAmount: 'Choose an amount, or type one in.',
    errAmountFormat: 'Type the amount in ringgit, like 15 or 15.50.',
    errAmountZero: 'The amount must be more than RM 0.00.',
    refusedTitle: 'This top-up can’t be made',
    AMOUNT_OUT_OF_RANGE: '{school} accepts top-ups from {min} to {max} at a time. Please choose an amount in that range.',
    DAILY_LIMIT: '{school} allows up to {limit} of top-ups a day for each child. Today {child} already has {used} in top-ups, so you can add up to {remaining} more today.',
    DAILY_LIMIT_NONE: '{school} allows up to {limit} of top-ups a day for each child. {child} has reached that today, so please top up again tomorrow.',
    MONTHLY_LIMIT: '{school} allows up to {limit} of top-ups a month for each child. This month {child} already has {used} in top-ups, so you can add up to {remaining} more this month.',
    MONTHLY_LIMIT_NONE: '{school} allows up to {limit} of top-ups a month for each child. {child} has reached that this month, so please top up again next month.',
    limitCountsNote: 'This counts top-ups from every parent, and top-ups started but not paid yet until their payment time runs out.',
    useAmount: 'Use {amount}',
    AMOUNT_INVALID: 'Type the amount in ringgit, like 15 or 15.50.',
    CARD_NOT_ACTIVE: '{child} has no working card right now, so the money couldn’t be added. Please ask the school office.',
    NOT_LINKED: '{child} isn’t linked to your account any more.',
    uncertainTitle: 'No answer from OneCard',
    uncertainText: 'We didn’t get an answer, so we can’t tell if the top-up started. Press “Try again”: it is safe, and you won’t pay twice.',
    downTitle: 'The OneCard server is off',
    downText: 'The top-up didn’t start. Press “Try again” once the server is back on: you won’t pay twice.',
    CROSS_ORIGIN: 'OneCard refused a request that didn’t come from this page. Reload the page and try again.',
    genericError: 'Something went wrong ({code}). Please try again.',

    // back from the bank
    resultTitle: 'Your top-up',
    resultPaidTitle: 'Payment received',
    resultPaidText: '{amount} is now waiting for {child} at {school}. It goes onto the card when your child taps the card at the school’s top-up kiosk.',
    reference: 'Reference {ref}',
    resultPaidAddBy: 'If it isn’t added by {time}, the money comes back to you by itself.',
    resultAddedTitle: 'Paid and added to the card',
    resultAddedText: '{amount} is already on {child}’s card.',
    resultFailedTitle: 'Payment declined',
    resultFailedText: 'The bank declined the payment of {amount}, so nothing was charged and nothing is waiting. You can try again.',
    resultCreatedTitle: 'Not paid yet',
    resultCreatedText: 'You haven’t finished paying {amount} for {child}. The payment link works until {time}.',
    resultCancelledTitle: 'Payment time ran out',
    resultCancelledText: '{amount} for {child} wasn’t paid in time, so it was cancelled. Nothing was charged.',
    resultRefundedTitle: 'Refunded',
    resultRefundedText: '{amount} wasn’t added to the card in time, so it went back to you.',
    resultParkedTitle: 'Payment received, being checked',
    resultParkedText: 'The kiosk may already have added {amount}. The school office is checking.',
    resultMissingTitle: 'We couldn’t find this payment',
    resultMissingText: 'It may belong to another parent, or the lab was reset. Each child’s page lists every top-up.',
    seeChild: 'See {child}’s card',
    startNewTopup: 'Start a new top-up',
    backHome: 'Back to my children',
    later: 'Not now',
  },

  zh: {
    // shell
    ribbon: '实验室 · 不是真钱',
    appName: '家长',
    appTitle: 'OneCard 家长网页',
    skip: '跳到内容',
    signedInAs: '已登录：{name}',
    signOut: '登出',
    labHome: '实验室所有应用',
    footNote: '这是练习用的实验室：这里的人、学校和钱都是虚构的。',

    offlineTitle: '现在连不上 OneCard 服务器。',
    offlineText: '你的钱是安全的。在实验室里，可以在实验室控制台把服务器重新打开。这个页面会自己一直重试。',
    networkTitle: '连不上实验室服务器。',
    networkText: '请确认实验室还在这台电脑上运行。这个页面会自己一直重试。',
    backOnline: '已经重新连上。',
    backOnlineTitle: 'OneCard 已经恢复',
    waitingServer: '正在等 OneCard 服务器…',
    waitingServerText: '服务器一回应，这个页面就会自己打开。',
    backOnlineRetry: '请按“再试一次”继续充值。这样做是安全的，你不会付两次钱。',

    signinTitle: '欢迎使用 OneCard',
    signinLede: '用手机查看孩子卡上的余额，也可以为卡充值。',
    labNoticeTitle: '实验室登录：不用密码',
    labNoticeText: '这是练习用的实验室，里面的人都是虚构的。选一位示范家长登录，或新建一位家长。真正的应用会要你用自己的账号登录。',
    demoParents: '以示范家长登录',
    noChildrenYet: '还没有绑定孩子',
    newParentTitle: '新家长',
    newParentText: '为实验室新建一位家长，然后用学校给的邀请码绑定孩子。',
    yourName: '你的名字',
    yourEmail: '电邮',
    emailHint: '请用虚构的地址，例如 name@example.com。',
    createParent: '新建家长并登录',
    signingIn: '正在登录…',
    creating: '正在新建…',
    errNameRequired: '请输入你的名字。',
    errEmailRequired: '请输入电邮地址，例如 name@example.com。',
    EMAIL_INVALID: '这个电邮地址好像不对。请用像 name@example.com 这样的地址。',
    EMAIL_TAKEN: '已经有家长用这个电邮。请在示范家长里选他，或换一个电邮。',
    NAME_INVALID: '请输入你的名字（最多 100 个字）。',
    PARENT_NOT_FOUND: '这位家长已经不存在（实验室可能已重置）。名单已经更新，请再选一次。',

    hello: '你好，{name}',
    yourChildren: '你的孩子',
    kidsInSchools: '{kids} 个孩子，在 {schools} 间学校。每间学校的卡各自分开。',
    kidsAtSchool: '{kids} 个孩子，都在 {school}。',
    noChildrenTitle: '还没有绑定孩子',
    noChildrenPending: '你的申请已送到学校办公室。学校批准后，孩子就会出现在这里。',
    noChildrenText: '请向学校办公室索取邀请码，然后在“绑定孩子”输入。',
    onCard: '卡上余额',
    waitingAtKiosk: '等待加到卡上',
    asOf: '截至 {time}',
    noCardUseYet: '还没有用卡记录',
    notOnCardYet: '还没加到卡上',
    cardEnding: '卡号尾数 {last4}',
    cardLostShort: '卡已挂失',
    cardRetiredShort: '卡已停用',
    noCardShort: '还没有卡',
    schoolPausedShort: '这间学校在 OneCard 上已暂停，暂时不能查看余额或充值。',
    open: '打开',
    pendingTitle: '等待学校批准',
    pendingText: '学校办公室会先核对每个申请，才把孩子绑定给你。',
    sentOn: '{time} 送出',
    pendingStatus: '等待批准',
    rejectedStatus: '没有批准',
    rejectedText: '学校没有批准这个申请。请向学校办公室索取新的邀请码。',
    linkTitle: '绑定孩子',
    linkText: '输入学校给你的邀请码。邀请码有 8 个英文字母和数字，只能用一次。',
    codeLabel: '邀请码',
    codePlaceholder: '例如 ABCD 2345',
    linkSubmit: '送去学校',
    linkSending: '正在送出…',
    linkSent: '申请已送到 {school}。学校批准后，{child} 就会出现在这里。',
    linkAgain: '你已经送出这个邀请码。{school} 批准后，{child} 就会出现在这里。',
    errCodeRequired: '请输入邀请码。',
    INVITE_INVALID: '这个邀请码不能用。请检查字母和数字，或向学校办公室索取新的邀请码。每个邀请码只能用一次。',
    LINK_EXISTS: '你已经申请绑定这个孩子，或这个孩子已经绑定给你了。',

    backToChildren: '我的孩子',
    classOf: '班级 {name}',
    moneyFor: '{name} 的钱',
    waitingExplain: '孩子在学校的充值机拍卡时，等待的钱就会加到卡上。',
    balanceExplain: '钱存在卡里面。“卡上余额”是学校机器最后一次报来的数目。',
    refresh: '刷新',
    refreshing: '正在刷新…',
    updated: '已更新。',
    topUp: '为卡充值',
    unpaidTitle: '还没付款',
    unpaidText: '你在 {time} 开始了一笔 {amount} 的充值，但还没付款。',
    unpaidPayBy: '在 {time} 之前还可以付款；过了时间会自动取消，不会扣钱。',
    payNow: '现在付款 {amount}',
    historyTitle: '记录',
    tabTopups: '充值',
    tabPurchases: '消费',
    noTopups: '还没有充值记录。',
    noPurchases: '还没有消费记录。',
    purchasesNote: '没有网络的机器会迟一点才送来消费记录，所以有些消费会晚一些才出现。',
    showMore: '显示更多',
    kindTOPUP: '你的充值',
    kindSUBSIDY: '学校补助',
    kindTRANSFER: '旧卡余额转入',
    statusCREATED: '还没付款',
    statusPAID: '等待加到卡上',
    statusADDED: '已加到卡上',
    statusPARKED: '学校核对中',
    statusEXPIRED: '已退款',
    statusREFUNDED: '已退款',
    statusFAILED: '付款被拒',
    statusCANCELLED: '没有及时付款',
    detailStarted: '{time} 开始',
    detailPayBy: '请在 {time} 前付款',
    detailPaid: '{time} 付款',
    detailGiven: '学校在 {time} 发出',
    detailMoved: '{time} 转入',
    detailAddBy: '如果 {time} 前没加到卡上，会自动退款',
    detailAdded: '{time} 加到卡上',
    detailParked: '充值机可能已经加了这笔钱，学校办公室正在核对。',
    detailRefundedTopup: '没有及时加到卡上，钱已退回给你。',
    detailRefundedSubsidy: '没有及时加到卡上，已退回学校。',
    detailFailed: '银行拒绝了这笔付款，没有扣钱。',
    detailCancelled: '没有及时付款，没有扣钱。',
    purchaseSALE: '食堂',
    purchaseWATER: '饮用水',
    litres: '{n} 公升',
    tryAgain: '再试一次',
    loadFailed: '载入不到。',

    suspendedTitle: '{school} 在 OneCard 上已暂停',
    suspendedText: '学校暂停期间，你不能查看 {child} 的余额，也不能充值。你已经付的钱是安全的。详情请联络学校。',
    notLinkedTitle: '找不到这个孩子',
    notLinkedText: '这个孩子没有绑定在你的账号。回到“我的孩子”看看有谁。',
    noCardTitle: '{child} 还没有卡',
    noCardText: '卡由学校办公室发出。{child} 有了卡之后就可以充值。',
    lostCardTitle: '{child} 的卡已挂失',
    lostCardText: '学校办公室给 {child} 新卡之前，暂时不能充值。',
    retiredCardTitle: '{child} 的卡已停用',
    retiredCardText: '请向学校办公室询问新卡的事。',

    topupTitle: '为卡充值',
    topupFor: '给 {child}（{school}）',
    howMuch: '充多少？',
    otherAmount: '其他金额',
    otherAmountHint: '以令吉计算，例如 15 或 15.50',
    limitsKnown: '{school} 每次充值可充 {min} 至 {max}。',
    nextTitle: '接下来会怎样',
    step1: '你在银行付款。实验室里的是模拟银行，不会真的扣钱。',
    step2: '钱会在 OneCard 上等着 {child}。',
    step3: '孩子在学校的充值机拍卡，钱就会加到卡上。',
    continueToBank: '前往银行付款',
    continueToBankAmount: '前往银行付款 · {amount}',
    leaveNote: '你会离开这个页面去付款，付完会回到这里。',
    starting: '正在开始充值…',
    goingToBank: '正在打开银行页面…',
    errChooseAmount: '请选一个金额，或自己输入。',
    errAmountFormat: '请以令吉输入金额，例如 15 或 15.50。',
    errAmountZero: '金额必须多过 RM 0.00。',
    refusedTitle: '这笔充值不能进行',
    AMOUNT_OUT_OF_RANGE: '{school} 每次充值可充 {min} 至 {max}。请选这个范围里的金额。',
    DAILY_LIMIT: '{school} 每个孩子每天最多可充值 {limit}。{child} 今天已经有 {used} 的充值，所以今天最多还可以充 {remaining}。',
    DAILY_LIMIT_NONE: '{school} 每个孩子每天最多可充值 {limit}。{child} 今天已经到了上限，请明天再充值。',
    MONTHLY_LIMIT: '{school} 每个孩子每个月最多可充值 {limit}。{child} 这个月已经有 {used} 的充值，所以这个月最多还可以充 {remaining}。',
    MONTHLY_LIMIT_NONE: '{school} 每个孩子每个月最多可充值 {limit}。{child} 这个月已经到了上限，请下个月再充值。',
    limitCountsNote: '这包括每位家长的充值，也包括已经开始但还没付款、付款时间还没过的充值。',
    useAmount: '改用 {amount}',
    AMOUNT_INVALID: '请以令吉输入金额，例如 15 或 15.50。',
    CARD_NOT_ACTIVE: '{child} 现在没有可以用的卡，所以钱加不上去。请联络学校办公室。',
    NOT_LINKED: '{child} 已经没有绑定在你的账号。',
    uncertainTitle: '没有收到 OneCard 的回复',
    uncertainText: '我们没有收到回复，所以不知道充值有没有开始。请按“再试一次”：这样做是安全的，你不会付两次钱。',
    downTitle: 'OneCard 服务器关着',
    downText: '充值没有开始。等服务器重新开启后，按“再试一次”：你不会付两次钱。',
    CROSS_ORIGIN: 'OneCard 拒绝了一个不是从这个页面发出的请求。请重新载入页面再试。',
    genericError: '出了点问题（{code}）。请再试一次。',

    resultTitle: '你的充值',
    resultPaidTitle: '已收到付款',
    resultPaidText: '{amount} 正在 {school} 等着 {child}。孩子在学校的充值机拍卡时，钱就会加到卡上。',
    reference: '参考编号 {ref}',
    resultPaidAddBy: '如果 {time} 前没加到卡上，钱会自动退回给你。',
    resultAddedTitle: '已付款，也已加到卡上',
    resultAddedText: '{amount} 已经在 {child} 的卡上。',
    resultFailedTitle: '付款被拒',
    resultFailedText: '银行拒绝了 {amount} 的付款，所以没有扣钱，也没有钱在等待。你可以再试一次。',
    resultCreatedTitle: '还没付款',
    resultCreatedText: '你还没付完给 {child} 的 {amount}。付款链接在 {time} 之前有效。',
    resultCancelledTitle: '付款时间已过',
    resultCancelledText: '给 {child} 的 {amount} 没有及时付款，所以已取消。没有扣钱。',
    resultRefundedTitle: '已退款',
    resultRefundedText: '{amount} 没有及时加到卡上，所以已退回给你。',
    resultParkedTitle: '已收到付款，正在核对',
    resultParkedText: '充值机可能已经加了 {amount}，学校办公室正在核对。',
    resultMissingTitle: '找不到这笔付款',
    resultMissingText: '它可能属于另一位家长，或实验室已经重置。每个孩子的页面都列出所有充值。',
    seeChild: '查看 {child} 的卡',
    startNewTopup: '重新充值',
    backHome: '回到我的孩子',
    later: '先不要',
  },
};
