// Every string the operator console shows, in English and Chinese (中文).

const en = {
  'app.skip': 'Skip to content',
  'app.home': 'OneCard Lab home',
  'app.name': 'Operator console',
  'app.ribbon': 'LAB · not real money',
  'app.signOut': 'Sign out',
  'app.waiting': 'Waiting for the OneCard server…',
  'band.kicker': 'SaaS operator',
  'band.title': 'OneCard platform',
  'band.text': "One server, many schools. You see every tenant; each school's staff see only their own school.",
  'band.who': 'OneCard platform operator',

  'signin.title': 'Operator console: sign in',
  'signin.lede': 'Lab only: there is no password. The lab has one platform operator account.',
  'signin.what':
    "The operator runs the OneCard platform for every school: onboards new schools, watches their health and can suspend one. The operator is not on any school's staff and never works inside a school's office.",
  'signin.button': 'Sign in as the platform operator',
  'signin.ended': 'Your session ended (the lab may have restarted). Sign in again.',

  'hl.title': 'Platform health',
  'hl.text': 'The shared cloud server every school uses.',
  'hl.server': 'Cloud server',
  'hl.serverUp': 'Running',
  'hl.serverDown': 'Unreachable',
  'hl.serverSub': 'Broker, platform and database on one virtual server',
  'hl.serverDownSub': 'Switch it back on in the lab console',
  'hl.link': 'Platform link to the broker',
  'hl.linkUp': 'Connected',
  'hl.linkDown': 'Not connected',
  'hl.linkUnknown': 'Unknown',
  'hl.broker': 'Broker connections',
  'hl.brokerSub': '{machines} machines · {other} other (the platform itself and read-only viewers)',
  'hl.brokerDown': 'The broker is not running',
  'hl.schools': 'Schools',
  'hl.schoolsSub': '{active} active · {suspended} suspended',

  'tn.title': 'Schools on the platform',
  'tn.text': "Every tenant, each with its own students, machines, money and differences. A school's staff never see another school.",
  'tn.school': 'School',
  'tn.status': 'Status',
  'tn.members': 'Students & staff',
  'tn.machines': 'Machines online',
  'tn.sales': 'Sales today',
  'tn.waiting': 'Waiting at kiosks',
  'tn.differences': 'Open differences',
  'tn.sinceAt': 'since {at}',
  'tn.cardsN': '{n} cards',
  'tn.brokerN': '{n} connected to the broker',
  'tn.action': 'Action',
  'tn.empty': 'No schools yet. Onboard the first one below.',
  'tn.machinesValue': '{online} of {total}',
  'tn.suspend': 'Suspend…',
  'tn.reactivate': 'Reactivate…',
  'tn.suspendTitle': 'Suspend {school}?',
  'tn.suspendBody1': 'Its machines are disconnected from the broker at once, and anything they send is refused.',
  'tn.suspendBody2': 'Its staff cannot use the school office, and its parents cannot see their children there or top up.',
  'tn.suspendBody3': 'Nothing is deleted, and every other school carries on untouched. You can reactivate it at any time.',
  'tn.suspendConfirm': 'Suspend school',
  'tn.suspended': '{school} is suspended. Machine connections closed: {n}.',
  'tn.reactivateTitle': 'Reactivate {school}?',
  'tn.reactivateBody':
    "Its machines may connect again and send the records they kept, and its staff and parents can use OneCard again. The platform sends the school's current prices, settings and block list to its machines.",
  'tn.reactivateConfirm': 'Reactivate school',
  'tn.reactivated': '{school} is active again.',
  'tn.sent': 'Its current prices, settings and block list were sent to its machines.',
  'tn.notSent': 'Its settings go out when the platform reaches the broker again.',
  'tn.refresh': 'Refresh',
  'school.ACTIVE': 'Active',
  'school.SUSPENDED': 'Suspended',

  'on.title': 'Onboard a new school',
  'on.text':
    'Creates the school with its staff accounts, the default price list and settings, an empty block list, its machines and, if you like, fictional demo students with new cards. The lab builds the new machines and cards straight away.',
  'on.name': 'School name',
  'on.nameHint': 'e.g. SK Taman Melati',
  'on.code': 'School code',
  'on.codeHint': 'Lower-case letters, digits and dashes, e.g. sk-taman-melati. Machine logins and message topics use it, so it cannot change later.',
  'on.staff': 'Staff',
  'on.staffText': "The first people who can sign in to this school's office.",
  'on.staffName': 'Name',
  'on.role': 'Role',
  'on.addStaff': 'Add a staff member',
  'on.remove': 'Remove',
  'on.removeStaff': 'Remove staff member {n}',
  'on.machines': 'Machines to install',
  'on.machinesText': 'Each machine gets its own secret, shown once after onboarding.',
  'on.machineCode': 'Machine code',
  'on.machineType': 'Type',
  'on.location': 'Location (optional)',
  'on.addMachine': 'Add a machine',
  'on.removeMachine': 'Remove machine {n}',
  'on.demo': 'Demo students',
  'on.demoHint': '0 to 200 fictional students, each with a new card holding RM 0.00.',
  'on.submit': 'Onboard school',
  'on.example': 'Fill in an example',
  'on.clear': 'Clear the form',
  'on.fixFirst': 'Fix the marked fields first.',
  'on.working': 'Onboarding…',
  'on.err.name': 'Enter a name of 1 to 100 characters.',
  'on.err.code': 'Use lower-case letters, digits and dashes (up to 32), starting and ending with a letter or digit.',
  'on.err.codeTaken': 'A school with this code is already on the platform.',
  'on.err.staffName': 'Enter a name of 1 to 100 characters.',
  'on.err.machineCode': 'Use capital letters, digits and dashes (up to 32), starting and ending with a letter or digit.',
  'on.err.machineTwice': 'Two machines have this code.',
  'on.err.location': 'At most 80 characters.',
  'on.err.demo': 'Enter a whole number from 0 to 200.',
  'on.doneTitle': '{school} is on the platform',
  'on.doneCode': 'School code {code}',
  'on.doneStaff': 'Staff who can sign in to the school office now:',
  'on.openOffice': 'Open the school office',
  'on.doneMachines': 'Machines and their secrets',
  'on.secretsWarn':
    'These secrets are shown only once. Copy them now: each machine signs its messages with its secret, so anyone who has one can pretend to be that machine. In the lab the virtual machines already have theirs.',
  'on.hideSecrets': 'I have copied them, hide the secrets',
  'on.secretsHidden': 'Secrets hidden. They cannot be shown again.',
  'on.secret': 'Secret',
  'on.doneMembers': '{n} demo students with new cards (RM 0.00 on each).',
  'on.doneNoMembers': 'No demo students.',
  'on.donePublished': 'The default prices and settings were sent to the new machines.',
  'on.doneNotPublished': 'The new machines get their prices and settings when they first connect.',
  'on.openLab': "See the new school's site in the lab console",
  'on.noMachines': 'No machines yet: the school office can register them later.',
  'on.noStaff': 'No staff accounts.',

  'role.OFFICE': 'Office',
  'role.FINANCE': 'Finance',
  'role.ADMIN': 'Admin',
  'roleText.OFFICE': 'students, cards, parents, machines, prices',
  'roleText.FINANCE': 'top-ups, subsidies, books, reconciliation',
  'roleText.ADMIN': 'everything in the school',
  'devType.CANTEEN': 'Canteen reader',
  'devType.WATER': 'Water machine',
  'devType.KIOSK': 'Top-up kiosk',

  'err.SCHOOL_CODE_INVALID': 'The school code must be lower-case letters, digits and dashes, e.g. sk-taman-melati.',
  'err.SCHOOL_CODE_TAKEN': 'A school with this code is already on the platform.',
  'err.NAME_INVALID': 'Every name must be 1 to 100 characters.',
  'err.STAFF_ROLE_INVALID': 'Choose Office, Finance or Admin for every staff member.',
  'err.TENANT_INVALID': 'The school could not be created as described: check the staff, machines and number of demo students.',
  'err.DEVICE_CODE_INVALID': 'Machine codes must be capital letters, digits and dashes, e.g. CANTEEN-01.',
  'err.DEVICE_TYPE_INVALID': 'Choose a type for every machine.',
  'err.DEVICE_CODE_TAKEN': 'Two machines have the same code.',
  'err.LOCATION_INVALID': 'A location can be at most 80 characters.',
  'err.SCHOOL_NOT_FOUND': 'This school is not on the platform any more.',
  'err.SCHOOL_STATUS_INVALID': 'Choose active or suspended.',
};

const zh = {
  'app.skip': '跳到内容',
  'app.home': 'OneCard 实验室首页',
  'app.name': '平台运营后台',
  'app.ribbon': '实验室 · 不是真钱',
  'app.signOut': '退出登录',
  'app.waiting': '正在等待 OneCard 服务器…',
  'band.kicker': 'SaaS 运营方',
  'band.title': 'OneCard 平台',
  'band.text': '一台服务器，很多学校。你看得到每个租户；每所学校的职员只看得到自己的学校。',
  'band.who': 'OneCard 平台运营方',

  'signin.title': '平台运营后台：登录',
  'signin.lede': '仅限实验室：没有密码。实验室只有一个平台运营方账号。',
  'signin.what': '运营方为所有学校运行 OneCard 平台：开通新学校、查看各校状况，也可以停用某所学校。运营方不属于任何学校的职员，也从不在学校后台里工作。',
  'signin.button': '以平台运营方身份登录',
  'signin.ended': '你的登录已结束（实验室可能重启了）。请重新登录。',

  'hl.title': '平台状况',
  'hl.text': '所有学校共用的云端服务器。',
  'hl.server': '云端服务器',
  'hl.serverUp': '运行中',
  'hl.serverDown': '连不上',
  'hl.serverSub': 'broker、平台和数据库在同一台虚拟服务器上',
  'hl.serverDownSub': '请在实验室控制台把它重新打开',
  'hl.link': '平台和 broker 的连线',
  'hl.linkUp': '已连线',
  'hl.linkDown': '没有连线',
  'hl.linkUnknown': '不明',
  'hl.broker': 'broker 连线数',
  'hl.brokerSub': '{machines} 台机器 · {other} 个其他（平台本身和只读查看者）',
  'hl.brokerDown': 'broker 没有在运行',
  'hl.schools': '学校',
  'hl.schoolsSub': '{active} 所正常 · {suspended} 所已停用',

  'tn.title': '平台上的学校',
  'tn.text': '每个租户都有自己的学生、机器、钱和差异。学校职员永远看不到别的学校。',
  'tn.school': '学校',
  'tn.status': '状态',
  'tn.members': '学生和职员',
  'tn.machines': '在线机器',
  'tn.sales': '今日销售',
  'tn.waiting': '在充值机等着加值',
  'tn.differences': '未处理的差异',
  'tn.sinceAt': '开通于 {at}',
  'tn.cardsN': '{n} 张卡',
  'tn.brokerN': '{n} 台连着 broker',
  'tn.action': '操作',
  'tn.empty': '还没有学校。请在下面开通第一所。',
  'tn.machinesValue': '{online} / {total}',
  'tn.suspend': '停用…',
  'tn.reactivate': '恢复…',
  'tn.suspendTitle': '停用 {school}？',
  'tn.suspendBody1': '它的机器会立刻和 broker 断开，发来的任何东西都会被拒绝。',
  'tn.suspendBody2': '它的职员不能使用学校后台，家长也不能在那里看到孩子或充值。',
  'tn.suspendBody3': '没有任何资料会被删除，其他学校完全不受影响。你随时可以恢复它。',
  'tn.suspendConfirm': '停用学校',
  'tn.suspended': '{school} 已停用。已断开的机器连线：{n}。',
  'tn.reactivateTitle': '恢复 {school}？',
  'tn.reactivateBody': '它的机器可以重新连线，并补传保存的记录；职员和家长可以再次使用 OneCard。平台会把学校目前的价格、设置和黑名单发给它的机器。',
  'tn.reactivateConfirm': '恢复学校',
  'tn.reactivated': '{school} 已恢复正常。',
  'tn.sent': '学校目前的价格、设置和黑名单已发给它的机器。',
  'tn.notSent': '平台重新连上 broker 后会发出学校的设置。',
  'tn.refresh': '刷新',
  'school.ACTIVE': '正常',
  'school.SUSPENDED': '已停用',

  'on.title': '开通新学校',
  'on.text': '建立学校、职员账号、默认价格表和设置、空的黑名单、学校的机器，也可以加上虚构的示范学生和新卡。实验室会立刻建好新机器和新卡。',
  'on.name': '学校名称',
  'on.nameHint': '例如 SK Taman Melati',
  'on.code': '学校代码',
  'on.codeHint': '小写字母、数字和横线，例如 sk-taman-melati。机器登录和消息主题都用它，以后不能更改。',
  'on.staff': '职员',
  'on.staffText': '第一批可以登录这所学校后台的人。',
  'on.staffName': '名字',
  'on.role': '角色',
  'on.addStaff': '新增职员',
  'on.remove': '移除',
  'on.removeStaff': '移除第 {n} 位职员',
  'on.machines': '要安装的机器',
  'on.machinesText': '每台机器都有自己的密钥，开通后只显示一次。',
  'on.machineCode': '机器编号',
  'on.machineType': '类型',
  'on.location': '位置（可不填）',
  'on.addMachine': '新增机器',
  'on.removeMachine': '移除第 {n} 台机器',
  'on.demo': '示范学生',
  'on.demoHint': '0 到 200 位虚构学生，每人一张起始余额 RM 0.00 的新卡。',
  'on.submit': '开通学校',
  'on.example': '填入示例',
  'on.clear': '清空表格',
  'on.fixFirst': '请先修正标出的栏位。',
  'on.working': '开通中…',
  'on.err.name': '请输入 1 到 100 个字的名称。',
  'on.err.code': '请用小写字母、数字和横线（最多 32 个），开头和结尾必须是字母或数字。',
  'on.err.codeTaken': '平台上已经有这个代码的学校。',
  'on.err.staffName': '请输入 1 到 100 个字的名字。',
  'on.err.machineCode': '请用大写字母、数字和横线（最多 32 个），开头和结尾必须是字母或数字。',
  'on.err.machineTwice': '有两台机器用了这个编号。',
  'on.err.location': '最多 80 个字。',
  'on.err.demo': '请输入 0 到 200 的整数。',
  'on.doneTitle': '{school} 已在平台上开通',
  'on.doneCode': '学校代码 {code}',
  'on.doneStaff': '现在可以登录学校后台的职员：',
  'on.openOffice': '打开学校后台',
  'on.doneMachines': '机器和它们的密钥',
  'on.secretsWarn': '这些密钥只显示这一次。请现在复制：每台机器都用自己的密钥为消息签名，谁拿到就能冒充那台机器。在实验室里，虚拟机器已经有自己的密钥。',
  'on.hideSecrets': '我已复制，隐藏密钥',
  'on.secretsHidden': '密钥已隐藏，无法再次显示。',
  'on.secret': '密钥',
  'on.doneMembers': '{n} 位示范学生，每人一张新卡（卡上 RM 0.00）。',
  'on.doneNoMembers': '没有示范学生。',
  'on.donePublished': '默认价格和设置已发给新机器。',
  'on.doneNotPublished': '新机器第一次连线时会收到价格和设置。',
  'on.openLab': '在实验室控制台查看新学校',
  'on.noMachines': '还没有机器：学校后台以后可以登记。',
  'on.noStaff': '没有职员账号。',

  'role.OFFICE': '办公室',
  'role.FINANCE': '财务',
  'role.ADMIN': '管理员',
  'roleText.OFFICE': '学生、卡、家长、机器、价格',
  'roleText.FINANCE': '充值、补助、账本、对账',
  'roleText.ADMIN': '学校里的一切',
  'devType.CANTEEN': '食堂刷卡机',
  'devType.WATER': '饮水机',
  'devType.KIOSK': '充值机',

  'err.SCHOOL_CODE_INVALID': '学校代码必须是小写字母、数字和横线，例如 sk-taman-melati。',
  'err.SCHOOL_CODE_TAKEN': '平台上已经有这个代码的学校。',
  'err.NAME_INVALID': '每个名称都必须是 1 到 100 个字。',
  'err.STAFF_ROLE_INVALID': '请为每位职员选择办公室、财务或管理员。',
  'err.TENANT_INVALID': '无法按所填资料建立学校：请检查职员、机器和示范学生人数。',
  'err.DEVICE_CODE_INVALID': '机器编号必须是大写字母、数字和横线，例如 CANTEEN-01。',
  'err.DEVICE_TYPE_INVALID': '请为每台机器选择类型。',
  'err.DEVICE_CODE_TAKEN': '有两台机器用了同一个编号。',
  'err.LOCATION_INVALID': '位置最多 80 个字。',
  'err.SCHOOL_NOT_FOUND': '这所学校已不在平台上。',
  'err.SCHOOL_STATUS_INVALID': '请选择正常或停用。',
};

export const STRINGS = { en, zh };
