import { test, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { createTestCtx, eventsOf } from '../helpers.js';
import { createSchools } from '../../src/platform/schools.js';
import { createDevices } from '../../src/platform/devices.js';
import { createConfigs, DEFAULT_PRICES, DEFAULT_SETTINGS } from '../../src/platform/configs.js';
import { createLedger } from '../../src/platform/ledger.js';
import { createDifferences } from '../../src/platform/differences.js';
import { createTopups } from '../../src/platform/topups.js';
import { createSettlement } from '../../src/platform/settlement.js';
import { createReconcile } from '../../src/platform/reconcile.js';
import { createIntake, MAX_MESSAGE_BYTES } from '../../src/platform/intake.js';
import { signEnvelope } from '../../src/shared/crypto.js';
import { buildEnvelope, deviceTxnNo, topicFor, UP_TYPES } from '../../src/shared/protocol.js';
import { waterChargeSen } from '../../src/shared/money.js';
import { newUuid } from '../../src/shared/ids.js';
import { MINUTE, toIso } from '../../src/shared/time.js';

// Every school, person and machine here is fictional; card keys and device secrets are
// generated by the services for each test.

const PRICE = Object.fromEntries(DEFAULT_PRICES.items.map((i) => [i.code, i.priceSen]));
const { perLitreSen: PER_LITRE, minChargeSen: MIN_CHARGE } = DEFAULT_PRICES.water;
const MACHINES_A = [['CANTEEN-01', 'CANTEEN'], ['CANTEEN-02', 'CANTEEN'], ['WATER-01', 'WATER'], ['KIOSK-01', 'KIOSK']];
const MACHINES_B = [['CANTEEN-01', 'CANTEEN'], ['KIOSK-01', 'KIOSK']];

let t; // this test's world

function addSchool(svc, code, name, people, machines) {
  const school = svc.schools.createSchool({ code, name });
  const m = {};
  for (const [deviceCode, type] of machines) {
    const { device, secret } = svc.devices.registerDevice({ schoolId: school.id, code: deviceCode, type, actor: 'test' });
    m[deviceCode] = { id: device.id, code: deviceCode, type, secret, school: { id: school.id, code }, seq: 0 };
  }
  const members = {};
  for (const [key, p] of Object.entries(people)) {
    const member = svc.schools.addMember({ schoolId: school.id, memberNo: p.no, name: p.name });
    const card = svc.schools.issueCard({ schoolId: school.id, memberId: member.id, uid: p.uid, actor: 'test' });
    members[key] = { id: member.id, uid: p.uid, cardId: card.id, digest: card.digest };
  }
  svc.configs.publish({ schoolId: school.id, kind: 'prices', content: DEFAULT_PRICES, actor: 'test' });
  svc.configs.publish({ schoolId: school.id, kind: 'settings', content: DEFAULT_SETTINGS, actor: 'test' });
  svc.configs.ensureBlockList({ schoolId: school.id, actor: 'test' });
  return { id: school.id, code, m, members };
}

function setup() {
  const ctx = createTestCtx();
  const schools = createSchools(ctx);
  const devices = createDevices(ctx);
  const configs = createConfigs(ctx, { schools });
  const ledger = createLedger(ctx);
  const differences = createDifferences(ctx);
  const topups = createTopups(ctx, { ledger, schools, differences });
  const settlement = createSettlement(ctx, { ledger, schools, configs, devices, differences });
  const reconcile = createReconcile(ctx, { ledger, schools, configs, devices, differences });
  const intake = createIntake(ctx, { schools, devices, configs, settlement, reconcile });
  const svc = { ctx, schools, devices, configs, ledger, differences, topups, settlement, reconcile, intake };
  const a = addSchool(svc, 'smk-alpha', 'SMK Alpha (fictional)', {
    aina: { no: 'A001', name: 'Aina Alpha', uid: '04A1B2C3D4E5F6' },
    badrul: { no: 'A002', name: 'Badrul Alpha', uid: '04B7C8D9EAFB01' },
  }, MACHINES_A);
  // Same card UID as Aina's on purpose: in another school it is another card, with another digest.
  const b = addSchool(svc, 'smk-beta', 'SMK Beta (fictional)', { chong: { no: 'B001', name: 'Chong Beta', uid: '04A1B2C3D4E5F6' } }, MACHINES_B);
  return { ...svc, a, b };
}

beforeEach(() => {
  t = setup();
});
afterEach(() => {
  t.ctx.db.close();
});

// ---- messages ------------------------------------------------------------------------------

/** A signed envelope from machine `m`; its seq counts up unless given. */
function envelope(m, type, body, { seq, txn, at, id, school, device, v } = {}) {
  const env = buildEnvelope({ school: school ?? m.school.code, device: device ?? m.code, seq: seq ?? ++m.seq, at: at ?? t.ctx.clock.iso(), type, txn, body });
  if (id !== undefined) env.id = id;
  if (v !== undefined) env.v = v;
  return signEnvelope(m.secret, env);
}

const topicOf = (m, channel) => topicFor(m.school.code, m.code, channel);
/** Deliver an envelope on machine m's own topic for its type (or `channel`). */
const deliver = (m, env, channel = UP_TYPES[env.type] ?? 'records') => t.intake.handle(topicOf(m, channel), JSON.stringify(env));
const send = (m, type, body, opts = {}) => deliver(m, envelope(m, type, body, opts), opts.channel);

const heartbeatBody = (versions = { prices: 1, settings: 1, blocklist: 1 }) => ({ fw: '1.0.0-lab', health: 'OK', listVersions: versions, journalUnsent: 0 });

// ---- cards and records -----------------------------------------------------------------------

let kioskTxns = 0;
/** Money onto a member's card through the real flow: a school subsidy, then the kiosk adds it. */
function fund(school, key, amountSen) {
  const member = school.members[key];
  const order = t.topups.grantSubsidy({ schoolId: school.id, memberId: member.id, amountSen, actor: 'test', note: 'start' });
  t.topups.kioskConfirm({
    schoolId: school.id,
    kioskDeviceId: school.m['KIOSK-01'].id,
    kioskDeviceCode: 'KIOSK-01',
    orderId: order.id,
    result: 'ADDED',
    amountSen,
    cardDigest: member.digest,
    balanceAfterOnCardSen: amountSen,
    kioskTxn: deviceTxnNo('KIOSK-01', ++kioskTxns),
  });
  // the chip: the kiosk's credit raised its counter too
  return { digest: member.digest, last4: member.uid.slice(-4), cardSeq: 1, balanceSen: amountSen };
}

function debit(card, fields, amountSen) {
  card.cardSeq += 1;
  const balanceBeforeSen = card.balanceSen;
  card.balanceSen -= amountSen;
  return {
    priceVersion: 1,
    listVersion: 1,
    at: t.ctx.clock.iso(),
    currency: 'MYR',
    ...fields,
    card: card.digest,
    last4: card.last4,
    cardSeq: card.cardSeq,
    amountSen,
    balanceBeforeSen,
    balanceAfterSen: card.balanceSen,
  };
}

function sale(card, { origin = 'CANTEEN-01', n, items = [['NASI-LEMAK', 1]] } = {}) {
  const lines = items.map(([code, qty]) => ({ code, qty, priceSen: PRICE[code] }));
  return debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'SALE', items: lines }, lines.reduce((s, l) => s + l.qty * l.priceSen, 0));
}

function water(card, { origin = 'WATER-01', n, ml }) {
  return debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'WATER', ml, perLitreSen: PER_LITRE }, waterChargeSen(ml, PER_LITRE, MIN_CHARGE));
}

// ---- looking at the platform ---------------------------------------------------------------

const wallet = (school, key) => t.ledger.balance(school.id, 'STUDENT_WALLET', school.members[key].id);
const purchases = (school) => t.settlement.listPurchases(school.id);
const lastSeq = (m) => t.devices.getDevice(m.school.id, m.id).lastSeq;
const inbound = (school) => t.ctx.db.get('SELECT count(*) AS n FROM inbound_message WHERE school_id = ?', school.id).n;
const logOf = (m) => t.devices.listLog(m.school.id, { deviceId: m.id });
const refusedEvents = () => eventsOf(t.ctx, 'intake.refused');

function assertBooks(school) {
  const tb = t.ledger.trialBalance(school.id);
  assert.equal(tb.balanced, true, `the books of ${school.code} do not balance`);
  const posted = t.ctx.db.get("SELECT coalesce(sum(amount_sen), 0) AS s FROM purchase WHERE school_id = ? AND status = 'POSTED'", school.id).s;
  assert.equal(t.ledger.balance(school.id, 'SALES_PAYABLE'), posted);
}

/** A refusal: the answer, nothing recorded, the seq untouched, a WARN line in the machine's log and an event. */
function assertRefused(res, code, m, { before } = {}) {
  assert.equal(res.result, 'REFUSED', JSON.stringify(res));
  assert.equal(res.code, code, JSON.stringify(res));
  assert.equal(typeof res.detail.message, 'string');
  if (m) {
    const [entry] = logOf(m);
    assert.equal(entry.code, code);
    assert.equal(entry.level, 'WARN');
    assert.equal(entry.deviceCode, m.code);
    if (before) {
      assert.equal(lastSeq(m), before.seq, 'a refused message must not use up its seq');
      assert.equal(inbound(m.school), before.inbound, 'a refused message must not be recorded');
    }
  }
  const event = refusedEvents().at(-1);
  assert.equal(event.data.code, code);
}

const snapshotOf = (m) => ({ seq: lastSeq(m), inbound: inbound(m.school) });

// ---- tests ------------------------------------------------------------------------------------

describe('createIntake', () => {
  test('needs the services it hands messages to', () => {
    const { devices, configs, settlement, reconcile } = t;
    assert.throws(() => createIntake(t.ctx, {}), TypeError);
    assert.throws(() => createIntake(t.ctx, { devices, configs, settlement }), /reconcile/);
    assert.throws(() => createIntake(t.ctx, { configs, settlement, reconcile }), /devices/);
    assert.equal(typeof createIntake(t.ctx, { devices, configs, settlement, reconcile }).handle, 'function');
  });
});

describe('refusals, one step of the pipeline at a time', () => {
  test('1. TOPIC_INVALID: not a records or status topic of a device; filed under no school', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const env = JSON.stringify(envelope(canteen, 'device.heartbeat', heartbeatBody()));
    const topics = [
      'lab/v1/smk-alpha/CANTEEN-01/commands/prices', // commands go the other way
      'lab/v1/smk-alpha/CANTEEN-01',
      'lab/v1/smk-alpha/CANTEEN-01/records/extra',
      'lab/v2/smk-alpha/CANTEEN-01/records',
      'lab/v1/SMK-ALPHA/CANTEEN-01/records',
      'lab/v1/smk-alpha/canteen-01/status',
      '',
      null,
      42,
    ];
    for (const topic of topics) {
      const res = t.intake.handle(topic, env);
      assert.equal(res.result, 'REFUSED', String(topic));
      assert.equal(res.code, 'TOPIC_INVALID', String(topic));
    }
    // an unidentified sender's refusals go to the lab console's list of unknown senders
    const unknown = t.devices.listLog(null);
    assert.equal(unknown.length, topics.length);
    assert.ok(unknown.every((e) => e.code === 'TOPIC_INVALID' && e.level === 'WARN' && e.schoolId === null && e.deviceId === null));
    assert.equal(unknown.at(-1).detail.topic, 'lab/v1/smk-alpha/CANTEEN-01/commands/prices');
    assert.deepEqual(t.devices.listLog(t.a.id), []);
    assert.ok(refusedEvents().every((e) => e.school === null && e.data.code === 'TOPIC_INVALID'));
    assert.equal(lastSeq(canteen), 0);
  });

  test('2. UNKNOWN_DEVICE: a school or machine the platform does not know', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const env = JSON.stringify(envelope(canteen, 'device.heartbeat', heartbeatBody()));
    for (const topic of ['lab/v1/smk-gamma/CANTEEN-01/status', 'lab/v1/smk-alpha/CANTEEN-09/status', 'lab/v1/smk-beta/WATER-01/status']) {
      const res = t.intake.handle(topic, env);
      assert.equal(res.code, 'UNKNOWN_DEVICE', topic);
      assert.equal(res.type, undefined, 'the payload is not read for an unknown sender');
    }
    assert.deepEqual(t.devices.listLog(null).map((e) => e.code), ['UNKNOWN_DEVICE', 'UNKNOWN_DEVICE', 'UNKNOWN_DEVICE']);
    assert.deepEqual(t.devices.listLog(null)[0].detail, { school: 'smk-beta', device: 'WATER-01' });
    // never filed in a school's own log: the sender is not one of its machines
    assert.deepEqual(t.devices.listLog(t.a.id), []);
    assert.deepEqual(t.devices.listLog(t.b.id), []);
    // the lab console files the event under the school the topic names, as the broker does
    assert.deepEqual(refusedEvents().map((e) => [e.school, e.data]), [
      ['smk-gamma', { device: 'CANTEEN-01', type: null, code: 'UNKNOWN_DEVICE' }],
      ['smk-alpha', { device: 'CANTEEN-09', type: null, code: 'UNKNOWN_DEVICE' }],
      ['smk-beta', { device: 'WATER-01', type: null, code: 'UNKNOWN_DEVICE' }],
    ]);
  });

  test('3. ENVELOPE_INVALID: not JSON, not text, or too large', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const topic = topicOf(canteen, 'status');
    const before = snapshotOf(canteen);
    for (const payload of ['not json', '', '{"v":"1.0",', Buffer.from([0xff, 0xfe, 0x00]), null, undefined, 42, { v: '1.0' }]) {
      const res = t.intake.handle(topic, payload);
      assertRefused(res, 'ENVELOPE_INVALID', canteen, { before });
    }
    const huge = JSON.stringify({ ...envelope(canteen, 'device.heartbeat', heartbeatBody()), padding: 'x'.repeat(MAX_MESSAGE_BYTES) });
    assertRefused(t.intake.handle(topic, huge), 'ENVELOPE_INVALID', canteen, { before });
    assert.match(logOf(canteen)[0].message, /larger than/);
    // the refusals are filed under the machine and its school
    assert.ok(refusedEvents().every((e) => e.school === 'smk-alpha' && e.data.device === 'CANTEEN-01'));
  });

  test('3. ENVELOPE_INVALID / VERSION_UNSUPPORTED / UNKNOWN_TYPE: the shape of the envelope', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const good = envelope(canteen, 'device.heartbeat', heartbeatBody(), { seq: 1 });
    const before = snapshotOf(canteen);
    const cases = [
      [[1, 2, 3], 'ENVELOPE_INVALID'],
      [{ ...good, v: 1 }, 'ENVELOPE_INVALID'],
      [{ ...good, id: 'short' }, 'ENVELOPE_INVALID'],
      [{ ...good, seq: 0 }, 'ENVELOPE_INVALID'],
      [{ ...good, seq: 1.5 }, 'ENVELOPE_INVALID'],
      [{ ...good, at: '2026-02-30T10:00:00Z' }, 'ENVELOPE_INVALID'],
      [{ ...good, body: [] }, 'ENVELOPE_INVALID'],
      [{ ...good, txn: 7 }, 'ENVELOPE_INVALID'],
      [{ ...good, sig: undefined }, 'ENVELOPE_INVALID'],
      [{ ...good, v: '2.0' }, 'VERSION_UNSUPPORTED'],
      [{ ...good, type: 'sale.voided' }, 'UNKNOWN_TYPE'],
      // inherited object names are not message types either
      [{ ...good, type: 'toString' }, 'UNKNOWN_TYPE'],
      [{ ...good, type: 'constructor' }, 'UNKNOWN_TYPE'],
    ];
    for (const [payload, code] of cases) {
      const res = t.intake.handle(topicOf(canteen, 'status'), JSON.stringify(payload));
      assertRefused(res, code, canteen, { before });
    }
    // the type, when readable, travels with the refusal
    assert.equal(t.intake.handle(topicOf(canteen, 'status'), JSON.stringify({ ...good, type: 'sale.voided' })).type, 'sale.voided');
  });

  test('4. TOPIC_MISMATCH: the envelope must name the topic\'s school and machine, on the right channel', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const before = snapshotOf(canteen);
    const sale1 = { record: sale(fund(t.a, 'aina', 1000), { n: 1 }) };
    const cases = [
      [envelope(canteen, 'device.heartbeat', heartbeatBody(), { school: 'smk-beta' }), 'status', /names smk-beta\/CANTEEN-01/],
      [envelope(canteen, 'device.heartbeat', heartbeatBody(), { device: 'CANTEEN-02' }), 'status', /names smk-alpha\/CANTEEN-02/],
      [envelope(canteen, 'device.heartbeat', heartbeatBody()), 'records', /belongs on the status topic/],
      [envelope(canteen, 'sale.recorded', sale1), 'status', /belongs on the records topic/],
      [envelope(canteen, 'config.prices', { version: 9 }), 'records', /not a message a machine sends/],
    ];
    for (const [env, channel, message] of cases) {
      const res = deliver(canteen, env, channel);
      assertRefused(res, 'TOPIC_MISMATCH', canteen, { before: { ...before, inbound: inbound(t.a) } });
      assert.match(res.detail.message, message);
    }
    assert.equal(lastSeq(canteen), 0);
    assert.deepEqual(purchases(t.a), []);
  });

  test('5. SIGNATURE_INVALID: signed with this machine\'s own secret, and nothing changed since', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const other = t.a.m['CANTEEN-02'];
    const sameCodeOtherSchool = t.b.m['CANTEEN-01'];
    const before = snapshotOf(canteen);
    const card = fund(t.a, 'aina', 1000);
    const env = envelope(canteen, 'sale.recorded', { record: sale(card, { n: 1 }) });
    const cases = [
      { ...env, body: { record: { ...env.body.record, amountSen: 1 } } }, // changed after signing
      { ...env, seq: env.seq + 1 },
      { ...env, sig: `${env.sig.slice(0, -2)}AA` },
      signEnvelope(other.secret, { ...env, sig: undefined }), // another machine of the school
      signEnvelope(sameCodeOtherSchool.secret, { ...env, sig: undefined }), // the same code in another school
    ];
    for (const forged of cases) assertRefused(deliver(canteen, forged), 'SIGNATURE_INVALID', canteen, { before });
    assert.deepEqual(purchases(t.a), []);
    assert.equal(wallet(t.a, 'aina'), 1000);
  });

  test('6. DUPLICATE: the same message again changes nothing', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 1000);
    const env = envelope(canteen, 'sale.recorded', { record: sale(card, { n: 1 }) }, { txn: 'CANTEEN-01-000001' });
    const first = deliver(canteen, env);
    assert.equal(first.result, 'ACCEPTED');
    const again = deliver(canteen, env);
    assert.deepEqual(again, {
      result: 'DUPLICATE',
      type: 'sale.recorded',
      detail: { messageId: env.id, firstReceivedAt: t.ctx.clock.now(), firstResult: 'ACCEPTED' },
    });
    // not a refusal: no log line, one purchase, one posting
    assert.deepEqual(logOf(canteen), []);
    assert.equal(purchases(t.a).length, 1);
    assert.equal(wallet(t.a, 'aina'), 1000 - PRICE['NASI-LEMAK']);
    assert.deepEqual(eventsOf(t.ctx, 'intake.duplicate').map((e) => [e.school, e.data]), [['smk-alpha', { device: 'CANTEEN-01', type: 'sale.recorded' }]]);
    // a duplicate is found before the gates: the machine is not told off for repeating itself
    t.schools.setSchoolStatus(t.a.id, 'SUSPENDED', 'test');
    assert.equal(deliver(canteen, env).result, 'DUPLICATE');
    assertBooks(t.a);
  });

  test('7. SEQUENCE_ROLLBACK: a new message must carry a higher seq', () => {
    const canteen = t.a.m['CANTEEN-01'];
    assert.equal(send(canteen, 'device.heartbeat', heartbeatBody(), { seq: 5 }).result, 'ACCEPTED');
    const before = snapshotOf(canteen);
    for (const seq of [5, 4, 1]) {
      const res = send(canteen, 'device.heartbeat', heartbeatBody(), { seq });
      assertRefused(res, 'SEQUENCE_ROLLBACK', canteen, { before });
      assert.deepEqual([res.detail.seq, res.detail.lastSeq], [seq, 5]);
    }
    assert.match(logOf(canteen)[0].message, /seq 1 is not higher than 5/);
    assert.equal(logOf(canteen)[0].detail.seq, 1);
    assert.equal(send(canteen, 'device.heartbeat', heartbeatBody(), { seq: 6 }).result, 'ACCEPTED');
    assert.equal(lastSeq(canteen), 6);
  });

  test('8. SCHOOL_SUSPENDED: the whole message is refused and can be sent again once the school is back', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 2000);
    const records = [sale(card, { n: 1 }), sale(card, { n: 2 })];
    const env = envelope(canteen, 'journal.batch', { batchId: 'CANTEEN-01-B1', count: 2, records }, { txn: 'CANTEEN-01-B1' });
    t.schools.setSchoolStatus(t.a.id, 'SUSPENDED', 'operator');
    const before = snapshotOf(canteen);
    assertRefused(deliver(canteen, env), 'SCHOOL_SUSPENDED', canteen, { before });
    assert.deepEqual(purchases(t.a), []);
    // other schools carry on
    assert.equal(send(t.b.m['CANTEEN-01'], 'device.heartbeat', heartbeatBody()).result, 'ACCEPTED');
    // the machine kept its records and sends the same message again
    t.schools.setSchoolStatus(t.a.id, 'ACTIVE', 'operator');
    const res = deliver(canteen, env);
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail.results.map((r) => r.status), ['POSTED', 'POSTED']);
    assertBooks(t.a);
  });

  test('8. DEVICE_DISABLED: a machine that is not ACTIVE is refused until switched back on', () => {
    const water1 = t.a.m['WATER-01'];
    const card = fund(t.a, 'aina', 1000);
    const env = envelope(water1, 'water.recorded', { record: water(card, { n: 1, ml: 500 }) });
    for (const status of ['DISABLED', 'MAINTENANCE']) {
      t.devices.setDeviceStatus({ schoolId: t.a.id, code: 'WATER-01', status, actor: 'office' });
      const res = deliver(water1, env);
      assertRefused(res, 'DEVICE_DISABLED', water1, { before: { seq: 0, inbound: 0 } });
      assert.equal(res.detail.status, status);
    }
    t.devices.setDeviceStatus({ schoolId: t.a.id, code: 'WATER-01', status: 'ACTIVE', actor: 'office' });
    assert.equal(deliver(water1, env).result, 'ACCEPTED');
    assert.equal(purchases(t.a)[0].kind, 'WATER');
  });

  test('9. WRONG_DEVICE_TYPE: sales only from readers, water only from water machines, read-backs only from kiosks', () => {
    const card = fund(t.a, 'aina', 2000);
    const cases = [
      [t.a.m['WATER-01'], 'sale.recorded', { record: sale(card, { origin: 'WATER-01', n: 1 }) }],
      [t.a.m['KIOSK-01'], 'sale.recorded', { record: sale(card, { n: 1 }) }],
      [t.a.m['CANTEEN-01'], 'water.recorded', { record: water(card, { origin: 'CANTEEN-01', n: 2, ml: 300 }) }],
      [t.a.m['CANTEEN-01'], 'card.readback', { card: card.digest, last4: card.last4, balanceSen: card.balanceSen, cardSeq: card.cardSeq, records: [], writes: [] }],
    ];
    for (const [m, type, body] of cases) {
      const res = send(m, type, body);
      assertRefused(res, 'WRONG_DEVICE_TYPE', m, { before: { seq: 0, inbound: 0 } });
      assert.equal(res.detail.deviceType, m.type);
    }
    assert.deepEqual(purchases(t.a), []);
  });

  test('9. COUNT_MISMATCH and malformed bodies (ENVELOPE_INVALID) are refused whole', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const kiosk = t.a.m['KIOSK-01'];
    const card = fund(t.a, 'aina', 5000);
    const r1 = sale(card, { n: 1 });
    const r2 = sale(card, { n: 2 });
    const batch = (fields) => send(canteen, 'journal.batch', { batchId: 'CANTEEN-01-B1', ...fields });
    let res = batch({ count: 3, records: [r1, r2] });
    assertRefused(res, 'COUNT_MISMATCH', canteen, { before: { seq: 0, inbound: 0 } });
    assert.deepEqual([res.detail.count, res.detail.records], [3, 2]);
    assertRefused(batch({ count: '2', records: [r1, r2] }), 'COUNT_MISMATCH', canteen);
    assertRefused(batch({ records: [r1, r2] }), 'COUNT_MISMATCH', canteen);
    assertRefused(batch({ count: 2, records: { r1, r2 } }), 'ENVELOPE_INVALID', canteen);
    assertRefused(batch({ count: 0, records: [] }), 'ENVELOPE_INVALID', canteen);
    const tooMany = Array.from({ length: 201 }, () => r1);
    assertRefused(batch({ count: 201, records: tooMany }), 'ENVELOPE_INVALID', canteen);
    assertRefused(send(kiosk, 'card.readback', { card: card.digest, balanceSen: 0, cardSeq: 0 }), 'ENVELOPE_INVALID', kiosk);
    const ack = { command: newUuid(), kind: 'prices', result: 'APPLIED', appliedVersion: 1 };
    for (const broken of [{ ...ack, kind: 'firmware' }, { ...ack, result: 'OK' }, { ...ack, appliedVersion: -1 }, { ...ack, command: undefined }, { ...ack, command: '' }]) {
      assertRefused(send(canteen, 'command.ack', broken), 'ENVELOPE_INVALID', canteen);
    }
    assert.equal(lastSeq(canteen), 0);
    assert.equal(inbound(t.a), 0);
    assert.deepEqual(purchases(t.a), []);
  });

  test('the earliest failing step decides the code', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const water1 = t.a.m['WATER-01'];
    const card = fund(t.a, 'aina', 5000);
    assert.equal(send(canteen, 'device.heartbeat', heartbeatBody(), { seq: 10 }).result, 'ACCEPTED');
    assert.equal(send(water1, 'device.heartbeat', heartbeatBody(), { seq: 10 }).result, 'ACCEPTED');
    t.devices.setDeviceStatus({ schoolId: t.a.id, code: 'WATER-01', status: 'DISABLED', actor: 'office' });

    // unknown machine before a bad payload
    assert.equal(t.intake.handle('lab/v1/smk-alpha/CANTEEN-09/records', 'not json').code, 'UNKNOWN_DEVICE');
    // topic mismatch before the signature
    const wrongSchool = envelope(canteen, 'device.heartbeat', heartbeatBody(), { school: 'smk-beta', seq: 11 });
    assert.equal(deliver(canteen, { ...wrongSchool, sig: 'x'.repeat(43) }, 'status').code, 'TOPIC_MISMATCH');
    // a forged message with an old seq is a forgery first
    const old = envelope(canteen, 'device.heartbeat', heartbeatBody(), { seq: 3 });
    assert.equal(deliver(canteen, { ...old, sig: 'x'.repeat(43) }).code, 'SIGNATURE_INVALID');
    // an old seq before the school's suspension, the suspension before the switched-off machine
    t.schools.setSchoolStatus(t.a.id, 'SUSPENDED', 'operator');
    assert.equal(deliver(canteen, old).code, 'SEQUENCE_ROLLBACK');
    assert.equal(send(water1, 'sale.recorded', { record: sale(card, { origin: 'WATER-01', n: 1 }) }, { seq: 11 }).code, 'SCHOOL_SUSPENDED');
    t.schools.setSchoolStatus(t.a.id, 'ACTIVE', 'operator');
    // the switched-off machine before the wrong message type
    assert.equal(send(water1, 'sale.recorded', { record: sale(card, { origin: 'WATER-01', n: 1 }) }, { seq: 12 }).code, 'DEVICE_DISABLED');
    // the wrong message type before a count that does not add up
    const kioskBatch = { batchId: 'K-B1', count: 9, records: [sale(card, { n: 1 })] };
    assert.equal(send(water1, 'card.readback', { ...kioskBatch, card: card.digest, balanceSen: 0, cardSeq: 0 }, { seq: 13 }).code, 'DEVICE_DISABLED');
    t.devices.setDeviceStatus({ schoolId: t.a.id, code: 'WATER-01', status: 'ACTIVE', actor: 'office' });
    assert.equal(send(water1, 'card.readback', { card: card.digest, balanceSen: 0, cardSeq: 0, records: 'none' }, { seq: 14 }).code, 'WRONG_DEVICE_TYPE');
    assert.equal(send(canteen, 'journal.batch', kioskBatch, { seq: 15 }).code, 'COUNT_MISMATCH');
    assert.deepEqual(purchases(t.a), []);
  });
});

describe('accepted messages', () => {
  test('device.heartbeat: the machine\'s heartbeat, firmware, health and list versions', () => {
    const canteen = t.a.m['CANTEEN-01'];
    t.ctx.clock.advance(MINUTE);
    const at = t.ctx.clock.iso();
    const res = send(canteen, 'device.heartbeat', { fw: '1.0.0-lab', health: 'WARN', listVersions: { prices: 1, settings: 0, blocklist: 1 }, journalUnsent: 4 }, { at });
    assert.deepEqual(res, {
      result: 'ACCEPTED',
      type: 'device.heartbeat',
      detail: { listVersions: { prices: 1, settings: 0, blocklist: 1 }, journalUnsent: 4 },
    });
    const device = t.devices.getDevice(t.a.id, canteen.id);
    assert.deepEqual([device.lastHeartbeatAt, device.fwVersion, device.health, device.online, device.lastSeq], [Date.parse(at), '1.0.0-lab', 'WARN', true, 1]);
    const states = t.configs.listStates(t.a.id).filter((s) => s.deviceCode === 'CANTEEN-01');
    assert.deepEqual(states.map((s) => [s.kind, s.appliedVersion, s.via, s.behind]), [
      ['prices', 1, 'HEARTBEAT', false],
      ['settings', 0, 'HEARTBEAT', true],
      ['blocklist', 1, 'HEARTBEAT', false],
    ]);
    assert.deepEqual(eventsOf(t.ctx, 'intake.accepted').map((e) => [e.school, e.data]), [['smk-alpha', { device: 'CANTEEN-01', type: 'device.heartbeat' }]]);
    assert.equal(inbound(t.a), 1);
  });

  test('device.heartbeat: unusable list versions are skipped, the heartbeat still counts', () => {
    const kiosk = t.a.m['KIOSK-01'];
    const res = send(kiosk, 'device.heartbeat', { fw: 'x', health: 'OK', listVersions: { prices: 'one', settings: -1, blocklist: 2, firmware: 7 } });
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail, { listVersions: { blocklist: 2 } });
    assert.equal(send(kiosk, 'device.heartbeat', { listVersions: null }).result, 'ACCEPTED');
    const states = t.configs.listStates(t.a.id).filter((s) => s.deviceCode === 'KIOSK-01' && s.via !== null);
    assert.deepEqual(states.map((s) => [s.kind, s.appliedVersion]), [['blocklist', 2]]);
    assert.equal(t.devices.getDevice(t.a.id, kiosk.id).online, true);
  });

  test('sale.recorded: posted over MQTT, mirrored in the books', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 2000);
    const record = sale(card, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 2]] });
    const res = send(canteen, 'sale.recorded', { record }, { txn: record.txn });
    assert.equal(res.result, 'ACCEPTED');
    assert.equal(res.type, 'sale.recorded');
    const [r] = res.detail.results;
    assert.match(r.purchaseId, /^pur_/);
    assert.deepEqual({ ...r, purchaseId: 'x' }, { txn: 'CANTEEN-01-000001', origin: 'CANTEEN-01', status: 'POSTED', purchaseId: 'x', differences: [] });
    const [p] = purchases(t.a);
    assert.deepEqual([p.via, p.status, p.amountSen, p.late], ['MQTT', 'POSTED', 710, false]);
    assert.equal(wallet(t.a, 'aina'), 2000 - 710);
    assertBooks(t.a);
    assert.deepEqual(eventsOf(t.ctx, 'intake.accepted').map((e) => e.data), [
      { device: 'CANTEEN-01', type: 'sale.recorded', results: [{ txn: 'CANTEEN-01-000001', status: 'POSTED', differences: [] }] },
    ]);
  });

  test('water.recorded: posted, with what a person must look at', () => {
    const water1 = t.a.m['WATER-01'];
    const card = fund(t.a, 'badrul', 100);
    const record = water(card, { n: 1, ml: 650 });
    const res = send(water1, 'water.recorded', { record }, { txn: record.txn });
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail.results.map((r) => [r.status, r.differences]), [['POSTED', []]]);
    assert.equal(wallet(t.a, 'badrul'), 100 - waterChargeSen(650, PER_LITRE, MIN_CHARGE));
    // a record the books disagree with is still posted (the card was charged), with a difference:
    // this chip holds more than its mirror (say a top-up whose confirm never arrived)
    card.balanceSen += 1000;
    const overdrawn = water(card, { n: 2, ml: 20000 });
    const second = send(water1, 'water.recorded', { record: overdrawn });
    assert.equal(second.result, 'ACCEPTED');
    assert.deepEqual(second.detail.results[0].differences, ['MIRROR_NEGATIVE']);
    assertBooks(t.a);
  });

  test('sale.recorded: a card the school does not know is kept FLAGGED for a person', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const stranger = { digest: t.schools.cardDigestFor(t.a.id, '04DEADBEEF0001'), last4: '0001', cardSeq: 0, balanceSen: 1000 };
    const res = send(canteen, 'sale.recorded', { record: sale(stranger, { n: 1 }) });
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail.results.map((r) => [r.status, r.differences]), [['FLAGGED', ['UNKNOWN_CARD']]]);
    assertBooks(t.a);
  });

  test('sale.recorded: a record settlement refuses refuses the message, which is still recorded once', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 2000);
    const broken = { ...sale(card, { n: 1 }), amountSen: -5 };
    const env = envelope(canteen, 'sale.recorded', { record: broken });
    const res = deliver(canteen, env);
    assert.equal(res.result, 'REFUSED');
    assert.equal(res.code, 'RECORD_INVALID');
    assert.equal(res.type, 'sale.recorded');
    assert.deepEqual(res.detail.results.map((r) => [r.status, r.code]), [['REFUSED', 'RECORD_INVALID']]);
    const [entry] = logOf(canteen);
    assert.deepEqual([entry.level, entry.code, entry.detail.txn, entry.detail.type], ['WARN', 'RECORD_INVALID', 'CANTEEN-01-000001', 'sale.recorded']);
    assert.deepEqual(refusedEvents().map((e) => e.data), [
      { device: 'CANTEEN-01', type: 'sale.recorded', code: 'RECORD_INVALID', results: [{ txn: 'CANTEEN-01-000001', status: 'REFUSED', code: 'RECORD_INVALID', differences: [] }] },
    ]);
    // the message got through the pipeline: its seq is used and a repeat is a duplicate
    assert.equal(lastSeq(canteen), env.seq);
    assert.deepEqual(deliver(canteen, env).detail.firstResult, 'REFUSED');
    // a record naming a machine this school does not have
    const elsewhere = sale(card, { origin: 'CANTEEN-07', n: 1 });
    const res2 = send(canteen, 'sale.recorded', { record: elsewhere });
    assert.equal(res2.code, 'UNKNOWN_ORIGIN_DEVICE');
    assert.equal(logOf(canteen)[0].code, 'UNKNOWN_ORIGIN_DEVICE');
    assert.deepEqual(purchases(t.a), []);
    assert.equal(wallet(t.a, 'aina'), 2000);
  });

  test('journal.batch: each record on its own, one bad record refused alone', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 3000);
    const r1 = sale(card, { n: 1 });
    assert.equal(send(canteen, 'sale.recorded', { record: r1 }).result, 'ACCEPTED');
    const r2 = sale(card, { n: 2, items: [['MEE-GORENG', 1]] });
    const r3 = { ...sale(card, { n: 3 }), card: 'not-a-digest' };
    const r4 = sale(card, { n: 4, items: [['MILO-AIS', 2]] });
    const records = [r1, r2, r3, r4];
    const res = send(canteen, 'journal.batch', { batchId: 'CANTEEN-01-B1', count: 4, records }, { txn: 'CANTEEN-01-B1' });
    assert.equal(res.result, 'ACCEPTED');
    assert.equal(res.detail.batchId, 'CANTEEN-01-B1');
    assert.equal(res.detail.count, 4);
    assert.deepEqual(res.detail.results.map((r) => [r.index, r.txn, r.status, r.code]), [
      [0, 'CANTEEN-01-000001', 'DUPLICATE', undefined],
      [1, 'CANTEEN-01-000002', 'POSTED', undefined],
      [2, 'CANTEEN-01-000003', 'REFUSED', 'RECORD_INVALID'],
      [3, 'CANTEEN-01-000004', 'POSTED', undefined],
    ]);
    const posted = purchases(t.a);
    assert.deepEqual(posted.map((p) => [p.txn, p.via, p.late]).sort(), [
      ['CANTEEN-01-000001', 'MQTT', false],
      ['CANTEEN-01-000002', 'JOURNAL_BATCH', true],
      ['CANTEEN-01-000004', 'JOURNAL_BATCH', true],
    ]);
    // the bad record, and only it, is in the machine's log
    const log = logOf(canteen);
    assert.equal(log.length, 1);
    assert.deepEqual([log[0].code, log[0].detail.index, log[0].detail.batchId, log[0].detail.txn], ['RECORD_INVALID', 2, 'CANTEEN-01-B1', 'CANTEEN-01-000003']);
    assert.equal(wallet(t.a, 'aina'), 3000 - PRICE['NASI-LEMAK'] - PRICE['MEE-GORENG'] - 2 * PRICE['MILO-AIS']);
    assertBooks(t.a);
    const event = eventsOf(t.ctx, 'intake.accepted').at(-1);
    assert.deepEqual(event.data.results.map((r) => r.status), ['DUPLICATE', 'POSTED', 'REFUSED', 'POSTED']);
  });

  test('card.readback: the card\'s records are posted, then its balance is checked against the mirror', () => {
    const kiosk = t.a.m['KIOSK-01'];
    const card = fund(t.a, 'aina', 2000);
    // bought on machines with no network: only the card knows
    const r1 = sale(card, { n: 1 });
    const r2 = water(card, { n: 1, ml: 500 });
    const body = () => ({
      card: card.digest,
      last4: card.last4,
      balanceSen: card.balanceSen,
      cardSeq: card.cardSeq,
      listVersionOnCard: 1,
      records: [r1, r2],
      writes: [],
    });
    const res = send(kiosk, 'card.readback', body());
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail.results.map((r) => [r.origin, r.status]), [['CANTEEN-01', 'POSTED'], ['WATER-01', 'POSTED']]);
    assert.deepEqual(res.detail.snapshot, { checked: true, match: true, mirrorSen: card.balanceSen, cardSen: card.balanceSen, unconfirmedSen: 0 });
    assert.deepEqual(purchases(t.a).map((p) => p.via), ['KIOSK_READBACK', 'KIOSK_READBACK']);
    assert.deepEqual(t.differences.list(t.a.id), []);

    // the same card again: the records are duplicates, and a card holding more than the books is flagged
    card.balanceSen += 500;
    const again = send(kiosk, 'card.readback', body());
    assert.deepEqual(again.detail.results.map((r) => r.status), ['DUPLICATE', 'DUPLICATE']);
    assert.equal(again.detail.snapshot.match, false);
    const [diff] = t.differences.list(t.a.id, { kind: 'BALANCE_MISMATCH' });
    assert.equal(diff.ref, `${card.digest}:${card.cardSeq}`);
    assert.equal(diff.detail.differenceSen, 500);
    assertBooks(t.a);
  });

  test('card.readback: a write the kiosk has not confirmed yet (power cut) is not a mismatch', () => {
    const kiosk = t.a.m['KIOSK-01'];
    const member = t.a.members.aina;
    const card = fund(t.a, 'aina', 1000);
    // a subsidy reached the card, but the power went before the kiosk could confirm it
    const order = t.topups.grantSubsidy({ schoolId: t.a.id, memberId: member.id, amountSen: 700, actor: 'office' });
    t.topups.kioskPending({ schoolId: t.a.id, kioskDeviceId: kiosk.id, cardDigest: member.digest });
    card.balanceSen += 700;
    card.cardSeq += 1;
    const writes = [{ orderId: order.id, amountSen: 700, kioskTxn: deviceTxnNo('KIOSK-01', 99), at: toIso(t.ctx.clock.now()) }];
    const body = { card: card.digest, last4: card.last4, balanceSen: card.balanceSen, cardSeq: card.cardSeq, listVersionOnCard: 1, records: [], writes };
    const res = send(kiosk, 'card.readback', body);
    assert.deepEqual(res.detail.snapshot, { checked: true, match: true, mirrorSen: 1000, cardSen: 1700, unconfirmedSen: 700 });
    assert.deepEqual(t.differences.list(t.a.id), []);
    // without the card's writes the same snapshot would be a mismatch
    const blind = send(kiosk, 'card.readback', { ...body, writes: undefined });
    assert.equal(blind.detail.snapshot.match, false);
    assert.equal(t.differences.list(t.a.id, { kind: 'BALANCE_MISMATCH' }).length, 1);
  });

  test('card.readback: a snapshot that cannot be checked is logged, and the records stay', () => {
    const kiosk = t.a.m['KIOSK-01'];
    const card = fund(t.a, 'aina', 2000);
    const r1 = sale(card, { n: 1 });
    const cases = [
      { card: 'not-a-digest', balanceSen: card.balanceSen, cardSeq: card.cardSeq },
      { card: card.digest, balanceSen: -1, cardSeq: card.cardSeq },
      { card: card.digest, balanceSen: card.balanceSen, cardSeq: 1.5 },
      { card: card.digest, balanceSen: card.balanceSen, cardSeq: card.cardSeq, writes: 'lots' },
      { card: card.digest, balanceSen: card.balanceSen, cardSeq: card.cardSeq, writes: [{ orderId: 7, amountSen: 1 }] },
    ];
    for (const [i, snap] of cases.entries()) {
      const res = send(kiosk, 'card.readback', { last4: card.last4, records: [r1], ...snap });
      assert.equal(res.result, 'ACCEPTED', `case ${i}`);
      assert.equal(res.detail.snapshot.checked, false);
      assert.equal(res.detail.snapshot.code, 'SNAPSHOT_INVALID');
      assert.deepEqual(res.detail.results.map((r) => r.status), [i === 0 ? 'POSTED' : 'DUPLICATE']);
      const [entry] = logOf(kiosk);
      assert.deepEqual([entry.level, entry.code], ['WARN', 'SNAPSHOT_INVALID']);
      assert.match(entry.message, /^card read-back: /);
    }
    assert.equal(purchases(t.a).length, 1);
    assert.equal(wallet(t.a, 'aina'), 2000 - PRICE['NASI-LEMAK']);
    assertBooks(t.a);
  });

  test('command.ack: APPLIED and ALREADY_APPLIED record what the machine runs; REJECTED is logged', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const command = newUuid();
    let res = send(canteen, 'command.ack', { command, kind: 'prices', result: 'APPLIED', appliedVersion: 1 });
    assert.deepEqual(res, {
      result: 'ACCEPTED',
      type: 'command.ack',
      detail: { command, kind: 'prices', ack: 'APPLIED', appliedVersion: 1, recorded: true },
    });
    res = send(canteen, 'command.ack', { command: newUuid(), kind: 'blocklist', result: 'ALREADY_APPLIED', appliedVersion: 1 });
    assert.equal(res.detail.recorded, true);
    const stateOf = (kind) => t.configs.listStates(t.a.id).find((s) => s.deviceCode === 'CANTEEN-01' && s.kind === kind);
    assert.deepEqual([stateOf('prices').appliedVersion, stateOf('prices').via], [1, 'MQTT']);
    assert.deepEqual([stateOf('blocklist').appliedVersion, stateOf('blocklist').via], [1, 'MQTT']);

    res = send(canteen, 'command.ack', { command: newUuid(), kind: 'settings', result: 'REJECTED', appliedVersion: 0, error: 'CONFIG_INVALID' });
    assert.equal(res.result, 'ACCEPTED');
    assert.equal(res.detail.recorded, false);
    assert.equal(stateOf('settings').via, null, 'a rejection says nothing new about the version');
    const [entry] = logOf(canteen);
    assert.deepEqual([entry.level, entry.code, entry.detail.error], ['WARN', 'COMMAND_REJECTED', 'CONFIG_INVALID']);
  });
});

describe('idempotency', () => {
  test('one sale reaching the platform three ways is posted once', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const kiosk = t.a.m['KIOSK-01'];
    const card = fund(t.a, 'aina', 1000);
    const record = sale(card, { n: 1 });
    assert.deepEqual(send(canteen, 'sale.recorded', { record }).detail.results.map((r) => r.status), ['POSTED']);
    const batch = send(canteen, 'journal.batch', { batchId: 'CANTEEN-01-B1', count: 1, records: [record] });
    assert.deepEqual(batch.detail.results.map((r) => r.status), ['DUPLICATE']);
    const readback = send(kiosk, 'card.readback', { card: card.digest, last4: card.last4, balanceSen: card.balanceSen, cardSeq: card.cardSeq, records: [record], writes: [] });
    assert.deepEqual(readback.detail.results.map((r) => r.status), ['DUPLICATE']);
    assert.equal(readback.detail.snapshot.match, true);
    assert.equal(purchases(t.a).length, 1);
    assert.equal(wallet(t.a, 'aina'), 1000 - PRICE['NASI-LEMAK']);
    assert.equal(t.ledger.postings(t.a.id, { limit: 100 }).filter((p) => p.kind === 'PURCHASE').length, 1);
    assertBooks(t.a);
  });

  test('a message id is per machine: another machine may use the same id', () => {
    const c1 = t.a.m['CANTEEN-01'];
    const c2 = t.a.m['CANTEEN-02'];
    const id = newUuid();
    assert.equal(send(c1, 'device.heartbeat', heartbeatBody(), { id }).result, 'ACCEPTED');
    assert.equal(send(c2, 'device.heartbeat', heartbeatBody(), { id }).result, 'ACCEPTED');
    assert.equal(send(c1, 'device.heartbeat', heartbeatBody(), { id, seq: 1 }).result, 'DUPLICATE');
  });
});

describe('tenant isolation', () => {
  test('a machine of one school can never post into another', () => {
    const canteenA = t.a.m['CANTEEN-01'];
    const canteenB = t.b.m['CANTEEN-01'];
    const cardB = fund(t.b, 'chong', 1000);
    const record = sale(cardB, { n: 1 });
    // A's machine speaks for B's same-code machine: it cannot sign as that machine
    const forged = envelope(canteenA, 'sale.recorded', { record }, { school: 'smk-beta' });
    assertRefused(deliver(canteenB, forged), 'SIGNATURE_INVALID', canteenB, { before: { seq: 0, inbound: 0 } });
    // A's own envelope on B's topic
    const ownEnvelope = envelope(canteenA, 'sale.recorded', { record });
    assertRefused(deliver(canteenB, ownEnvelope), 'TOPIC_MISMATCH', canteenB);
    assert.deepEqual(purchases(t.b), []);
    assert.equal(wallet(t.b, 'chong'), 1000);
    // and B's card used on A's machine is a card A does not know (another school, another digest)
    assert.notEqual(t.a.members.aina.digest, t.b.members.chong.digest);
    const res = deliver(canteenA, ownEnvelope);
    assert.deepEqual(res.detail.results.map((r) => [r.status, r.differences]), [['FLAGGED', ['UNKNOWN_CARD']]]);
    assert.deepEqual(purchases(t.b), []);
    assertBooks(t.a);
    assertBooks(t.b);
    // each school's log holds only its own machines' lines
    assert.ok(t.devices.listLog(t.b.id).every((e) => e.deviceCode === 'CANTEEN-01' && e.schoolId === t.b.id));
    assert.deepEqual(t.devices.listLog(t.a.id), []);
    assert.deepEqual(refusedEvents().map((e) => e.school), ['smk-beta', 'smk-beta']);
  });

  test('sequence numbers, duplicates and gates belong to one machine of one school', () => {
    const canteenA = t.a.m['CANTEEN-01'];
    const canteenB = t.b.m['CANTEEN-01'];
    const id = newUuid();
    assert.equal(send(canteenA, 'device.heartbeat', heartbeatBody(), { seq: 50, id }).result, 'ACCEPTED');
    // B's machine with the same code starts from its own seq and may reuse the id
    assert.equal(send(canteenB, 'device.heartbeat', heartbeatBody(), { seq: 1, id }).result, 'ACCEPTED');
    t.schools.setSchoolStatus(t.a.id, 'SUSPENDED', 'operator');
    assert.equal(send(canteenA, 'device.heartbeat', heartbeatBody(), { seq: 51 }).code, 'SCHOOL_SUSPENDED');
    assert.equal(send(canteenB, 'device.heartbeat', heartbeatBody(), { seq: 2 }).result, 'ACCEPTED');
    assert.deepEqual([lastSeq(canteenA), lastSeq(canteenB)], [50, 2]);
  });
});

describe('handle never throws', () => {
  test('whatever arrives, it answers', () => {
    const canteen = t.a.m['CANTEEN-01'];
    const odd = [
      [undefined, undefined],
      [{}, 'x'],
      [topicOf(canteen, 'records'), Symbol('payload')],
      [topicOf(canteen, 'records'), new Uint8Array([0x7b, 0x7d])],
      [topicOf(canteen, 'records'), JSON.stringify({ ...envelope(canteen, 'journal.batch', { count: 1, records: [null] }) })],
    ];
    for (const [topic, payload] of odd) {
      const res = t.intake.handle(topic, payload);
      assert.ok(['ACCEPTED', 'REFUSED'].includes(res.result), JSON.stringify(res));
    }
  });

  test('a failure of the platform itself is REFUSED INTERNAL, logged, and nothing of the message is kept', () => {
    const logs = [];
    t.ctx.log = (level, message, meta) => logs.push({ level, message, meta });
    const broken = { receive: () => { throw new Error('settlement is down'); } };
    const intake = createIntake(t.ctx, { schools: t.schools, devices: t.devices, configs: t.configs, settlement: broken, reconcile: t.reconcile });
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 1000);
    const env = envelope(canteen, 'sale.recorded', { record: sale(card, { n: 1 }) });
    const res = intake.handle(topicOf(canteen, 'records'), JSON.stringify(env));
    assert.deepEqual(res, { result: 'REFUSED', code: 'INTERNAL', type: 'sale.recorded', detail: { message: 'the platform could not process this message' } });
    assert.equal(lastSeq(canteen), 0);
    assert.equal(inbound(t.a), 0);
    const [entry] = logOf(canteen);
    assert.deepEqual([entry.level, entry.code, entry.detail.error], ['ERROR', 'INTERNAL', 'settlement is down']);
    assert.ok(logs.some((l) => l.level === 'error' && l.meta.error === 'settlement is down'));
    assert.equal(refusedEvents().at(-1).data.code, 'INTERNAL');
    // once the platform works again the machine's same message goes in
    assert.equal(t.intake.handle(topicOf(canteen, 'records'), JSON.stringify(env)).result, 'ACCEPTED');
    assert.equal(purchases(t.a).length, 1);
    assertBooks(t.a);
  });

  test('in a batch, a failure of the platform costs only that record its place', () => {
    t.ctx.log = () => {};
    const canteen = t.a.m['CANTEEN-01'];
    const card = fund(t.a, 'aina', 2000);
    const records = [sale(card, { n: 1 }), sale(card, { n: 2 }), sale(card, { n: 3 })];
    const flaky = {
      receive(args) {
        if (args.record.txn === 'CANTEEN-01-000002') throw new Error('one record trips a bug');
        return t.settlement.receive(args);
      },
    };
    const intake = createIntake(t.ctx, { devices: t.devices, configs: t.configs, settlement: flaky, reconcile: t.reconcile });
    const env = envelope(canteen, 'journal.batch', { batchId: 'CANTEEN-01-B1', count: 3, records });
    const res = intake.handle(topicOf(canteen, 'records'), JSON.stringify(env));
    assert.equal(res.result, 'ACCEPTED');
    assert.deepEqual(res.detail.results.map((r) => [r.status, r.code]), [['POSTED', undefined], ['REFUSED', 'INTERNAL'], ['POSTED', undefined]]);
    assert.deepEqual([logOf(canteen)[0].level, logOf(canteen)[0].code], ['ERROR', 'INTERNAL']);
    assert.equal(purchases(t.a).length, 2);
    assertBooks(t.a);
  });

  test('even with the database gone it answers instead of throwing', () => {
    const ctx = createTestCtx();
    const schools = createSchools(ctx);
    const devices = createDevices(ctx);
    const configs = createConfigs(ctx, { schools });
    const ledger = createLedger(ctx);
    const differences = createDifferences(ctx);
    const settlement = createSettlement(ctx, { ledger, schools, configs, devices, differences });
    const reconcile = createReconcile(ctx, { ledger, schools, configs, devices, differences });
    const intake = createIntake(ctx, { schools, devices, configs, settlement, reconcile });
    ctx.db.close();
    const res = intake.handle('lab/v1/smk-alpha/CANTEEN-01/records', '{}');
    assert.equal(res.result, 'REFUSED');
    assert.equal(res.code, 'INTERNAL');
  });
});
