import { test, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { createTestCtx, eventsOf } from '../helpers.js';
import { createSchools } from '../../src/platform/schools.js';
import { createDevices } from '../../src/platform/devices.js';
import { createConfigs, DEFAULT_PRICES } from '../../src/platform/configs.js';
import { createLedger } from '../../src/platform/ledger.js';
import { createDifferences } from '../../src/platform/differences.js';
import { createSettlement } from '../../src/platform/settlement.js';
import { createReconcile, DEFAULT_LIST_MAX_AGE_MS } from '../../src/platform/reconcile.js';
import { waterChargeSen } from '../../src/shared/money.js';
import { deviceTxnNo } from '../../src/shared/protocol.js';
import { DEFAULT_LAB_START } from '../../src/shared/clock.js';
import { DAY, HOUR } from '../../src/shared/time.js';

// All schools, people and machines below are fictional; card keys and device secrets are
// generated by the services for every test.

/** assert.throws matcher for a LabError code (and optional HTTP status). */
const code = (c, status) => (err) => {
  assert.equal(err.name, 'LabError', `expected LabError ${c}, got ${err}`);
  assert.equal(err.code, c, err.message);
  if (status !== undefined) assert.equal(err.status, status);
  return true;
};

const MACHINES = [['CANTEEN-01', 'CANTEEN'], ['CANTEEN-02', 'CANTEEN'], ['WATER-01', 'WATER'], ['KIOSK-01', 'KIOSK']];
const T0 = DEFAULT_LAB_START; // where createTestCtx's clock starts: Mon 05/10/2026 10:00 in Kuala Lumpur

let t; // this test's world: ctx, services and two schools

/**
 * A school as it is after installation: machines, members with cards, the default prices, and
 * block list version 1, which every machine was provisioned with.
 */
function addSchool(svc, schoolCode, name, people, machines) {
  const school = svc.schools.createSchool({ code: schoolCode, name });
  const devices = {};
  for (const [deviceCode, type] of machines) {
    devices[deviceCode] = svc.devices.registerDevice({ schoolId: school.id, code: deviceCode, type, actor: 'test' }).device;
  }
  const members = {};
  for (const [key, p] of Object.entries(people)) {
    const member = svc.schools.addMember({ schoolId: school.id, memberNo: p.no, name: p.name });
    const card = svc.schools.issueCard({ schoolId: school.id, memberId: member.id, uid: p.uid, actor: 'test' });
    members[key] = { id: member.id, uid: p.uid, cardId: card.id };
  }
  svc.configs.publish({ schoolId: school.id, kind: 'prices', content: DEFAULT_PRICES, actor: 'test' });
  const { version } = svc.configs.ensureBlockList({ schoolId: school.id, actor: 'test' });
  for (const device of Object.values(devices)) {
    svc.configs.recordListState({ deviceId: device.id, kind: 'blocklist', version, via: 'PROVISION' });
  }
  return { id: school.id, code: schoolCode, devices, members };
}

function setup() {
  const ctx = createTestCtx();
  const schools = createSchools(ctx);
  const devices = createDevices(ctx);
  const configs = createConfigs(ctx, { schools });
  const ledger = createLedger(ctx);
  const differences = createDifferences(ctx);
  const deps = { ledger, schools, configs, devices, differences };
  const svc = { ctx, ...deps, settlement: createSettlement(ctx, deps), reconcile: createReconcile(ctx, deps) };
  const a = addSchool(svc, 'smk-alpha', 'SMK Alpha (fictional)', {
    aina: { no: 'A001', name: 'Aina Alpha', uid: '04A1B2C3D4E5F6' },
    badrul: { no: 'A002', name: 'Badrul Alpha', uid: '04B7C8D9EAFB01' },
  }, MACHINES);
  // The same card UID as Aina's on purpose: in another school it is another card.
  const b = addSchool(svc, 'smk-beta', 'SMK Beta (fictional)', {
    chong: { no: 'B001', name: 'Chong Beta', uid: '04A1B2C3D4E5F6' },
  }, [['CANTEEN-01', 'CANTEEN'], ['WATER-01', 'WATER']]);
  return { ...svc, a, b };
}

beforeEach(() => {
  t = setup();
});
afterEach(() => {
  t.ctx.db.close();
});

/** What a card's chip would hold: its digest in the school, its counter and its balance. */
function chip(school, uid, balanceSen = 0) {
  return { digest: t.schools.cardDigestFor(school.id, uid), last4: uid.slice(-4), cardSeq: 0, balanceSen };
}

let orders = 0;
/** A member's card holding `balanceSen`, booked on the mirror the way the kiosk flow books it. */
function funded(school, key, balanceSen) {
  const { id: memberId, uid } = school.members[key];
  const orderId = `ord_test${++orders}`;
  const amountSen = balanceSen;
  t.ledger.post({
    schoolId: school.id,
    idemKey: `TOPUP:${orderId}:PAID`,
    kind: 'TOPUP',
    lines: [{ kind: 'CASH_RECEIVED', side: 'DR', amountSen }, { kind: 'WAITING_TO_BE_ADDED', memberId, side: 'CR', amountSen }],
  });
  t.ledger.post({
    schoolId: school.id,
    idemKey: `TOPUP:${orderId}:ADDED`,
    kind: 'TOPUP',
    lines: [{ kind: 'WAITING_TO_BE_ADDED', memberId, side: 'DR', amountSen }, { kind: 'STUDENT_WALLET', memberId, side: 'CR', amountSen }],
  });
  return chip(school, uid, balanceSen);
}

/** The chip's part of a debit: next counter, balance before and after. */
function debit(card, fields, amountSen) {
  card.cardSeq += 1;
  const balanceBeforeSen = card.balanceSen;
  card.balanceSen -= amountSen;
  return {
    priceVersion: 1,
    listVersion: 1,
    at: t.ctx.clock.iso(),
    ...fields,
    card: card.digest,
    last4: card.last4,
    cardSeq: card.cardSeq,
    amountSen,
    balanceBeforeSen,
    balanceAfterSen: card.balanceSen,
  };
}

/** A nasi lemak (RM 3.50) bought at `origin`, transaction number `n`. */
const sale = (card, { origin = 'CANTEEN-01', n }) =>
  debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'SALE', items: [{ code: 'NASI-LEMAK', qty: 1, priceSen: 350 }] }, 350);

const water = (card, { origin = 'WATER-01', n, ml }) =>
  debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'WATER', ml, perLitreSen: 20 }, waterChargeSen(ml, 20, 5));

const receive = (record, { school = t.a, via = 'MQTT' } = {}) =>
  t.settlement.receive({ schoolId: school.id, uploaderDeviceId: school.devices[record.origin]?.id ?? null, via, record });

/** What a kiosk read-back of the card reports. */
const snapshot = (card, school = t.a) =>
  t.reconcile.checkCardSnapshot({ schoolId: school.id, cardDigest: card.digest, balanceSen: card.balanceSen, cardSeq: card.cardSeq });

const diffsOf = (kind, school = t.a) => t.differences.list(school.id, { kind });
const refsOf = (kind, school = t.a) => diffsOf(kind, school).map((d) => d.ref).sort();
const assertBalanced = (school = t.a) => assert.equal(t.ledger.trialBalance(school.id).balanced, true, `the books of ${school.code} do not balance`);

describe('createReconcile', () => {
  test('needs the services it works with', () => {
    assert.throws(() => createReconcile(t.ctx, {}), TypeError);
    assert.throws(() => createReconcile(t.ctx, { ledger: t.ledger, schools: t.schools, configs: t.configs }), /differences/);
    // devices is accepted for the same signature as settlement, but no check needs it
    const { devices: _unused, ...rest } = { ledger: t.ledger, schools: t.schools, configs: t.configs, devices: t.devices, differences: t.differences };
    assert.equal(typeof createReconcile(t.ctx, rest).run, 'function');
  });

  test('gives machines 24 hours to take a new block list by default', () => {
    assert.equal(DEFAULT_LIST_MAX_AGE_MS, DAY);
  });
});

describe('checkCardSnapshot', () => {
  test('a card holding exactly its mirror balance matches', () => {
    const card = funded(t.a, 'aina', 2000);
    receive(sale(card, { n: 1 }));
    assert.deepEqual(snapshot(card), { match: true, mirrorSen: 1650, cardSen: 1650 });
    assert.equal(t.differences.list(t.a.id).length, 0);
    // a new card that was never written: counter 0, nothing on it, nothing in the books
    assert.deepEqual(snapshot(chip(t.a, t.a.members.badrul.uid)), { match: true, mirrorSen: 0, cardSen: 0 });
    assertBalanced();
  });

  test('a card holding less than its mirror opens BALANCE_MISMATCH once per card counter', () => {
    const card = funded(t.a, 'aina', 2000);
    receive(sale(card, { n: 1 }));
    const waiting = sale(card, { origin: 'CANTEEN-02', n: 1 }); // still in an offline reader's journal
    assert.deepEqual(snapshot(card), { match: false, mirrorSen: 1650, cardSen: 1300 });
    const [d] = diffsOf('BALANCE_MISMATCH');
    assert.equal(d.ref, `${card.digest}:2`);
    const { hint, ...amounts } = d.detail;
    assert.deepEqual(amounts, { memberId: t.a.members.aina.id, last4: 'E5F6', cardSeq: 2, cardSen: 1300, mirrorSen: 1650, differenceSen: -350 });
    assert.match(hint, /holds less than the books/);
    assert.match(hint, /journal/);
    // the same read-back again is the same difference
    assert.deepEqual(snapshot(card), { match: false, mirrorSen: 1650, cardSen: 1300 });
    assert.equal(diffsOf('BALANCE_MISMATCH').length, 1);
    // once the record arrives, the card and the books agree again
    receive(waiting, { via: 'KIOSK_READBACK' });
    assert.deepEqual(snapshot(card), { match: true, mirrorSen: 1300, cardSen: 1300 });
    // a later mismatch at another card counter is a new difference
    sale(card, { origin: 'CANTEEN-02', n: 2 });
    assert.equal(snapshot(card).match, false);
    assert.deepEqual(refsOf('BALANCE_MISMATCH'), [`${card.digest}:2`, `${card.digest}:3`].sort());
    assertBalanced();
  });

  test('a card holding more than its mirror says so in the hint', () => {
    const card = funded(t.a, 'aina', 2000);
    // a kiosk wrote RM 10.00 to the card, then lost power before confirming it
    card.balanceSen += 1000;
    card.cardSeq += 1;
    assert.deepEqual(snapshot(card), { match: false, mirrorSen: 2000, cardSen: 3000 });
    const [d] = diffsOf('BALANCE_MISMATCH');
    assert.equal(d.detail.differenceSen, 1000);
    assert.match(d.detail.hint, /holds more than the books/);
    assert.match(d.detail.hint, /never confirmed/);
  });

  test('a card the school does not know has no mirror to compare with', () => {
    const stranger = chip(t.a, '04FFEEDDCCBBAA', 500);
    assert.deepEqual(snapshot(stranger), { match: false, mirrorSen: null, cardSen: 500 });
    // nor does another school's card, even with a UID this school also issued
    const visitor = funded(t.b, 'chong', 700);
    assert.deepEqual(snapshot(visitor, t.a), { match: false, mirrorSen: null, cardSen: 700 });
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.equal(t.differences.list(t.b.id).length, 0);
  });

  test('each school compares its own cards with its own books', () => {
    const aina = funded(t.a, 'aina', 2000);
    const chong = funded(t.b, 'chong', 700); // the same UID, another school
    assert.deepEqual(snapshot(aina, t.a), { match: true, mirrorSen: 2000, cardSen: 2000 });
    assert.deepEqual(snapshot(chong, t.b), { match: true, mirrorSen: 700, cardSen: 700 });
    chong.balanceSen = 100;
    assert.equal(snapshot(chong, t.b).match, false);
    assert.equal(diffsOf('BALANCE_MISMATCH', t.b).length, 1);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.deepEqual(eventsOf(t.ctx, 'difference.opened').map((e) => [e.school, e.data.kind]), [['smk-beta', 'BALANCE_MISMATCH']]);
    assertBalanced();
    assertBalanced(t.b);
  });

  test('a malformed snapshot is refused with SNAPSHOT_INVALID', () => {
    const card = funded(t.a, 'aina', 2000);
    const good = { schoolId: t.a.id, cardDigest: card.digest, balanceSen: 2000, cardSeq: 0 };
    const cases = [
      { cardDigest: 'C3D4' },
      { cardDigest: card.digest.toUpperCase() },
      { cardDigest: undefined },
      { balanceSen: -1 },
      { balanceSen: 12.5 },
      { balanceSen: '2000' },
      { balanceSen: undefined },
      { cardSeq: -1 },
      { cardSeq: 1.5 },
      { cardSeq: undefined },
    ];
    for (const bad of cases) {
      assert.throws(() => t.reconcile.checkCardSnapshot({ ...good, ...bad }), code('SNAPSHOT_INVALID', 400), JSON.stringify(bad));
    }
    assert.throws(() => t.reconcile.checkCardSnapshot(), code('SNAPSHOT_INVALID', 400));
    assert.throws(() => t.reconcile.checkCardSnapshot(null), code('SNAPSHOT_INVALID', 400));
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.deepEqual(t.reconcile.checkCardSnapshot(good), { match: true, mirrorSen: 2000, cardSen: 2000 });
  });
});

describe('scanGaps', () => {
  test('one MISSING_RECORDS difference per run of missing transaction numbers', () => {
    const card = funded(t.a, 'aina', 10000);
    for (const n of [3, 4, 7, 8, 12]) receive(sale(card, { n }));
    for (const n of [1, 2]) receive(water(card, { n, ml: 500 }));
    assert.equal(t.reconcile.scanGaps(t.a.id), 2);
    const byRef = Object.fromEntries(diffsOf('MISSING_RECORDS').map((d) => [d.ref, d.detail]));
    assert.deepEqual(Object.keys(byRef).sort(), ['CANTEEN-01:5-6', 'CANTEEN-01:9-11']);
    assert.deepEqual(byRef['CANTEEN-01:9-11'], {
      origin: 'CANTEEN-01', from: 9, to: 11, count: 3, fromTxn: 'CANTEEN-01-000009', toTxn: 'CANTEEN-01-000011',
    });
    assert.deepEqual(byRef['CANTEEN-01:5-6'].count, 2);
    // nothing new the second time
    assert.equal(t.reconcile.scanGaps(t.a.id), 0);
    assert.equal(diffsOf('MISSING_RECORDS').length, 2);
    assert.deepEqual(eventsOf(t.ctx, 'difference.opened').map((e) => [e.school, e.data.ref]), [
      ['smk-alpha', 'CANTEEN-01:5-6'],
      ['smk-alpha', 'CANTEEN-01:9-11'],
    ]);
  });

  test('nothing before the first or after the last number is guessed at; one missing number is a range of one', () => {
    const card = funded(t.a, 'aina', 5000);
    for (const n of [5, 7]) receive(sale(card, { n }));
    assert.equal(t.reconcile.scanGaps(t.a.id), 1);
    const [d] = diffsOf('MISSING_RECORDS');
    assert.equal(d.ref, 'CANTEEN-01:6-6');
    assert.deepEqual(d.detail, { origin: 'CANTEEN-01', from: 6, to: 6, count: 1, fromTxn: 'CANTEEN-01-000006', toTxn: 'CANTEEN-01-000006' });
  });

  test('a range filled in part later keeps its difference and opens the rest as new ranges', () => {
    const card = funded(t.a, 'aina', 5000);
    for (const n of [1, 5]) receive(sale(card, { n }));
    assert.equal(t.reconcile.scanGaps(t.a.id), 1); // 2-4
    receive(sale(card, { n: 3 }), { via: 'JOURNAL_BATCH' });
    assert.equal(t.reconcile.scanGaps(t.a.id), 2); // 2-2 and 4-4
    assert.deepEqual(refsOf('MISSING_RECORDS'), ['CANTEEN-01:2-2', 'CANTEEN-01:2-4', 'CANTEEN-01:4-4']);
    // the whole range arriving later opens nothing more
    for (const n of [2, 4]) receive(sale(card, { n }), { via: 'USB_IMPORT' });
    assert.equal(t.reconcile.scanGaps(t.a.id), 0);
  });

  test('numbers count, however many leading zeros a txn is written with', () => {
    const card = funded(t.a, 'aina', 5000);
    receive(sale(card, { n: 1 }));
    const fourth = sale(card, { n: 4 });
    assert.equal(receive({ ...fourth, txn: 'CANTEEN-01-0000004' }).status, 'POSTED');
    assert.equal(t.reconcile.scanGaps(t.a.id), 1);
    const [d] = diffsOf('MISSING_RECORDS');
    assert.equal(d.ref, 'CANTEEN-01:2-3');
    assert.deepEqual([d.detail.fromTxn, d.detail.toTxn], ['CANTEEN-01-000002', 'CANTEEN-01-000003']);
  });

  test('a FLAGGED purchase (unknown card) still counts as received', () => {
    const card = funded(t.a, 'aina', 5000);
    receive(sale(card, { n: 1 }));
    assert.equal(receive(sale(chip(t.a, '04FFEEDDCCBBAA', 900), { n: 2 })).status, 'FLAGGED');
    receive(sale(card, { n: 3 }));
    assert.equal(t.reconcile.scanGaps(t.a.id), 0);
  });

  test("each school's machines are scanned on their own", () => {
    const aina = funded(t.a, 'aina', 5000);
    const chong = funded(t.b, 'chong', 5000);
    for (const n of [1, 2]) receive(sale(aina, { n }));
    for (const n of [1, 4]) receive(sale(chong, { n }), { school: t.b }); // the same machine code in smk-beta
    assert.equal(t.reconcile.scanGaps(t.a.id), 0);
    assert.equal(t.reconcile.scanGaps(t.b.id), 1);
    assert.deepEqual(refsOf('MISSING_RECORDS', t.b), ['CANTEEN-01:2-3']);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.equal(t.reconcile.scanGaps('sch_nope'), 0);
    assert.equal(t.reconcile.scanGaps(undefined), 0);
  });
});

describe('scanListLag', () => {
  /** The office blocks a member's card: a new block-list version. */
  const block = (school, key) => t.configs.blockCard({ schoolId: school.id, cardId: school.members[key].cardId, actor: 'test' }).version;
  /** A machine reports the block-list version it runs. */
  const applied = (school, deviceCode, version, via = 'MQTT') =>
    t.configs.recordListState({ deviceId: school.devices[deviceCode].id, kind: 'blocklist', version, via });
  const scan = (school = t.a, options) => t.reconcile.scanListLag(school.id, options);

  test('machines still behind a block list older than 24 hours are flagged once per version', () => {
    t.ctx.clock.advance(2 * DAY);
    assert.equal(scan(), 0); // every machine runs version 1, the current one
    assert.equal(block(t.a, 'aina'), 2);
    const since = t.ctx.clock.now();
    applied(t.a, 'CANTEEN-01', 2);
    applied(t.a, 'KIOSK-01', 2, 'HEARTBEAT');
    assert.equal(scan(), 0); // brand new: the offline machines get their 24 hours
    t.ctx.clock.advance(DAY);
    assert.equal(scan(), 0); // exactly 24 hours is not older than 24 hours
    t.ctx.clock.advance(1);
    assert.equal(scan(), 2);
    assert.deepEqual(refsOf('OLD_BLOCK_LIST'), ['CANTEEN-02:2', 'WATER-01:2']);
    const water = diffsOf('OLD_BLOCK_LIST').find((d) => d.ref === 'WATER-01:2');
    assert.deepEqual(water.detail, {
      deviceCode: 'WATER-01', appliedVersion: 1, currentVersion: 2, currentSince: since, reportedVia: 'PROVISION', reportedAt: T0,
    });
    assert.equal(scan(), 0); // nothing new
    // the admin card brings CANTEEN-02 up to date; WATER-01's difference stays for a person
    applied(t.a, 'CANTEEN-02', 2, 'ADMIN_CARD');
    assert.equal(scan(), 0);
    // a newer version, once it is a day old: every machine behind it, under the new version
    assert.equal(block(t.a, 'badrul'), 3);
    applied(t.a, 'CANTEEN-01', 3);
    t.ctx.clock.advance(DAY + 1);
    assert.equal(scan(), 3);
    assert.deepEqual(refsOf('OLD_BLOCK_LIST'), ['CANTEEN-02:2', 'CANTEEN-02:3', 'KIOSK-01:3', 'WATER-01:2', 'WATER-01:3']);
  });

  test('maxAgeMs sets how long machines get; an unusable one means 24 hours', () => {
    block(t.a, 'aina');
    t.ctx.clock.advance(2 * HOUR);
    for (const maxAgeMs of [-1, 'soon', NaN, Infinity, null]) assert.equal(scan(t.a, { maxAgeMs }), 0, String(maxAgeMs));
    assert.equal(scan(), 0);
    assert.equal(scan(t.a, { maxAgeMs: 3 * HOUR }), 0);
    assert.equal(scan(t.a, { maxAgeMs: HOUR }), 4); // no machine has taken version 2
    assert.equal(scan(t.a, { maxAgeMs: 0 }), 0); // already open
  });

  test('a machine that never reported a block list is behind every version', () => {
    const late = t.devices.registerDevice({ schoolId: t.a.id, code: 'CANTEEN-03', type: 'CANTEEN', actor: 'test' }).device;
    for (const deviceCode of Object.keys(t.a.devices)) applied(t.a, deviceCode, 1, 'HEARTBEAT');
    t.ctx.clock.advance(DAY + 1);
    assert.equal(scan(), 1);
    const [d] = diffsOf('OLD_BLOCK_LIST');
    assert.equal(d.ref, 'CANTEEN-03:1');
    assert.deepEqual(d.detail, {
      deviceCode: late.code, appliedVersion: 0, currentVersion: 1, currentSince: T0, reportedVia: null, reportedAt: null,
    });
  });

  test('a machine the office switched off is still judged: offline, it sells on its old list', () => {
    t.devices.setDeviceStatus({ schoolId: t.a.id, code: 'WATER-01', status: 'DISABLED', actor: 'test' });
    assert.equal(block(t.a, 'aina'), 2);
    for (const deviceCode of ['CANTEEN-01', 'CANTEEN-02', 'KIOSK-01']) applied(t.a, deviceCode, 2);
    t.ctx.clock.advance(DAY + 1);
    assert.equal(scan(), 1);
    assert.deepEqual(refsOf('OLD_BLOCK_LIST'), ['WATER-01:2']);
  });

  test('a school that never had a block list has nothing to lag behind', () => {
    const gamma = t.schools.createSchool({ code: 'smk-gamma', name: 'SMK Gamma (fictional)' });
    t.devices.registerDevice({ schoolId: gamma.id, code: 'CANTEEN-01', type: 'CANTEEN', actor: 'test' });
    t.ctx.clock.advance(10 * DAY);
    assert.equal(t.reconcile.scanListLag(gamma.id), 0);
    assert.equal(t.reconcile.scanListLag('sch_nope'), 0);
    assert.equal(t.differences.list(gamma.id).length, 0);
  });

  test("only the school's own machines are judged, against its own list", () => {
    block(t.a, 'aina'); // smk-alpha version 2; smk-beta stays on version 1, which all its machines run
    t.ctx.clock.advance(DAY + 1);
    assert.equal(scan(t.b), 0);
    assert.equal(scan(t.a), 4);
    assert.deepEqual(refsOf('OLD_BLOCK_LIST'), ['CANTEEN-01:2', 'CANTEEN-02:2', 'KIOSK-01:2', 'WATER-01:2']);
    assert.equal(t.differences.list(t.b.id).length, 0);
    // smk-beta's machines being behind smk-beta's own new version is smk-beta's difference only
    block(t.b, 'chong');
    t.ctx.clock.advance(DAY + 1);
    assert.equal(scan(t.b), 2);
    assert.deepEqual(refsOf('OLD_BLOCK_LIST', t.b), ['CANTEEN-01:2', 'WATER-01:2']);
    assert.equal(diffsOf('OLD_BLOCK_LIST').length, 4);
  });
});

describe('run', () => {
  test('runs both scans and says what each one opened', () => {
    const card = funded(t.a, 'aina', 2000);
    for (const n of [1, 3]) receive(sale(card, { n }));
    t.configs.blockCard({ schoolId: t.a.id, cardId: t.a.members.badrul.cardId, actor: 'test' });
    t.ctx.clock.advance(DAY + 1);
    assert.deepEqual(t.reconcile.run(t.a.id), { gaps: 1, lag: 4 });
    assert.deepEqual(t.reconcile.run(t.a.id), { gaps: 0, lag: 0 });
    assert.deepEqual(t.reconcile.run(t.b.id), { gaps: 0, lag: 0 });
    assert.equal(t.differences.countOpen(t.a.id), 5);
    assert.equal(t.differences.countOpen(t.b.id), 0);
    // a resolved difference stays resolved: the same gap is not opened again
    const [gap] = diffsOf('MISSING_RECORDS');
    t.differences.resolve({ schoolId: t.a.id, id: gap.id, actor: 'test', note: 'the reader lost power mid-sale' });
    assert.deepEqual(t.reconcile.run(t.a.id), { gaps: 0, lag: 0 });
    assertBalanced();
  });
});
