import { test, describe, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { createTestCtx, eventsOf } from '../helpers.js';
import { createSchools } from '../../src/platform/schools.js';
import { createDevices } from '../../src/platform/devices.js';
import { createConfigs, DEFAULT_PRICES } from '../../src/platform/configs.js';
import { createLedger } from '../../src/platform/ledger.js';
import { createDifferences } from '../../src/platform/differences.js';
import { createSettlement, PURCHASE_VIAS } from '../../src/platform/settlement.js';
import { canonicalJson } from '../../src/shared/crypto.js';
import { waterChargeSen } from '../../src/shared/money.js';
import { deviceTxnNo } from '../../src/shared/protocol.js';
import { DEFAULT_LAB_START } from '../../src/shared/clock.js';
import { DAY, HOUR, MINUTE, parseIso, toIso } from '../../src/shared/time.js';

// All schools, people and machines below are fictional; card keys and device secrets are
// generated by the services for every test.

/** assert.throws matcher for a LabError code (and optional HTTP status). */
const code = (c, status) => (err) => {
  assert.equal(err.name, 'LabError', `expected LabError ${c}, got ${err}`);
  assert.equal(err.code, c, err.message);
  if (status !== undefined) assert.equal(err.status, status);
  return true;
};

const PRICE = Object.fromEntries(DEFAULT_PRICES.items.map((i) => [i.code, i.priceSen]));
const { perLitreSen: PER_LITRE, minChargeSen: MIN_CHARGE } = DEFAULT_PRICES.water;
const MACHINES_A = [['CANTEEN-01', 'CANTEEN'], ['CANTEEN-02', 'CANTEEN'], ['WATER-01', 'WATER'], ['KIOSK-01', 'KIOSK']];
const MACHINES_B = [['CANTEEN-01', 'CANTEEN'], ['WATER-01', 'WATER'], ['WATER-02', 'WATER'], ['KIOSK-01', 'KIOSK']];
const DTO_KEYS = [
  'amountSen', 'id', 'items', 'kind', 'late', 'listVersion', 'memberId', 'memberName', 'ml', 'occurredAt',
  'originDeviceCode', 'priceVersion', 'receivedAt', 'status', 'txn', 'via',
];

let t; // this test's world: ctx, services and two schools

/** A school with machines, members holding cards, the default prices and block list version 1. */
function addSchool(svc, schoolCode, name, people, machines) {
  const school = svc.schools.createSchool({ code: schoolCode, name });
  const devices = {};
  for (const [deviceCode, type] of machines) {
    devices[deviceCode] = svc.devices.registerDevice({ schoolId: school.id, code: deviceCode, type, actor: 'test' }).device;
  }
  const members = {};
  for (const [key, p] of Object.entries(people)) {
    const member = svc.schools.addMember({ schoolId: school.id, memberNo: p.no, name: p.name });
    const card = svc.schools.issueCard({ schoolId: school.id, memberId: member.id, uid: p.uid, actor: 'test' });
    members[key] = { id: member.id, name: p.name, uid: p.uid, cardId: card.id };
  }
  svc.configs.publish({ schoolId: school.id, kind: 'prices', content: DEFAULT_PRICES, actor: 'test' });
  svc.configs.ensureBlockList({ schoolId: school.id, actor: 'test' });
  return { id: school.id, code: schoolCode, devices, members };
}

function setup() {
  const ctx = createTestCtx();
  const schools = createSchools(ctx);
  const devices = createDevices(ctx);
  const configs = createConfigs(ctx, { schools });
  const ledger = createLedger(ctx);
  const differences = createDifferences(ctx);
  const settlement = createSettlement(ctx, { ledger, schools, configs, devices, differences });
  const svc = { ctx, schools, devices, configs, ledger, differences, settlement };
  const a = addSchool(svc, 'smk-alpha', 'SMK Alpha (fictional)', {
    aina: { no: 'A001', name: 'Aina Alpha', uid: '04A1B2C3D4E5F6' },
    badrul: { no: 'A002', name: 'Badrul Alpha', uid: '04B7C8D9EAFB01' },
  }, MACHINES_A);
  // The same card UID as Aina's on purpose: in another school it is another card with another digest.
  const b = addSchool(svc, 'smk-beta', 'SMK Beta (fictional)', {
    chong: { no: 'B001', name: 'Chong Beta', uid: '04A1B2C3D4E5F6' },
  }, MACHINES_B);
  return { ...svc, a, b };
}

beforeEach(() => {
  t = setup();
});
afterEach(() => {
  t.ctx.db.close();
});

const services = () => ({ ledger: t.ledger, schools: t.schools, configs: t.configs, devices: t.devices, differences: t.differences });

/** What a card's chip would hold: its digest in the school, its counter and its balance. */
function chip(school, uid, balanceSen = 0) {
  return { digest: t.schools.cardDigestFor(school.id, uid), last4: uid.slice(-4), cardSeq: 0, balanceSen };
}

let orders = 0;
/** Money onto a member's mirror the way the kiosk flow books it: paid, then added to the card. */
function fund(school, memberId, amountSen) {
  const orderId = `ord_test${++orders}`;
  t.ledger.post({
    schoolId: school.id,
    idemKey: `TOPUP:${orderId}:PAID`,
    kind: 'TOPUP',
    lines: [{ kind: 'CASH_RECEIVED', side: 'DR', amountSen }, { kind: 'WAITING_TO_BE_ADDED', memberId, side: 'CR', amountSen }],
  });
  t.ledger.post({
    schoolId: school.id,
    idemKey: `TOPUP:${orderId}:ADDED`,
    kind: 'TOPUP',
    lines: [{ kind: 'WAITING_TO_BE_ADDED', memberId, side: 'DR', amountSen }, { kind: 'STUDENT_WALLET', memberId, side: 'CR', amountSen }],
  });
}

/** A member's card holding `balanceSen`, with the same amount on the platform's mirror. */
function funded(school, key, balanceSen) {
  const member = school.members[key];
  fund(school, member.id, balanceSen);
  return chip(school, member.uid, balanceSen);
}

/** The chip's part of a debit, as VirtualCard.debit fills it in: next counter, balance before and after. */
function debit(card, fields, amountSen) {
  card.cardSeq += 1;
  const balanceBeforeSen = card.balanceSen;
  card.balanceSen -= amountSen;
  return {
    priceVersion: 1,
    listVersion: 1,
    at: t.ctx.clock.iso(),
    ...fields,
    card: card.digest,
    last4: card.last4,
    cardSeq: card.cardSeq,
    amountSen,
    balanceBeforeSen,
    balanceAfterSen: card.balanceSen,
  };
}

/** A completed canteen record. items: [code, qty, priceSen = the default list's price]. */
function sale(card, { origin = 'CANTEEN-01', n, items = [['NASI-LEMAK', 1]], amountSen, ...rest } = {}) {
  const lines = items.map(([itemCode, qty, priceSen = PRICE[itemCode]]) => ({ code: itemCode, qty, priceSen }));
  const itemsSen = lines.reduce((sum, l) => sum + l.qty * l.priceSen, 0);
  return debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'SALE', items: lines, ...rest }, amountSen ?? itemsSen);
}

/** A completed water record; the amount follows waterChargeSen unless given. */
function water(card, { origin = 'WATER-01', n, ml, perLitreSen = PER_LITRE, minChargeSen = MIN_CHARGE, amountSen, ...rest } = {}) {
  const charge = amountSen ?? waterChargeSen(ml, perLitreSen, minChargeSen);
  return debit(card, { txn: deviceTxnNo(origin, n), origin, kind: 'WATER', ml, perLitreSen, ...rest }, charge);
}

/** settlement.receive into school A (or `school`), delivered by the record's own machine unless told otherwise. */
function receive(record, { school = t.a, via = 'MQTT', uploader = via === 'KIOSK_READBACK' ? 'KIOSK-01' : record?.origin } = {}) {
  const device = uploader == null ? undefined : school.devices[uploader];
  return t.settlement.receive({ schoolId: school.id, uploaderDeviceId: device ? device.id : null, via, record });
}

/** The books balance, and sales payable holds exactly the posted purchases. */
function assertBooks(school = t.a) {
  const tb = t.ledger.trialBalance(school.id);
  assert.equal(tb.balanced, true, `the books of ${school.code} do not balance`);
  const posted = t.ctx.db.get("SELECT coalesce(sum(amount_sen), 0) AS s FROM purchase WHERE school_id = ? AND status = 'POSTED'", school.id).s;
  assert.equal(t.ledger.balance(school.id, 'SALES_PAYABLE'), posted);
  return tb;
}

const wallet = (school, key) => t.ledger.balance(school.id, 'STUDENT_WALLET', school.members[key].id);
const purchaseRow = (id) => t.ctx.db.get('SELECT * FROM purchase WHERE id = ?', id);
const countRows = (table, school = t.a) => t.ctx.db.get(`SELECT count(*) AS n FROM ${table} WHERE school_id = ?`, school.id).n;
const diffsOf = (kind, school = t.a) => t.differences.list(school.id, { kind });
const purchasePostings = (school = t.a) => t.ledger.postings(school.id, { limit: 1000 }).filter((p) => p.kind === 'PURCHASE');
const T0 = DEFAULT_LAB_START; // where createTestCtx's clock starts: Mon 05/10/2026 10:00 in Kuala Lumpur

describe('createSettlement', () => {
  test('needs every service it works with', () => {
    assert.throws(() => createSettlement(t.ctx, {}), TypeError);
    assert.throws(() => createSettlement(t.ctx, { ...services(), ledger: undefined }), /ledger/);
    assert.throws(() => createSettlement(t.ctx, { ...services(), differences: null }), /differences/);
  });

  test('knows the four ways a record reaches the platform', () => {
    assert.deepEqual(PURCHASE_VIAS, ['MQTT', 'JOURNAL_BATCH', 'KIOSK_READBACK', 'USB_IMPORT']);
    assert.ok(Object.isFrozen(PURCHASE_VIAS));
  });
});

describe('receive: purchases that check out', () => {
  test('a canteen sale over MQTT is POSTED: purchase row, posting and mirror', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 1]] });
    const res = receive(record);
    assert.deepEqual(Object.keys(res).sort(), ['differences', 'purchaseId', 'status']);
    assert.equal(res.status, 'POSTED');
    assert.match(res.purchaseId, /^pur_/);
    assert.deepEqual(res.differences, []);

    const row = purchaseRow(res.purchaseId);
    const posting = t.ledger.findByIdemKey(t.a.id, 'PURCHASE:CANTEEN-01:CANTEEN-01-000001');
    assert.deepEqual({ ...row }, {
      id: res.purchaseId,
      school_id: t.a.id,
      origin_device_code: 'CANTEEN-01',
      device_txn: 'CANTEEN-01-000001',
      txn_number: 1,
      uploader_device_id: t.a.devices['CANTEEN-01'].id,
      via: 'MQTT',
      kind: 'SALE',
      card_digest: card.digest,
      card_id: t.a.members.aina.cardId,
      member_id: t.a.members.aina.id,
      amount_sen: 530,
      ml: null,
      price_version: 1,
      list_version: 1,
      card_seq: 1,
      balance_before_sen: 2000,
      balance_after_sen: 1470,
      occurred_at: T0,
      received_at: T0,
      status: 'POSTED',
      posting_id: posting.id,
      late: 0,
      raw: canonicalJson(record),
    });
    // DR the member's wallet / CR sales payable, linked to the purchase
    assert.equal(posting.kind, 'PURCHASE');
    assert.equal(posting.ref, res.purchaseId);
    assert.equal(posting.memo, 'Sale CANTEEN-01-000001');
    assert.deepEqual(posting.lines, [
      { kind: 'STUDENT_WALLET', memberId: t.a.members.aina.id, side: 'DR', amountSen: 530 },
      { kind: 'SALES_PAYABLE', memberId: null, side: 'CR', amountSen: 530 },
    ]);
    // the mirror follows the card
    assert.equal(wallet(t.a, 'aina'), card.balanceSen);
    assert.equal(wallet(t.a, 'aina'), 1470);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assertBooks();
  });

  test('water is charged by the litre, with the minimum charge for a small pour', () => {
    const card = funded(t.a, 'aina', 2000);
    const big = receive(water(card, { n: 1, ml: 650 })); // 650 ml at 20 sen a litre = 13 sen
    const small = receive(water(card, { n: 2, ml: 10 })); // below the 5 sen minimum charge
    for (const res of [big, small]) {
      assert.equal(res.status, 'POSTED');
      assert.deepEqual(res.differences, []);
    }
    assert.equal(waterChargeSen(650, PER_LITRE, MIN_CHARGE), 13);
    const [b, s] = [purchaseRow(big.purchaseId), purchaseRow(small.purchaseId)];
    assert.deepEqual([b.kind, b.ml, b.amount_sen, s.ml, s.amount_sen], ['WATER', 650, 13, 10, 5]);
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:WATER-01:WATER-01-000001').memo, 'Water 650 ml WATER-01-000001');
    assert.equal(wallet(t.a, 'aina'), 2000 - 13 - 5);
    assertBooks();
  });

  test('a zero-amount record is stored POSTED but moves no money', () => {
    // a price list with no minimum charge: a few millilitres cost nothing
    const v2 = t.configs.publish({
      schoolId: t.a.id, kind: 'prices', content: { ...DEFAULT_PRICES, water: { perLitreSen: 20, minChargeSen: 0 } }, actor: 'test',
    });
    const card = funded(t.a, 'aina', 1000);
    const record = water(card, { n: 1, ml: 20, minChargeSen: 0, priceVersion: v2.version });
    assert.equal(record.amountSen, 0);
    const res = receive(record);
    assert.deepEqual(res, { status: 'POSTED', purchaseId: res.purchaseId, differences: [] });
    const row = purchaseRow(res.purchaseId);
    assert.deepEqual([row.status, row.amount_sen, row.posting_id, row.member_id], ['POSTED', 0, null, t.a.members.aina.id]);
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:WATER-01:WATER-01-000001'), null);
    assert.equal(purchasePostings().length, 0);
    assert.equal(wallet(t.a, 'aina'), 1000);
    // stored like any other: a second copy is a duplicate
    assert.equal(receive(record, { via: 'JOURNAL_BATCH' }).status, 'DUPLICATE');
    assertBooks();
  });
});

describe('receive: prices', () => {
  test("a sale is checked against the price list version the machine used, not today's", () => {
    const content = { ...DEFAULT_PRICES, items: DEFAULT_PRICES.items.map((i) => (i.code === 'NASI-LEMAK' ? { ...i, priceSen: 380 } : i)) };
    assert.equal(t.configs.publish({ schoolId: t.a.id, kind: 'prices', content, actor: 'test' }).version, 2);
    const card = funded(t.a, 'aina', 5000);
    // an offline machine still on version 1 charges the old price: fine
    assert.deepEqual(receive(sale(card, { origin: 'CANTEEN-02', n: 1 })).differences, []);
    // a machine on version 2 charges the new price: fine
    assert.deepEqual(receive(sale(card, { n: 1, items: [['NASI-LEMAK', 1, 380]], priceVersion: 2 })).differences, []);
    // a machine saying version 2 but charging the old price: flagged, and posted for what the card paid
    const res = receive(sale(card, { n: 2, items: [['NASI-LEMAK', 2, 350]], priceVersion: 2 }));
    assert.equal(res.status, 'POSTED');
    assert.deepEqual(res.differences, ['PRICE_MISMATCH']);
    const [d] = diffsOf('PRICE_MISMATCH');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000002');
    assert.deepEqual(d.detail, {
      origin: 'CANTEEN-01',
      txn: 'CANTEEN-01-000002',
      kind: 'SALE',
      priceVersion: 2,
      amountSen: 700,
      expectedSen: 760,
      problems: ['NASI-LEMAK charged at 350 sen, the list says 380 sen'],
    });
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:CANTEEN-01:CANTEEN-01-000002').lines[0].amountSen, 700);
    assert.equal(wallet(t.a, 'aina'), 5000 - 350 - 380 - 700);
    assertBooks();
  });

  test('items that do not add up to the amount are a PRICE_MISMATCH', () => {
    const card = funded(t.a, 'aina', 2000);
    // 350 + 2 x 180 = 710, but the record charged 700
    const res = receive(sale(card, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 2]], amountSen: 700 }));
    assert.deepEqual([res.status, res.differences], ['POSTED', ['PRICE_MISMATCH']]);
    const [d] = diffsOf('PRICE_MISMATCH');
    assert.equal(d.detail.expectedSen, 710);
    assert.deepEqual(d.detail.problems, ['the items add up to 710 sen, the record charged 700 sen']);
    assert.equal(wallet(t.a, 'aina'), 1300);
    assertBooks();
  });

  test('an item that is not on the price list version is a PRICE_MISMATCH', () => {
    const card = funded(t.a, 'aina', 2000);
    const res = receive(sale(card, { n: 1, items: [['KUIH-LAPIS', 1, 120], ['BUAH', 1]] }));
    assert.deepEqual([res.status, res.differences], ['POSTED', ['PRICE_MISMATCH']]);
    const [d] = diffsOf('PRICE_MISMATCH');
    assert.equal(d.detail.expectedSen, null); // the list cannot say what the purchase should cost
    assert.deepEqual(d.detail.problems, ['KUIH-LAPIS is not on price list version 1']);
    assert.equal(wallet(t.a, 'aina'), 2000 - 220);
    assertBooks();
  });

  test("water: the litre price must be the version's and the amount must be waterChargeSen", () => {
    const card = funded(t.a, 'aina', 5000);
    // a machine with another litre price
    const other = receive(water(card, { n: 1, ml: 650, perLitreSen: 25 }));
    assert.deepEqual([other.status, other.differences], ['POSTED', ['PRICE_MISMATCH']]);
    // the right litre price, but the minimum charge left out
    const free = receive(water(card, { n: 2, ml: 10, minChargeSen: 0 }));
    assert.deepEqual([free.status, free.differences], ['POSTED', ['PRICE_MISMATCH']]);
    const byRef = Object.fromEntries(diffsOf('PRICE_MISMATCH').map((d) => [d.ref, d.detail]));
    assert.deepEqual(byRef['WATER-01:WATER-01-000001'], {
      origin: 'WATER-01',
      txn: 'WATER-01-000001',
      kind: 'WATER',
      priceVersion: 1,
      amountSen: 16,
      expectedSen: 13,
      problems: ['water charged at 25 sen a litre, the list says 20 sen', '650 ml costs 13 sen, the record charged 16 sen'],
    });
    assert.deepEqual(byRef['WATER-01:WATER-01-000002'].problems, ['10 ml costs 5 sen, the record charged 0 sen']);
    assert.equal(byRef['WATER-01:WATER-01-000002'].expectedSen, 5);
    assert.equal(wallet(t.a, 'aina'), 5000 - 16);
    assertBooks();
  });

  test('a price list version that was never issued is PRICE_VERSION_UNKNOWN, and still posted', () => {
    const card = funded(t.a, 'aina', 2000);
    const res = receive(sale(card, { n: 1, priceVersion: 7 }));
    assert.deepEqual([res.status, res.differences], ['POSTED', ['PRICE_VERSION_UNKNOWN']]);
    const [d] = diffsOf('PRICE_VERSION_UNKNOWN');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000001');
    assert.deepEqual(d.detail, { origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001', priceVersion: 7, latestVersion: 1 });
    assert.equal(wallet(t.a, 'aina'), 1650);
    // a version of another school does not count either
    t.configs.publish({ schoolId: t.b.id, kind: 'prices', content: DEFAULT_PRICES, actor: 'test' }); // smk-beta version 2
    assert.deepEqual(receive(sale(card, { n: 2, priceVersion: 2 })).differences, ['PRICE_VERSION_UNKNOWN']);
    assertBooks();
  });
});

describe('receive: the same record twice', () => {
  test('the same record again is a DUPLICATE however it arrives, and counts once', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    const first = receive(record);
    for (const via of PURCHASE_VIAS) {
      assert.deepEqual(receive(structuredClone(record), { via }), { status: 'DUPLICATE', purchaseId: first.purchaseId, differences: [] });
    }
    // canonical JSON: the same fields in another order are the same record
    const reordered = Object.fromEntries(Object.entries(record).reverse());
    assert.deepEqual(receive(reordered), { status: 'DUPLICATE', purchaseId: first.purchaseId, differences: [] });
    assert.equal(countRows('purchase'), 1);
    assert.equal(purchaseRow(first.purchaseId).via, 'MQTT'); // the first copy is the one kept
    assert.equal(purchasePostings().length, 1);
    assert.equal(wallet(t.a, 'aina'), 1650);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assertBooks();
  });

  test('the same txn with other content is a DUPLICATE CONFLICT: nothing is posted again', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    const first = receive(record);
    const other = { ...record, items: [{ code: 'MEE-GORENG', qty: 1, priceSen: 400 }], amountSen: 400, balanceAfterSen: 1600 };
    const res = receive(other, { via: 'KIOSK_READBACK' });
    assert.deepEqual(res, { status: 'DUPLICATE', purchaseId: first.purchaseId, code: 'CONFLICT', differences: ['DUPLICATE_CONFLICT'] });
    const [d] = diffsOf('DUPLICATE_CONFLICT');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000001');
    assert.deepEqual(d.detail, { purchaseId: first.purchaseId, changed: ['amountSen', 'balanceAfterSen', 'items'], stored: record, received: other });
    // the first copy is kept as it was
    assert.equal(purchaseRow(first.purchaseId).raw, canonicalJson(record));
    assert.equal(purchaseRow(first.purchaseId).amount_sen, 350);
    assert.equal(purchasePostings().length, 1);
    assert.equal(wallet(t.a, 'aina'), 1650);
    // yet another version: still a conflict, still one difference to look at
    assert.equal(receive({ ...record, listVersion: 4 }).code, 'CONFLICT');
    assert.equal(diffsOf('DUPLICATE_CONFLICT').length, 1);
    assert.equal(countRows('purchase'), 1);
    assertBooks();
  });

  test('the same txn number written with more leading zeros is the same transaction', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 17 });
    const first = receive(record);
    const res = receive({ ...record, txn: 'CANTEEN-01-0000017' });
    assert.deepEqual(res, { status: 'DUPLICATE', purchaseId: first.purchaseId, code: 'CONFLICT', differences: ['DUPLICATE_CONFLICT'] });
    const [d] = diffsOf('DUPLICATE_CONFLICT');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000017');
    assert.deepEqual(d.detail.changed, ['txn']);
    assert.equal(countRows('purchase'), 1);
    assert.equal(wallet(t.a, 'aina'), 1650);
    assertBooks();
  });
});

describe('receive: a card the school does not know', () => {
  test('is stored FLAGGED with no member and no posting, and opens UNKNOWN_CARD', () => {
    const stranger = chip(t.a, '04FFEEDDCCBBAA', 900); // never issued by this school
    const record = sale(stranger, { n: 1 });
    const res = receive(record);
    assert.deepEqual(res, { status: 'FLAGGED', purchaseId: res.purchaseId, differences: ['UNKNOWN_CARD'] });
    const row = purchaseRow(res.purchaseId);
    assert.deepEqual(
      [row.status, row.member_id, row.card_id, row.posting_id, row.amount_sen, row.card_digest],
      ['FLAGGED', null, null, null, 350, stranger.digest],
    );
    const [d] = diffsOf('UNKNOWN_CARD');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000001');
    assert.deepEqual(d.detail, { origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001', last4: 'BBAA', amountSen: 350 });
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:CANTEEN-01:CANTEEN-01-000001'), null);
    assert.equal(t.ledger.balance(t.a.id, 'SALES_PAYABLE'), 0);
    // stored, so the next copy is a duplicate, not a second flag
    assert.equal(receive(record, { via: 'USB_IMPORT', uploader: null }).status, 'DUPLICATE');
    assert.equal(diffsOf('UNKNOWN_CARD').length, 1);
    assertBooks();
  });

  test("another school's card is unknown here, even with the same card UID", () => {
    // smk-beta issued Aina's UID to Chong; its digest is made with smk-beta's own card key
    const visitor = funded(t.b, 'chong', 900);
    assert.notEqual(visitor.digest, t.schools.cardDigestFor(t.a.id, t.b.members.chong.uid));
    const res = receive(sale(visitor, { n: 1 }));
    assert.deepEqual([res.status, res.differences], ['FLAGGED', ['UNKNOWN_CARD']]);
    // nothing reached Aina, who holds that UID in smk-alpha, nor anything in smk-beta
    assert.equal(wallet(t.a, 'aina'), 0);
    assert.equal(countRows('purchase', t.b), 0);
    assert.equal(t.differences.list(t.b.id).length, 0);
    assert.equal(wallet(t.b, 'chong'), 900);
    assertBooks();
    assertBooks(t.b);
  });
});

describe('receive: refused records', () => {
  test('a malformed record is REFUSED with RECORD_INVALID and nothing is stored', () => {
    const card = funded(t.a, 'aina', 2000);
    const goodSale = sale(card, { n: 1 });
    const goodWater = water(card, { n: 1, ml: 500 });
    const good = (patch) => ({ ...structuredClone(goodSale), ...patch });
    const { ml: _ml, ...waterWithoutMl } = structuredClone(goodWater);
    // [what is wrong, record, the reason given]
    const cases = [
      ['no record at all', undefined, /not an object/],
      ['null', null, /not an object/],
      ['a list', [], /not an object/],
      ['text', 'CANTEEN-01-000001', /not an object/],
      ['a txn that is not DEVICE-000123', good({ txn: 'CANTEEN-01-17' }), /txn must look like/],
      ["another machine's txn", good({ txn: 'CANTEEN-02-000001' }), /origin device code/],
      ['an unknown kind', good({ kind: 'TOPUP' }), /kind must be/],
      ['a card that is not a digest', good({ card: 'C3D4' }), /card digest/],
      ['a negative amount', good({ amountSen: -350 }), /amountSen must be whole sen/],
      ['an amount in ringgit', good({ amountSen: 3.5 }), /amountSen must be whole sen/],
      ['card counter 0', good({ cardSeq: 0 }), /cardSeq/],
      ['price version 0', good({ priceVersion: 0 }), /priceVersion/],
      ['a time that is not ISO-8601', good({ at: '05/10/2026 10:00' }), /ISO-8601/],
      ['another currency', good({ currency: 'SGD' }), /MYR/],
      ['a sale without items', good({ items: [] }), /1 to 20 items/],
      ['water without ml', waterWithoutMl, /ml must be/],
      // limits the platform adds to validateRecord()
      ['a txn longer than 64 characters', good({ txn: `CANTEEN-01-${'0'.repeat(60)}1` }), /at most 64 characters/],
      ['a txn number beyond exact whole numbers', good({ txn: 'CANTEEN-01-99999999999999999999' }), /too large/],
      ['an amount beyond one posting', good({ amountSen: 1_000_000_001, balanceBeforeSen: 2_000_000_000, balanceAfterSen: 999_999_999 }), /amountSen/],
      ['an item price beyond one posting', good({ items: [{ code: 'NASI-LEMAK', qty: 1, priceSen: 1_000_000_001 }] }), /item priceSen/],
      ['an item code that is a number', good({ items: [{ code: 123, qty: 1, priceSen: 350 }] }), /item code must be text/],
      ['a value that is not plain JSON', good({ extra: new Date(T0) }), /plain JSON/],
    ];
    for (const [name, record, why] of cases) {
      const { message, ...rest } = receive(record, { uploader: 'CANTEEN-01' });
      assert.deepEqual(rest, { status: 'REFUSED', code: 'RECORD_INVALID', differences: [] }, name);
      assert.match(message, why, name);
    }
    assert.equal(countRows('purchase'), 0);
    assert.equal(purchasePostings().length, 0);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.equal(wallet(t.a, 'aina'), 2000);
    // a refused record can be sent again once it is right
    assert.equal(receive(goodSale).status, 'POSTED');
    assert.equal(receive(goodWater).status, 'POSTED');
    assertBooks();
  });

  test('a record from a machine the school does not have is REFUSED with UNKNOWN_ORIGIN_DEVICE', () => {
    const card = funded(t.a, 'aina', 2000);
    const unknown = receive(sale(card, { origin: 'CANTEEN-09', n: 1 }), { uploader: 'KIOSK-01', via: 'KIOSK_READBACK' });
    assert.deepEqual(unknown, {
      status: 'REFUSED', code: 'UNKNOWN_ORIGIN_DEVICE', message: 'CANTEEN-09 is not a machine of this school', differences: [],
    });
    // WATER-02 is a machine of smk-beta, not of smk-alpha
    assert.equal(receive(water(card, { origin: 'WATER-02', n: 1, ml: 500 }), { uploader: 'KIOSK-01' }).code, 'UNKNOWN_ORIGIN_DEVICE');
    assert.equal(countRows('purchase'), 0);
    assert.equal(countRows('purchase', t.b), 0);
    assert.equal(wallet(t.a, 'aina'), 2000);
  });

  test('a broken call throws: it is a bug in the caller, not a problem with the record', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    assert.throws(() => t.settlement.receive({ schoolId: 'sch_nope', via: 'MQTT', record }), code('SCHOOL_NOT_FOUND', 404));
    assert.throws(() => t.settlement.receive(), code('SCHOOL_NOT_FOUND', 404));
    assert.throws(() => t.settlement.receive({ schoolId: t.a.id, via: 'PIGEON', record }), code('VIA_INVALID', 400));
    assert.throws(() => t.settlement.receive({ schoolId: t.a.id, record }), code('VIA_INVALID', 400));
    // the uploader is stored with the purchase, so it must be a machine of the same school
    const foreign = t.b.devices['CANTEEN-01'].id;
    assert.throws(() => t.settlement.receive({ schoolId: t.a.id, uploaderDeviceId: foreign, via: 'MQTT', record }), code('DEVICE_NOT_FOUND', 404));
    assert.equal(countRows('purchase'), 0);
    assert.equal(eventsOf(t.ctx, 'purchase.received').length, 0);
  });
});

describe('receive: checks on the money', () => {
  test('balance before minus amount must equal balance after (BALANCE_CONTINUITY)', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = { ...sale(card, { n: 1 }), balanceAfterSen: 1700 }; // 2000 - 350 is 1650
    const res = receive(record);
    assert.deepEqual([res.status, res.differences], ['POSTED', ['BALANCE_CONTINUITY']]);
    const [d] = diffsOf('BALANCE_CONTINUITY');
    assert.equal(d.ref, 'CANTEEN-01:CANTEEN-01-000001');
    assert.deepEqual(d.detail, {
      origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001', balanceBeforeSen: 2000, amountSen: 350, balanceAfterSen: 1700, expectedAfterSen: 1650,
    });
    assert.equal(wallet(t.a, 'aina'), 1650); // the amount is what moves, not the card's own arithmetic
    assertBooks();
  });

  test('two purchases with the same card counter point to a copied card (CARD_CLONE_SUSPECTED)', () => {
    const card = funded(t.a, 'aina', 2000);
    const copy = { ...card }; // the clone fault: the same chip memory, its own chip from now on
    const original = sale(card, { n: 1 });
    const cloned = sale(copy, { origin: 'CANTEEN-02', n: 1, items: [['MEE-GORENG', 1]] });
    assert.equal(original.cardSeq, cloned.cardSeq);
    assert.deepEqual(receive(original).differences, []);
    const res = receive(cloned, { via: 'JOURNAL_BATCH' });
    assert.deepEqual([res.status, res.differences], ['POSTED', ['CARD_CLONE_SUSPECTED']]);
    const [d] = diffsOf('CARD_CLONE_SUSPECTED');
    assert.equal(d.ref, `${card.digest}:1`);
    assert.deepEqual(d.detail, {
      last4: 'E5F6',
      cardSeq: 1,
      purchases: [{ origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001' }, { origin: 'CANTEEN-02', txn: 'CANTEEN-02-000001' }],
    });
    // both cards really paid: the books take both, and the original card no longer matches its mirror
    assert.equal(wallet(t.a, 'aina'), 2000 - 350 - 400);
    assert.notEqual(wallet(t.a, 'aina'), card.balanceSen);
    // the next purchases on each card carry on with their own counters
    assert.deepEqual(receive(sale(card, { n: 2, items: [['BUAH', 1]] })).differences, []);
    assertBooks();
  });

  test('a purchase that takes the mirror below zero is posted and flagged MIRROR_NEGATIVE', () => {
    const card = funded(t.a, 'aina', 500);
    card.balanceSen = 2000; // the chip holds a top-up the platform has not heard about yet
    const res = receive(sale(card, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 1]] })); // 530
    assert.deepEqual([res.status, res.differences], ['POSTED', ['MIRROR_NEGATIVE']]);
    assert.equal(wallet(t.a, 'aina'), -30);
    const memberId = t.a.members.aina.id;
    const [d] = diffsOf('MIRROR_NEGATIVE');
    assert.equal(d.ref, `${memberId}:CANTEEN-01-000001`);
    assert.deepEqual(d.detail, { memberId, origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001', amountSen: 530, walletSen: -30 });
    // each further purchase while below zero is its own difference
    assert.deepEqual(receive(sale(card, { n: 2, items: [['BUAH', 1]] })).differences, ['MIRROR_NEGATIVE']);
    assert.equal(wallet(t.a, 'aina'), -130);
    // a zero-amount record moves nothing, so it takes nothing below zero
    const v2 = t.configs.publish({
      schoolId: t.a.id, kind: 'prices', content: { ...DEFAULT_PRICES, water: { perLitreSen: 20, minChargeSen: 0 } }, actor: 'test',
    });
    assert.deepEqual(receive(water(card, { n: 1, ml: 20, minChargeSen: 0, priceVersion: v2.version })).differences, []);
    assert.equal(diffsOf('MIRROR_NEGATIVE').length, 2);
    // the books still balance with a wallet below zero
    assertBooks();
  });

  test('every check that fails is reported, in the order of the steps', () => {
    const card = funded(t.a, 'aina', 300);
    card.balanceSen = 2000; // the chip holds more than the mirror
    const copy = { ...card };
    const lost = t.schools.markCardLost({ schoolId: t.a.id, uid: t.a.members.aina.uid, actor: 'test' });
    t.schools.setLostListVersion(t.a.id, lost.id, t.configs.blockCard({ schoolId: t.a.id, cardId: lost.id, actor: 'test' }).version);
    assert.deepEqual(receive(sale(copy, { origin: 'CANTEEN-02', n: 1, items: [['BUAH', 1]] })).differences, ['SPENT_AFTER_LOST_REPORT']);
    // charged 300 for a 350 nasi lemak, the card's arithmetic is off, same counter as the copy, and more than the mirror holds
    const record = { ...sale(card, { n: 1, items: [['NASI-LEMAK', 1, 300]] }), balanceAfterSen: 1 };
    const res = receive(record);
    assert.equal(res.status, 'POSTED');
    assert.deepEqual(res.differences, ['PRICE_MISMATCH', 'BALANCE_CONTINUITY', 'CARD_CLONE_SUSPECTED', 'SPENT_AFTER_LOST_REPORT', 'MIRROR_NEGATIVE']);
    assert.equal(wallet(t.a, 'aina'), 300 - 100 - 300);
    assertBooks();
  });
});

describe('receive: a card reported lost', () => {
  /** The office reports Aina's card lost now: LOST, blocked in a new list version, the version stored. */
  function reportLost({ storeVersion = true } = {}) {
    const card = t.schools.markCardLost({ schoolId: t.a.id, uid: t.a.members.aina.uid, actor: 'test' });
    const { version } = t.configs.blockCard({ schoolId: t.a.id, cardId: card.id, actor: 'test' });
    if (storeVersion) t.schools.setLostListVersion(t.a.id, card.id, version);
    return { ...card, version };
  }

  test('a purchase made before the report is fine, even when it arrives after it', () => {
    const card = funded(t.a, 'aina', 2000);
    const before = sale(card, { origin: 'CANTEEN-02', n: 1 });
    t.ctx.clock.advance(MINUTE);
    reportLost();
    t.ctx.clock.advance(HOUR);
    assert.deepEqual(receive(before, { via: 'JOURNAL_BATCH' }).differences, []);
    assert.equal(diffsOf('SPENT_AFTER_LOST_REPORT').length, 0);
  });

  test('spent from the moment of the report on a machine still on the old list: machineHadUpdatedList false', () => {
    const card = funded(t.a, 'aina', 2000);
    t.ctx.clock.advance(MINUTE);
    const lost = reportLost();
    assert.equal(lost.version, 2); // list version 2 is the first to carry the card
    const atReport = sale(card, { origin: 'CANTEEN-02', n: 1, at: toIso(lost.lostAt) }); // the same instant counts
    t.ctx.clock.advance(5 * MINUTE);
    const later = sale(card, { origin: 'CANTEEN-02', n: 2, listVersion: 1 });
    for (const record of [atReport, later]) {
      const res = receive(record, { via: 'JOURNAL_BATCH' });
      assert.deepEqual([res.status, res.differences], ['POSTED', ['SPENT_AFTER_LOST_REPORT']]);
    }
    const found = diffsOf('SPENT_AFTER_LOST_REPORT');
    assert.deepEqual(found.map((d) => d.ref).sort(), ['CANTEEN-02:CANTEEN-02-000001', 'CANTEEN-02:CANTEEN-02-000002']);
    for (const d of found) assert.deepEqual(d.detail, { listVersionOnMachine: 1, lostListVersion: 2, machineHadUpdatedList: false });
    assert.equal(wallet(t.a, 'aina'), 1300); // the card really paid
    assertBooks();
  });

  test('spent on a machine that already had the list blocking the card: machineHadUpdatedList true', () => {
    const card = funded(t.a, 'aina', 2000);
    reportLost();
    t.ctx.clock.advance(MINUTE);
    assert.deepEqual(receive(sale(card, { n: 1, listVersion: 2 })).differences, ['SPENT_AFTER_LOST_REPORT']);
    assert.deepEqual(receive(sale(card, { n: 2, listVersion: 3 })).differences, ['SPENT_AFTER_LOST_REPORT']);
    for (const d of diffsOf('SPENT_AFTER_LOST_REPORT')) {
      assert.equal(d.detail.lostListVersion, 2);
      assert.equal(d.detail.machineHadUpdatedList, true);
    }
    assertBooks();
  });

  test('before the block-list version is stored, no machine can have had it', () => {
    const card = funded(t.a, 'aina', 2000);
    reportLost({ storeVersion: false });
    const res = receive(sale(card, { n: 1, listVersion: 5 }));
    assert.deepEqual(res.differences, ['SPENT_AFTER_LOST_REPORT']);
    assert.deepEqual(diffsOf('SPENT_AFTER_LOST_REPORT')[0].detail, { listVersionOnMachine: 5, lostListVersion: null, machineHadUpdatedList: false });
  });

  test('a card found again is no longer flagged', () => {
    const card = funded(t.a, 'aina', 2000);
    reportLost();
    t.schools.markCardFound({ schoolId: t.a.id, uid: t.a.members.aina.uid, actor: 'test' });
    assert.deepEqual(receive(sale(card, { n: 1 })).differences, []);
  });
});

describe('receive: on time or late', () => {
  test('over MQTT within 24 hours is on time; journal batches, read-backs and USB files are late', () => {
    const card = funded(t.a, 'aina', 5000);
    const results = {
      MQTT: receive(sale(card, { n: 1 })),
      JOURNAL_BATCH: receive(sale(card, { n: 2 }), { via: 'JOURNAL_BATCH' }),
      KIOSK_READBACK: receive(sale(card, { n: 3 }), { via: 'KIOSK_READBACK' }),
      USB_IMPORT: receive(sale(card, { n: 4 }), { via: 'USB_IMPORT', uploader: null }),
    };
    for (const [via, res] of Object.entries(results)) {
      const row = purchaseRow(res.purchaseId);
      assert.equal(row.via, via);
      assert.equal(row.late, via === 'MQTT' ? 0 : 1, via);
    }
    // the machine that delivered each copy
    assert.equal(purchaseRow(results.KIOSK_READBACK.purchaseId).uploader_device_id, t.a.devices['KIOSK-01'].id);
    assert.equal(purchaseRow(results.USB_IMPORT.purchaseId).uploader_device_id, null);
    const late = Object.fromEntries(t.settlement.listPurchases(t.a.id).map((p) => [p.via, p.late]));
    assert.deepEqual(late, { MQTT: false, JOURNAL_BATCH: true, KIOSK_READBACK: true, USB_IMPORT: true });
  });

  test('more than 24 hours after the sale is late even over MQTT; exactly 24 hours is not', () => {
    const card = funded(t.a, 'aina', 5000);
    const exactly = sale(card, { n: 1 });
    const over = sale(card, { n: 2, at: toIso(T0 - 1) });
    t.ctx.clock.advance(DAY);
    assert.equal(purchaseRow(receive(exactly).purchaseId).late, 0);
    assert.equal(purchaseRow(receive(over).purchaseId).late, 1);
    // a record stamped ahead of the platform clock is not late
    const ahead = sale(card, { n: 3, at: toIso(t.ctx.clock.now() + HOUR) });
    assert.equal(purchaseRow(receive(ahead).purchaseId).late, 0);
  });
});

describe('receive: events and transactions', () => {
  test('purchase.received tells the lab console what happened, with the school code', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    const posted = receive(record);
    receive(record, { via: 'JOURNAL_BATCH' });
    receive({ ...record, listVersion: 9 });
    const flagged = receive(sale(chip(t.a, '04FFEEDDCCBBAA', 900), { n: 2 }));
    receive({ ...record, kind: 'TOPUP' });
    receive('garbage', { uploader: 'CANTEEN-01' });
    const elsewhere = receive(sale(funded(t.b, 'chong', 900), { n: 1 }), { school: t.b });
    const base = { origin: 'CANTEEN-01', txn: 'CANTEEN-01-000001', amountSen: 350, via: 'MQTT' };
    assert.deepEqual(eventsOf(t.ctx, 'purchase.received').map((e) => [e.school, e.data]), [
      ['smk-alpha', { ...base, purchaseId: posted.purchaseId, status: 'POSTED', differences: [] }],
      ['smk-alpha', { ...base, purchaseId: posted.purchaseId, status: 'DUPLICATE', differences: [], via: 'JOURNAL_BATCH' }],
      ['smk-alpha', { ...base, purchaseId: posted.purchaseId, status: 'DUPLICATE', code: 'CONFLICT', differences: ['DUPLICATE_CONFLICT'] }],
      ['smk-alpha', { ...base, purchaseId: flagged.purchaseId, txn: 'CANTEEN-01-000002', status: 'FLAGGED', differences: ['UNKNOWN_CARD'] }],
      ['smk-alpha', { ...base, purchaseId: null, status: 'REFUSED', code: 'RECORD_INVALID', differences: [] }],
      ['smk-alpha', { purchaseId: null, origin: null, txn: null, amountSen: null, status: 'REFUSED', code: 'RECORD_INVALID', differences: [], via: 'MQTT' }],
      ['smk-beta', { ...base, purchaseId: elsewhere.purchaseId, status: 'POSTED', differences: [] }],
    ]);
    // each opened difference is announced too
    assert.deepEqual(eventsOf(t.ctx, 'difference.opened').map((e) => [e.school, e.data.kind]), [
      ['smk-alpha', 'DUPLICATE_CONFLICT'],
      ['smk-alpha', 'UNKNOWN_CARD'],
    ]);
  });

  test('when anything fails after the posting, the purchase and its posting are rolled back together', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    const broken = createSettlement(t.ctx, { ...services(), ledger: { ...t.ledger, balance() { throw new Error('disk unplugged'); } } });
    assert.throws(() => broken.receive({ schoolId: t.a.id, via: 'MQTT', record }), /disk unplugged/);
    assert.equal(countRows('purchase'), 0);
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:CANTEEN-01:CANTEEN-01-000001'), null);
    assert.equal(wallet(t.a, 'aina'), 2000);
    assert.equal(eventsOf(t.ctx, 'purchase.received').length, 0);
    // nothing was left behind, so the real upload is a first copy, not a duplicate
    assert.equal(receive(record).status, 'POSTED');
    assertBooks();
  });

  test('when opening a difference fails, nothing of the record is kept', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = { ...sale(card, { n: 1, priceVersion: 7 }), balanceAfterSen: 1 }; // two differences to open
    let calls = 0;
    const flaky = {
      ...t.differences,
      open(args) {
        calls += 1;
        if (calls === 2) throw new Error('disk unplugged');
        return t.differences.open(args);
      },
    };
    const broken = createSettlement(t.ctx, { ...services(), differences: flaky });
    assert.throws(() => broken.receive({ schoolId: t.a.id, via: 'MQTT', record }), /disk unplugged/);
    assert.equal(calls, 2);
    assert.equal(countRows('purchase'), 0);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.equal(t.ledger.findByIdemKey(t.a.id, 'PURCHASE:CANTEEN-01:CANTEEN-01-000001'), null);
    assert.deepEqual(receive(record).differences, ['PRICE_VERSION_UNKNOWN', 'BALANCE_CONTINUITY']);
    assertBooks();
  });

  test('inside a caller\'s transaction the record becomes part of it', () => {
    const card = funded(t.a, 'aina', 2000);
    assert.throws(() =>
      t.ctx.db.tx(() => {
        assert.equal(receive(sale(card, { n: 1 })).status, 'POSTED');
        throw new Error('the caller changed its mind');
      }), /changed its mind/);
    assert.equal(countRows('purchase'), 0);
    assert.equal(wallet(t.a, 'aina'), 2000);
    assertBooks();
  });
});

describe('listPurchases', () => {
  test('newest sale first, with the fields from DESIGN.md §4.6', () => {
    const aina = funded(t.a, 'aina', 3000);
    const badrul = funded(t.a, 'badrul', 3000);
    const s1 = receive(sale(aina, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 2]] }));
    t.ctx.clock.advance(MINUTE);
    const w1 = receive(water(badrul, { n: 1, ml: 650 }));
    t.ctx.clock.advance(MINUTE);
    // made an hour ago on an offline reader, arriving last: it takes its place by when it happened
    const early = sale(badrul, { origin: 'CANTEEN-02', n: 1, at: toIso(t.ctx.clock.now() - HOUR) });
    t.ctx.clock.advance(MINUTE);
    const e1 = receive(early, { via: 'JOURNAL_BATCH' });

    const list = t.settlement.listPurchases(t.a.id);
    assert.deepEqual(list.map((p) => p.id), [w1.purchaseId, s1.purchaseId, e1.purchaseId]);
    for (const p of list) assert.deepEqual(Object.keys(p).sort(), DTO_KEYS);
    assert.deepEqual(list[1], {
      id: s1.purchaseId,
      originDeviceCode: 'CANTEEN-01',
      txn: 'CANTEEN-01-000001',
      via: 'MQTT',
      kind: 'SALE',
      memberId: t.a.members.aina.id,
      memberName: 'Aina Alpha',
      amountSen: 710,
      ml: null,
      items: [{ code: 'NASI-LEMAK', qty: 1, priceSen: 350 }, { code: 'TEH-TARIK', qty: 2, priceSen: 180 }],
      priceVersion: 1,
      listVersion: 1,
      occurredAt: T0,
      receivedAt: T0,
      status: 'POSTED',
      late: false,
    });
    assert.deepEqual(
      [list[0].kind, list[0].ml, list[0].items, list[0].amountSen, list[0].memberName, list[0].occurredAt],
      ['WATER', 650, [], 13, 'Badrul Alpha', T0 + MINUTE],
    );
    assert.deepEqual([list[2].via, list[2].late, list[2].occurredAt, list[2].receivedAt], ['JOURNAL_BATCH', true, T0 + 2 * MINUTE - HOUR, T0 + 3 * MINUTE]);
  });

  test('keeps only the fields the record format defines for each item', () => {
    const card = funded(t.a, 'aina', 2000);
    const record = sale(card, { n: 1 });
    record.items[0].note = 'extra field a machine added';
    receive(record);
    assert.deepEqual(t.settlement.listPurchases(t.a.id)[0].items, [{ code: 'NASI-LEMAK', qty: 1, priceSen: 350 }]);
  });

  test('filters by member and by origin machine, and takes a limit', () => {
    const aina = funded(t.a, 'aina', 5000);
    const badrul = funded(t.a, 'badrul', 5000);
    const ids = [];
    ids.push(receive(sale(aina, { n: 1 })).purchaseId);
    t.ctx.clock.advance(MINUTE);
    ids.push(receive(water(aina, { n: 1, ml: 650 })).purchaseId);
    t.ctx.clock.advance(MINUTE);
    ids.push(receive(sale(badrul, { n: 2 })).purchaseId);
    t.ctx.clock.advance(MINUTE);
    ids.push(receive(sale(chip(t.a, '04FFEEDDCCBBAA', 900), { origin: 'CANTEEN-02', n: 1 })).purchaseId);
    const newestFirst = [...ids].reverse();
    const idsOf = (options) => t.settlement.listPurchases(t.a.id, options).map((p) => p.id);

    assert.deepEqual(idsOf(), newestFirst);
    assert.deepEqual(idsOf({ memberId: t.a.members.aina.id }), [ids[1], ids[0]]);
    assert.deepEqual(idsOf({ deviceCode: 'CANTEEN-01' }), [ids[2], ids[0]]);
    assert.deepEqual(idsOf({ deviceCode: ' canteen-01 ' }), [ids[2], ids[0]]); // office input
    assert.deepEqual(idsOf({ memberId: t.a.members.aina.id, deviceCode: 'CANTEEN-01' }), [ids[0]]);
    assert.deepEqual(idsOf({ memberId: '', deviceCode: null }), newestFirst); // empty filters filter nothing
    // the unknown card's purchase has no member
    const [flagged] = t.settlement.listPurchases(t.a.id, { deviceCode: 'CANTEEN-02' });
    assert.deepEqual([flagged.status, flagged.memberId, flagged.memberName], ['FLAGGED', null, null]);
    // limit: a number or the query string's text; anything unusable means the default (100)
    assert.deepEqual(idsOf({ limit: 1 }), [ids[3]]);
    assert.deepEqual(idsOf({ limit: '2' }), [ids[3], ids[2]]);
    for (const limit of [0, -1, 'all', 1.5, null]) assert.deepEqual(idsOf({ limit }), newestFirst, String(limit));
    assert.deepEqual(t.settlement.listPurchases(t.a.id, null).map((p) => p.id), newestFirst);
  });

  test("another school's purchases are never visible", () => {
    const aina = funded(t.a, 'aina', 2000);
    const chong = funded(t.b, 'chong', 2000);
    // the same machine code and txn in two schools are two different purchases
    const inA = receive(sale(aina, { n: 1 }));
    const inB = receive(sale(chong, { n: 1, items: [['MEE-GORENG', 1]] }), { school: t.b });
    assert.equal(inB.status, 'POSTED');
    assert.deepEqual(t.settlement.listPurchases(t.a.id).map((p) => p.id), [inA.purchaseId]);
    assert.deepEqual(t.settlement.listPurchases(t.b.id).map((p) => p.id), [inB.purchaseId]);
    assert.deepEqual(t.settlement.listPurchases(t.b.id, { memberId: t.a.members.aina.id }), []);
    assert.deepEqual(t.settlement.listPurchases(t.a.id, { deviceCode: 'WATER-02' }), []);
    assert.deepEqual(t.settlement.listPurchases('sch_nope'), []);
    assert.deepEqual(t.settlement.listPurchases(undefined), []);
    // each school's books carry only its own sale
    assert.equal(t.ledger.balance(t.a.id, 'SALES_PAYABLE'), 350);
    assert.equal(t.ledger.balance(t.b.id, 'SALES_PAYABLE'), 400);
    assert.deepEqual([wallet(t.a, 'aina'), wallet(t.b, 'chong')], [1650, 1600]);
    assertBooks();
    assertBooks(t.b);
  });
});

describe('salesReport', () => {
  // Kuala Lumpur midnight between Monday 5 and Tuesday 6 October 2026 is 16:00 UTC on the 5th.
  const MIDNIGHT = parseIso('2026-10-05T16:00:00.000Z');
  const at = (ms) => toIso(ms);

  test('adds up the posted purchases of one Kuala Lumpur day, by machine and by item', () => {
    const aina = funded(t.a, 'aina', 5000);
    const badrul = funded(t.a, 'badrul', 5000);
    t.ctx.clock.advance(MIDNIGHT + HOUR - t.ctx.clock.now()); // 01:00 on Tuesday in Kuala Lumpur
    // Monday 10:00, 22:00 and 23:59 in Kuala Lumpur
    receive(sale(aina, { n: 1, items: [['NASI-LEMAK', 1], ['TEH-TARIK', 1]], at: at(MIDNIGHT - 14 * HOUR) }), { via: 'JOURNAL_BATCH' });
    receive(water(aina, { n: 1, ml: 650, at: at(MIDNIGHT - 2 * HOUR) }), { via: 'USB_IMPORT', uploader: null });
    receive(sale(badrul, { origin: 'CANTEEN-02', n: 1, items: [['TEH-TARIK', 2]], at: at(MIDNIGHT - MINUTE) }), { via: 'JOURNAL_BATCH' });
    // Tuesday 00:01
    receive(sale(badrul, { n: 2, items: [['ROTI-CANAI', 1], ['TEH-TARIK', 1]], at: at(MIDNIGHT + MINUTE) }));
    // not a sale yet: an unknown card's purchase waits for a person
    receive(sale(chip(t.a, '04FFEEDDCCBBAA', 900), { n: 3, at: at(MIDNIGHT - HOUR) }));

    const monday = t.settlement.salesReport(t.a.id, { day: '2026-10-05' });
    assert.deepEqual(monday, {
      day: '2026-10-05',
      totalSen: 530 + 13 + 360,
      count: 3,
      byDevice: [
        { deviceCode: 'CANTEEN-01', kind: 'SALE', count: 1, totalSen: 530 },
        { deviceCode: 'CANTEEN-02', kind: 'SALE', count: 1, totalSen: 360 },
        { deviceCode: 'WATER-01', kind: 'WATER', count: 1, totalSen: 13 },
      ],
      byItem: [
        { code: 'NASI-LEMAK', qty: 1, totalSen: 350 },
        { code: 'TEH-TARIK', qty: 3, totalSen: 540 },
      ],
    });
    const tuesday = t.settlement.salesReport(t.a.id, { day: '2026-10-06' });
    assert.deepEqual(tuesday, {
      day: '2026-10-06',
      totalSen: 330,
      count: 1,
      byDevice: [{ deviceCode: 'CANTEEN-01', kind: 'SALE', count: 1, totalSen: 330 }],
      byItem: [
        { code: 'ROTI-CANAI', qty: 1, totalSen: 150 },
        { code: 'TEH-TARIK', qty: 1, totalSen: 180 },
      ],
    });
    // no day means today in Kuala Lumpur, which is already Tuesday at 17:00 UTC
    assert.deepEqual(t.settlement.salesReport(t.a.id), tuesday);
    assert.deepEqual(t.settlement.salesReport(t.a.id, { day: '' }), tuesday);
    assert.deepEqual(t.settlement.salesReport(t.a.id, { day: '2026-10-04' }), { day: '2026-10-04', totalSen: 0, count: 0, byDevice: [], byItem: [] });
  });

  test('a zero-amount purchase counts as a sale of nothing', () => {
    const v2 = t.configs.publish({
      schoolId: t.a.id, kind: 'prices', content: { ...DEFAULT_PRICES, water: { perLitreSen: 20, minChargeSen: 0 } }, actor: 'test',
    });
    const card = funded(t.a, 'aina', 1000);
    receive(water(card, { n: 1, ml: 20, minChargeSen: 0, priceVersion: v2.version }));
    assert.deepEqual(t.settlement.salesReport(t.a.id, { day: '2026-10-05' }), {
      day: '2026-10-05', totalSen: 0, count: 1, byDevice: [{ deviceCode: 'WATER-01', kind: 'WATER', count: 1, totalSen: 0 }], byItem: [],
    });
  });

  test('a day that is not a YYYY-MM-DD date is refused (DAY_INVALID)', () => {
    for (const day of ['2026-13-01', '2026-02-30', '05/10/2026', '2026-1-5', '2026-10-05T00:00', 20261005, {}]) {
      assert.throws(() => t.settlement.salesReport(t.a.id, { day }), code('DAY_INVALID', 400), String(day));
    }
    assert.equal(t.settlement.salesReport(t.a.id, { day: '2028-02-29' }).day, '2028-02-29'); // a leap day is a day
  });

  test("only counts the school's own sales", () => {
    receive(sale(funded(t.a, 'aina', 2000), { n: 1 }));
    receive(sale(funded(t.b, 'chong', 2000), { n: 1, items: [['MEE-GORENG', 1]] }), { school: t.b });
    assert.equal(t.settlement.salesReport(t.a.id).totalSen, 350);
    assert.equal(t.settlement.salesReport(t.b.id).totalSen, 400);
    assert.deepEqual(t.settlement.salesReport('sch_nope', { day: '2026-10-05' }), { day: '2026-10-05', totalSen: 0, count: 0, byDevice: [], byItem: [] });
  });
});

describe('the books after a busy day', () => {
  test('stay balanced, every mirror follows its card and sales payable equals the posted purchases', () => {
    const aina = funded(t.a, 'aina', 3000);
    const badrul = funded(t.a, 'badrul', 1500);
    const records = [
      sale(aina, { n: 1, items: [['NASI-LEMAK', 1], ['MILO-AIS', 1]] }),
      water(badrul, { n: 1, ml: 1200 }),
      sale(badrul, { origin: 'CANTEEN-02', n: 1, items: [['ROTI-CANAI', 2]] }),
      water(aina, { n: 2, ml: 330 }),
      sale(aina, { origin: 'CANTEEN-02', n: 2, items: [['MEE-GORENG', 1], ['AIR-SIRAP', 1]] }),
      sale(badrul, { n: 2, items: [['BUAH', 3]] }),
    ];
    // live, then every copy again by every other way, in a shuffled order
    for (const r of records) receive(r);
    for (const via of ['KIOSK_READBACK', 'JOURNAL_BATCH', 'USB_IMPORT']) {
      for (const r of [...records].reverse()) assert.equal(receive(r, { via }).status, 'DUPLICATE');
    }
    assert.equal(countRows('purchase'), records.length);
    assert.equal(wallet(t.a, 'aina'), aina.balanceSen);
    assert.equal(wallet(t.a, 'badrul'), badrul.balanceSen);
    const tb = assertBooks();
    const total = records.reduce((sum, r) => sum + r.amountSen, 0);
    assert.equal(t.ledger.balance(t.a.id, 'SALES_PAYABLE'), total);
    assert.equal(tb.totals.debitSen, tb.totals.creditSen);
    assert.equal(t.differences.list(t.a.id).length, 0);
    assert.equal(t.settlement.salesReport(t.a.id).totalSen, total);
  });
});
